package com.anesthesiaclinic.anesthesiabriefs.data.repository;

import androidx.compose.runtime.internal.StabilityInferred;
import com.anesthesiaclinic.anesthesiabriefs.data.model.DoseInfo;
import com.anesthesiaclinic.anesthesiabriefs.data.model.Drug;
import com.anesthesiaclinic.anesthesiabriefs.data.model.PharmacokineticsInfo;
import java.util.List;
import java.util.Map;
import kotlin.Metadata;
import kotlin.Pair;
import kotlin.TuplesKt;
import kotlin.collections.CollectionsKt;
import kotlin.collections.MapsKt;
import kotlin.jvm.internal.DefaultConstructorMarker;
import org.jetbrains.annotations.NotNull;

@Metadata(
   mv = {2, 2, 0},
   k = 1,
   xi = 48,
   d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003R\u0017\u0010\u0004\u001a\b\u0012\u0004\u0012\u00020\u00060\u0005¢\u0006\b\n\u0000\u001a\u0004\b\u0007\u0010\b¨\u0006\t"},
   d2 = {"Lcom/anesthesiaclinic/anesthesiabriefs/data/repository/SeedDataDrugsPart3;", "", "<init>", "()V", "drugsList", "", "Lcom/anesthesiaclinic/anesthesiabriefs/data/model/Drug;", "getDrugsList", "()Ljava/util/List;", "app_debug"}
)
@StabilityInferred(
   parameters = 0
)
public final class SeedDataDrugsPart3 {
   @NotNull
   public static final SeedDataDrugsPart3 INSTANCE = new SeedDataDrugsPart3();
   @NotNull
   private static final List drugsList;
   public static final int $stable;

   private SeedDataDrugsPart3() {
   }

   @NotNull
   public final List getDrugsList() {
      return drugsList;
   }

   static {
      Drug[] var0 = new Drug[23];
      List var10008 = CollectionsKt.emptyList();
      Map var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      Map var10014 = MapsKt.emptyMap();
      Pair[] var1 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      Map var10015 = MapsKt.mapOf(var1);
      List var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      List var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var2 = new String[]{"Tiyopental (Pentothal), kafa içi basıncını düşürür ve beyin koruyucu etkisi vardır.", "Enjeksiyon ağrısı yapabilir, intraarteriyel kaçışta şiddetli spazm ve nekroz riski vardır!"};
      var0[0] = new Drug("thiopental", "Tiyopental", "Thiopental", "Thiopental", var10008, "induction", (String)null, "Barbitürat grubu kısa etkili genel anestezik", "GABA-A reseptörü üzerinden klor kanallarını açık tutarak MSS depresyonu sağlar.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var2), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var2 = new String[]{"Diaѕtаt AcuDial [DSC];", "Diaѕtat Pediatric [DSC];", "ԁiаzеPΑM Intensol;", "Libеrvaոt [DSC];", "Valiսm;"};
      var10008 = CollectionsKt.listOf(var2);
      Pair[] var4 = new Pair[]{TuplesKt.to("premedikasyon", new DoseInfo("5.0 - 10.0 mg IV/Oral", "Operasyon öncesi veya sabahı anksiyoliz için.")), TuplesKt.to("nobet", new DoseInfo("5.0 - 10.0 mg IV yavaş", "Status epileptikusta ilk basamak tedavidir, 10-15 dk sonra tekrarlanabilir."))};
      var10013 = MapsKt.mapOf(var4);
      var4 = new Pair[]{TuplesKt.to("premedikasyon", new DoseInfo("0.1 - 0.2 mg/kg Oral/IV", "Maksimum 10 mg.")), TuplesKt.to("nobet", new DoseInfo("0.2 - 0.3 mg/kg IV yavaş", "Maksimum 5 mg. Gerekirse tekrarlanabilir."))};
      var10014 = MapsKt.mapOf(var4);
      var4 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde aktif metabolitlerin birikimi nedeniyle doz azaltılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde yarı ömrü belirgin uzar, doz azaltılması önerilir."), TuplesKt.to("obezite", "Dağılım hacmi artar, etki süresi uzayabilir."), TuplesKt.to("geriatri", "Yaşlılarda merkezi sinir sistemi duyarlılığı artmıştır, doz %50 azaltılmalıdır.")};
      var10015 = MapsKt.mapOf(var4);
      String[] var7 = new String[]{"Bileşenlerine karşı bilinen aşırı duyarlılık", "Akut dar açılı glokom", "Ciddi solunum yetmezliği"};
      var10017 = CollectionsKt.listOf(var7);
      var7 = new String[]{"Solunum depresyonu ve uzamış sedasyon riski.", "Opioidlerle kombine edildiğinde sinerjistik solunum depresyonu yapar."};
      var10018 = CollectionsKt.listOf(var7);
      var7 = new String[]{"Antikonvülzan ve kas gevşetici etkisi çok güçlüdür.", "Aktif metabolitleri nedeniyle etkisi çok uzundur, yaşlılarda birikir."};
      var0[1] = new Drug("diazepam", "Diazepam", "Diazepam", "Diazepam", var10008, "induction", (String)null, "Uzun etkili Benzodiazepin (GABA-A Allosterik Modülatör)", "GABA-A reseptörüne allosterik olarak bağlanarak GABA'nın inhibitör etkisini artırır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var7), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var7 = new String[]{"Αtivаn;", "ԼОRаzeрam Intensol;", "Լoreеv XR"};
      var10008 = CollectionsKt.listOf(var7);
      Pair[] var11 = new Pair[]{TuplesKt.to("premedikasyon", new DoseInfo("1.0 - 2.0 mg IV/Oral", "Anksiyolitik ve sedatif etki için.")), TuplesKt.to("nobet", new DoseInfo("2.0 - 4.0 mg IV yavaş", "Status epileptikusta çok etkilidir, yavaş enjekte edilmelidir."))};
      var10013 = MapsKt.mapOf(var11);
      var11 = new Pair[]{TuplesKt.to("premedikasyon", new DoseInfo("0.03 - 0.05 mg/kg Oral/IV", "Maksimum 2 mg.")), TuplesKt.to("nobet", new DoseInfo("0.05 - 0.1 mg/kg IV yavaş", "Maksimum 4 mg."))};
      var10014 = MapsKt.mapOf(var11);
      var11 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması genellikle gerekmez, ancak aktif metabolitlerin birikimi izlenmelidir."), TuplesKt.to("karaciger_yetmezligi", "Glukuronidasyon ile elendiği için diazepama göre karaciğer yetmezliğinde daha güvenlidir."), TuplesKt.to("obezite", "Dozaj yağ dışı vücut ağırlığına göre ayarlanmalıdır."), TuplesKt.to("geriatri", "Sedasyon ve paradoksal ajitasyon riski nedeniyle yaşlılarda doz yarıya indirilmelidir.")};
      var10015 = MapsKt.mapOf(var11);
      String[] var14 = new String[]{"Bileşenlerine karşı bilinen aşırı duyarlılık", "Ağır solunum yetmezliği", "Uyku apnesi"};
      var10017 = CollectionsKt.listOf(var14);
      var14 = new String[]{"Solunum depresyonu ve derin sedasyon.", "Hızlı IV enjeksiyonlarda apne riski vardır."};
      var10018 = CollectionsKt.listOf(var14);
      var14 = new String[]{"Premedikasyonda ve status epileptikusta sık kullanılır.", "Karaciğer yetmezliğinde konjugasyonla elendiği için diazepama göre daha güvenlidir."};
      var0[2] = new Drug("lorazepam", "Lorazepam", "Lorazepam", "Lorazepam", var10008, "induction", (String)null, "Orta etkili Benzodiazepin (GABA-A Allosterik Modülatör)", "GABA-A reseptörüne allosterik bağlanarak inhibitör GABAerjik sinaps iletimini kolaylaştırır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var14), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Ѕսрranе");
      var10013 = MapsKt.mapOf(TuplesKt.to("idame", new DoseInfo("4.0% - 8.0%", "MAC değeri yaşla azalır, O2/N2O karışımında doz azaltılabilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("idame", new DoseInfo("5.0% - 9.0%", "Hava yolu iritasyonu ve laringospazm riski nedeniyle indüksiyonda tercih edilmez.")));
      Pair[] var17 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Kan-gaz çözünürlüğü çok düşük olduğundan obez hastaların hızlı uyanması için idealdir."), TuplesKt.to("geriatri", "MAC değeri yaşlılarda belirgin olarak düşer, doz azaltılmalıdır.")};
      var10015 = MapsKt.mapOf(var17);
      String[] var18 = new String[]{"Malign hipertermi öyküsü veya genetik yatkınlık", "Halojenli ajanlara karşı aşırı duyarlılık"};
      var10017 = CollectionsKt.listOf(var18);
      var18 = new String[]{"Hava yollarını irite eder, öksürük ve laringospazma yol açabilir.", "Malign hipertermiyi tetikleyebilir."};
      var10018 = CollectionsKt.listOf(var18);
      var18 = new String[]{"Kan-gaz çözünürlüğü en düşük ajandır, uyanma son derece hızlıdır.", "Solunum yollarını irite eder, bronkospazm riski nedeniyle indüksiyonda kullanılmaz."};
      var0[3] = new Drug("desflurane", "Desfluran", "Desflurane", "Desflurane", var10008, "inhalational", (String)null, "Halojenli inhalasyon anestezik gaz", "Merkezi sinir sistemindeki sinaptik iletimi modüle eder, MAC değeri %6'dır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var18), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var18 = new String[]{"Forаne;", "Tеrrell"};
      var10008 = CollectionsKt.listOf(var18);
      var10013 = MapsKt.mapOf(TuplesKt.to("idame", new DoseInfo("1.0% - 2.5%", "MAC değeri %1.15'tir, cerrahi anestezi idamesinde kullanılır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("idame", new DoseInfo("1.5% - 3.0%", "Hava yollarını orta derecede uyarabilir.")));
      Pair[] var22 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Uyanma süresi sevoflurana göre biraz daha uzundur."), TuplesKt.to("geriatri", "MAC değeri yaşlılarda düşer, hemodinami yakından izlenmelidir.")};
      var10015 = MapsKt.mapOf(var22);
      String[] var23 = new String[]{"Malign hipertermi öyküsü veya genetik duyarlılık", "Halojenli anesteziklere karşı duyarlılık"};
      var10017 = CollectionsKt.listOf(var23);
      var23 = new String[]{"Doz bağımlı vazodilatasyon ve hipotansiyon yapar.", "Koroner çalma sendromuna (teorik) yol açabilir."};
      var10018 = CollectionsKt.listOf(var23);
      var23 = new String[]{"Kardiyoprotektif özellikleri ve ucuz olması nedeniyle sık tercih edilir.", "Koroner çalma sendromu yapabilir (teorik)."};
      var0[4] = new Drug("isoflurane", "İzofluran", "Isoflurane", "Isoflurane", var10008, "inhalational", (String)null, "Halojenli inhalasyon anestezik gaz", "Merkezi sinir sistemindeki sinaptik iletimi modüle eder, MAC değeri %1.15'tir.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var23), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("analjezi", new DoseInfo("30% - 70%", "Oksijen ile karıştırılarak minimum %30 O2 olacak şekilde verilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("analjezi", new DoseInfo("30% - 70%", "Pediatrik sedasyon ve kooperasyon desteğinde çok etkilidir.")));
      Pair[] var26 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Genellikle iyi tolere edilir, ancak kardiyak depresan etkisi yaşlılarda belirginleşebilir.")};
      var10015 = MapsKt.mapOf(var26);
      String[] var27 = new String[]{"Pnömotoraks, hava embolisi, bağırsak tıkanıklığı", "Yakın zamanda göz içi gaz enjeksiyonu öyküsü"};
      var10017 = CollectionsKt.listOf(var27);
      var27 = new String[]{"Kapalı boşluklardaki gaz hacmini genişletir (pnömotoraks, obstrüksiyon, kulak ameliyatlarında kontrendikedir).", "Difüzyon hipoksisi riski vardır, kapatıldıktan sonra %100 O2 verilmelidir."};
      var10018 = CollectionsKt.listOf(var27);
      var27 = new String[]{"Güçlü analjezik etkisi vardır, ancak tek başına anestezi sağlayamaz.", "Kapalı boşluklardaki (pnömotoraks, kulak cerrahileri vb.) gaz hacmini artırır, bu durumlarda kontrendikedir!"};
      var0[5] = new Drug("nitrous_oxide", "Nitröz Oksit", "Nitrous Oxide", "Nitrous oxide", var10008, "inhalational", (String)null, "İnorganik inhalasyon anestezik gazı", "NMDA reseptör antagonisti ve zayıf anestezik, güçlü analjeziktir, MAC değeri %104'tür.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var27), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var30 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var30);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var31 = new String[]{"Etki başlangıcı en hızlı olan opioiddir, günübirlik girişimsel işlemlerde tercih edilir.", "Göz içi basıncını düşürür, katarakt cerrahisinde etkilidir."};
      var0[6] = new Drug("alfentanil", "Alfentanil", "Alfentanil", "Alfentanil (United States and Canada", var10008, "opioid", (String)null, "Kısa etkili sentetik opioid analjezik", "Mu-opioid reseptör agonistidir.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var31), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Dѕuviа");
      Pair[] var32 = new Pair[]{TuplesKt.to("induksiyon", new DoseInfo("0.1 - 0.5 mcg/kg IV bolus", "Laringoskopi yanıtını baskılamak için indüksiyondan 2 dk önce uygulanır.")), TuplesKt.to("idame", new DoseInfo("0.05 - 0.2 mcg/kg/saat IV", "İnfüzyon şeklinde cerrahi idame analjezisinde titre edilir."))};
      var10013 = MapsKt.mapOf(var32);
      var10014 = MapsKt.mapOf(TuplesKt.to("induksiyon", new DoseInfo("0.1 - 0.2 mcg/kg IV", "Çocuklarda yakın solunum takibi ile yavaş bolus.")));
      var32 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekebilir, böbrek yetmezliğinde klirensi hafif azalabilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde metabolizma yavaşlar, etki süresi uzayabilir."), TuplesKt.to("obezite", "Dozaj ideal veya yağ dışı vücut ağırlığına göre yapılmalıdır."), TuplesKt.to("geriatri", "Yaşlılarda yarı ömrü belirgin uzar, doz %50 oranında azaltılmalıdır.")};
      var10015 = MapsKt.mapOf(var32);
      String[] var34 = new String[]{"Opioidlere karşı bilinen aşırı duyarlılık", "Akut veya şiddetli solunum depresyonu"};
      var10017 = CollectionsKt.listOf(var34);
      var34 = new String[]{"Hızlı IV enjeksiyonlarda göğüs duvarı sertliği (rijidite) yapabilir.", "Güçlü solunum depresyonu ve apne riski."};
      var10018 = CollectionsKt.listOf(var34);
      var34 = new String[]{"Morfine göre 500-1000 kat daha güçlüdür, majör kalp ve beyin cerrahisinde hemodinamik stabilite sağlar.", "Dozlama mikrogram (mcg) cinsindendir."};
      var0[7] = new Drug("sufentanil", "Sufentanil", "Sufentanil", "Sufentanil", var10008, "opioid", (String)null, "Çok güçlü sentetik opioid (Mu-Reseptör Agonisti)", "Mu-opioid reseptör agonistidir (Fentanilden 5-10 kat güçlü).", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var34), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var34 = new String[]{"СоոZip;", "Qdоlo [DSC];", "Ultram [DSC]"};
      var10008 = CollectionsKt.listOf(var34);
      var10013 = MapsKt.mapOf(TuplesKt.to("analjezi", new DoseInfo("50 - 100 mg IV", "Yavaş bolus veya serum içinde 15 dakikada enjekte edilir (Maks 400 mg/gün).")));
      var10014 = MapsKt.mapOf(TuplesKt.to("analjezi", new DoseInfo("1.0 - 2.0 mg/kg IV", "12 yaşından küçük çocuklarda solunum depresyonu riski nedeniyle kontrendikedir.")));
      Pair[] var38 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde (eGFR < 30) doz sıklığı 12 saatte bire düşürülmeli, günlük doz 200 mg'ı aşmamalıdır."), TuplesKt.to("karaciger_yetmezligi", "Ciddi karaciğer yetmezliğinde doz azaltılmalı, günde en fazla 100 mg verilmelidir."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Yaşlılarda nöbet ve konfüzyon riski artabilir, doz yavaş titre edilmelidir.")};
      var10015 = MapsKt.mapOf(var38);
      String[] var39 = new String[]{"MAO inhibitörü kullanımı (son 14 gün içinde)", "Kontrolsüz epilepsi", "12 yaş altı çocuklar"};
      var10017 = CollectionsKt.listOf(var39);
      var39 = new String[]{"Bulantı ve kusma sıklığı yüksektir (antiemetik ön tedavi önerilir).", "Nöbet eşiğini düşürür, epilepsi hastalarında kaçınılmalıdır."};
      var10018 = CollectionsKt.listOf(var39);
      var39 = new String[]{"Bulantı kusma yapma potansiyeli çok yüksektir.", "Serotonerjik etkisi nedeniyle MAO inhibitörleri ile kullanıldığında serotonin sendromu yapabilir."};
      var0[8] = new Drug("tramadol", "Tramadol", "Tramadol", "Tramadol", var10008, "opioid", (String)null, "Zayıf Mu-Opioid Agonisti ve Monoamin Geri Alım İnhibitörü", "Mu-opioid agonisti ve norepinefrin/serotonin geri alım inhibitörüdür.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var39), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Dеmеrοl");
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var42 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var42);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var43 = new String[]{"Postoperatif titreme tedavisinde (titreme önleyici olarak) altın standarttır.", "Aktif metaboliti normeperidin birikerek nöbete yol açabilir, böbrek yetmezliğinde kaçınılmalıdır."};
      var0[9] = new Drug("meperidine", "Petidin (Meperidin)", "Meperidine (Pethidine)", "Meperidine (pethidine)", var10008, "opioid", (String)null, "Sentetik opioid analjezik", "Mu-opioid reseptör agonistidir. Antikolinerjik etkileri vardır, titremeyi önler.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var43), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var43 = new String[]{"8 Hour Pain Reliever [OTC];", "8 HR Arthritis Pain Relief [OTC];", "Αϲеtаmiոорhеn 8 Hour [OTC];", "Αmiոοfeո [OTC];", "Aрrа [OTC];"};
      var10008 = CollectionsKt.listOf(var43);
      var10013 = MapsKt.mapOf(TuplesKt.to("analjezi", new DoseInfo("1000 mg IV", "15 dakikalık infüzyon şeklinde, 6 saat arayla uygulanabilir (Maks 4000 mg/gün).")));
      var10014 = MapsKt.mapOf(TuplesKt.to("analjezi", new DoseInfo("15 mg/kg IV", "6 saat arayla uygulanabilir (Maks 75 mg/kg/gün veya 4000 mg/gün).")));
      Pair[] var45 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Ağır böbrek yetmezliğinde (eGFR < 30) doz aralığı en az 6 saatten 8 saate çıkarılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliği veya kronik alkolizm durumunda hepatotoksisite riski nedeniyle günlük doz maksimum 2 g ile sınırlandırılmalıdır."), TuplesKt.to("obezite", "Dozaj ideal ağırlığa göre yapılmalıdır."), TuplesKt.to("geriatri", "Genellikle güvenlidir, ancak hepatik ve renal fonksiyonlar göz önünde bulundurulmalıdır.")};
      var10015 = MapsKt.mapOf(var45);
      String[] var46 = new String[]{"Ciddi karaciğer yetmezliği veya aktif hepatit", "Bileşenlerine karşı bilinen aşırı duyarlılık"};
      var10017 = CollectionsKt.listOf(var46);
      var46 = new String[]{"Aşırı dozda akut karaciğer nekrozu ve hepatotoksisite riski vardır.", "Günde toplam 4 gramlık doz kesinlikle aşılmamalıdır."};
      var10018 = CollectionsKt.listOf(var46);
      var46 = new String[]{"Karaciğer toksisitesini önlemek için günlük maksimum doz 4 gramı aşmamalıdır.", "IV infüzyon mutlaka 15 dakikada yavaşça yapılmalıdır."};
      var0[10] = new Drug("paracetamol", "Parasetamol", "Paracetamol (Acetaminophen)", "Acetaminophen (paracetamol)", var10008, "nonop_analgesic", (String)null, "Anilin türevi analjezik ve antipiretik (Non-opioid)", "Sentral prostaglandin sentezini inhibe eder.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var46), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var49 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var49);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var50 = new String[]{"Hızlı enjeksiyon ciddi hipotansiyona yol açar, yavaş IV infüzyon yapılmalıdır.", "Kemik iliği supresyonu ve agranülositoz riski (nadir) nedeniyle yakından izlenmelidir."};
      var0[11] = new Drug("metamizole", "Metamizol (Novalgin)", "Metamizole (Dipyrone)", "Dipyrone (metamizole)", var10008, "nonop_analgesic", (String)null, "Non-opioid analjezik ve antispazmodik", "COX inhibitörüdür, düz kas gevşetici etkisi de bulunur.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var50), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var51 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var51);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var52 = new String[]{"Güçlü analjezik etkisi vardır, akut postoperatif ağrıda sık tercih edilir.", "Renal perfüzyonu bozabileceği için hidrasyonu kötü hastalarda dikkat edilmelidir."};
      var0[12] = new Drug("dexketoprofen", "Deksketoprofen", "Dexketoprofen", "Dexketoprofen", var10008, "nonop_analgesic", (String)null, "NSAID (Nonsteroidal Anti-inflamatuar İlaç)", "COX-1 ve COX-2 inhibitörüdür.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var52), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var52 = new String[]{"Cаmbiа;", "Catаflam [DSC];", "Լоfеnа;", "Ζiрsоr;", "Ζοrvοlеx [DSC]"};
      var10008 = CollectionsKt.listOf(var52);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var54 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var54);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var55 = new String[]{"Böbrek taşı (renal kolik) ve postoperatif ağrıda çok etkilidir.", "Akut böbrek yetmezliği ve GİS kanama riski yakından izlenmelidir."};
      var0[13] = new Drug("diclofenac", "Diklofenak", "Diclofenac", "Diclofenac (systemic)", var10008, "nonop_analgesic", (String)null, "NSAID", "COX-1 ve COX-2 inhibitörüdür.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var55), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var55 = new String[]{"Αdԁаpriո [OTC];", "Aԁvil Junior Strength [OTC];", "Αԁvil Liqui-Gels minis [OTC];", "Advil Migraine [OTC];", "Αԁvil [OTC];"};
      var10008 = CollectionsKt.listOf(var55);
      var10013 = MapsKt.mapOf(TuplesKt.to("analjezi", new DoseInfo("400 mg IV veya 400 - 800 mg Oral", "Günde 3-4 kez yemeklerden sonra veya yavaş infüzyon şeklinde (Maks 3200 mg/gün).")));
      var10014 = MapsKt.mapOf(TuplesKt.to("analjezi", new DoseInfo("5.0 - 10.0 mg/kg Oral/IV", "6-8 saat arayla, pediatrik ateş ve hafif ağrı tedavisinde.")));
      Pair[] var57 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek perfüzyonunu azaltabilir, orta ve ağır böbrek yetmezliğinde kaçınılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Ağır karaciğer yetmezliğinde kullanılmamalıdır."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Gastrointestinal kanama ve böbrek hasarı riski yaşlılarda yüksektir, en düşük etkili doz tercih edilmelidir.")};
      var10015 = MapsKt.mapOf(var57);
      String[] var58 = new String[]{"Aktif gastrointestinal kanama veya peptik ülser", "Şiddetli kalp yetmezliği", "Gebeliğin üçüncü trimesteri"};
      var10017 = CollectionsKt.listOf(var58);
      var58 = new String[]{"Gastrointestinal ülserasyon ve kanama riskini artırır.", "Koroner baypas cerrahisi sonrası perioperatif dönemde kontrendikedir."};
      var10018 = CollectionsKt.listOf(var58);
      var58 = new String[]{"Pediatrik ve yetişkin postoperatif ağrı yönetiminde güvenilir bir seçenektir.", "Yemeklerle veya bol suyla alınmalıdır."};
      var0[14] = new Drug("ibuprofen", "İbuprofen", "Ibuprofen", "Ibuprofen", var10008, "nonop_analgesic", (String)null, "Nonsteroid Antiinflamatuar İlaç (NSAİİ - COX İnhibitörü)", "COX-1 ve COX-2 inhibitörüdür.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var58), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var61 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var61);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var62 = new String[]{"Analjezik gücü orta doz opioidlere eşdeğerdir.", "GİS kanama ve renal toksisite riski yüksek olduğu için ardışık kullanımı en fazla 5 günle sınırlandırılmalıdır."};
      var0[15] = new Drug("ketorolac", "Ketorolak", "Ketorolac", "Ketorolac (systemic)", var10008, "nonop_analgesic", (String)null, "NSAID", "Güçlü COX-1 ve COX-2 inhibitörüdür.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var62), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      Pair[] var63 = new Pair[]{TuplesKt.to("entubasyon", new DoseInfo("0.08 - 0.1 mg/kg IV", "Klinik gevşeme süresi yaklaşık 30-40 dakikadır.")), TuplesKt.to("idame", new DoseInfo("0.02 - 0.03 mg/kg IV bolus", "Cerrahi uyarının şiddetine ve TOF takibine göre titre edilir."))};
      var10013 = MapsKt.mapOf(var63);
      var10014 = MapsKt.mapOf(TuplesKt.to("entubasyon", new DoseInfo("0.1 mg/kg IV", "Bebeklerde ve çocuklarda roküronyuma alternatif olarak kullanılabilir.")));
      var63 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde aktif metabolitleri birikebilir ve nöromüsküler blok uzayabilir."), TuplesKt.to("karaciger_yetmezligi", "Biliyer eliminasyonla atıldığı için karaciğer yetmezliğinde ilacın etkisi belirgin şekilde uzar."), TuplesKt.to("obezite", "Doz ideal vücut ağırlığına göre hesaplanmalıdır."), TuplesKt.to("geriatri", "Eliminasyon yavaşlayacağı için yaşlılarda etki süresi uzar, TOF takibi kritik önemdedir.")};
      var10015 = MapsKt.mapOf(var63);
      var10017 = CollectionsKt.listOf("Nöromüsküler blokörlere karşı bilinen aşırı duyarlılık");
      String[] var65 = new String[]{"Etkisi Sugammadeks (2-4 mg/kg) veya Neostigmin ile geri döndürülebilir.", "Yalnızca mekanik ventilasyon desteği altındaki hastalara uygulanmalıdır."};
      var10018 = CollectionsKt.listOf(var65);
      var65 = new String[]{"Sugammadeks veya neostigmin ile etkisi geri döndürülebilir.", "Aktif metaboliti böbrek yetmezliğinde uzamış bloğa yol açabilir."};
      var0[16] = new Drug("vecuronium", "Veküronyum", "Vecuronium", "Vecuronium", var10008, "nmb", (String)null, "Depolarizan olmayan orta etkili nöromüsküler blokör (Asetilkolin Antagonisti)", "Kompetitif nikotinik asetilkolin reseptör antagonistidir.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var65), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      Pair[] var67 = new Pair[]{TuplesKt.to("entubasyon", new DoseInfo("0.4 - 0.5 mg/kg IV", "Klinik gevşeme süresi yaklaşık 20-35 dakikadır.")), TuplesKt.to("idame", new DoseInfo("0.08 - 0.1 mg/kg IV bolus", "Her 15-25 dakikada bir tekrarlanabilir."))};
      var10013 = MapsKt.mapOf(var67);
      var10014 = MapsKt.mapOf(TuplesKt.to("entubasyon", new DoseInfo("0.4 - 0.5 mg/kg IV", "Çocuklarda güvenle uygulanabilir, histamin salınımına dikkat edilmelidir.")));
      var67 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Hofmann eliminasyonu ile elendiği için böbrek yetmezliğinde doz ayarlaması gerekmez, son derece güvenlidir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer perfüzyonundan bağımsız yıkıldığı için karaciğer yetmezliğinde en güvenli tercihlerdendir."), TuplesKt.to("obezite", "Dozaj ideal vücut ağırlığına göre hesaplanmalıdır."), TuplesKt.to("geriatri", "Hofmann eliminasyonu plazma pH ve sıcaklığına bağlı olduğundan yaşlılarda güvenle kullanılır.")};
      var10015 = MapsKt.mapOf(var67);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var69 = new String[]{"Histamin salınımına yol açabilir, hızlı IV boluslardan kaçınılmalıdır.", "Bronkospazm riski nedeniyle astım hastalarında dikkatli olunmalıdır."};
      var10018 = CollectionsKt.listOf(var69);
      var69 = new String[]{"Sıcaklık ve pH'a bağlı spontaneous (Hofmann) eliminasyonla yıkılır.", "Metaboliti laudanosin çok yüksek dozlarda santral sinir sistemi stimülasyonu yapabilir."};
      var0[17] = new Drug("atracurium", "Atrakuryum", "Atracurium", "Atracurium", var10008, "nmb", (String)null, "Depolarizan olmayan orta etkili nöromüsküler blokör (Benzilizokinolin)", "Kompetitif nikotinik asetilkolin reseptör antagonistidir. Hofmann eliminasyonu ile atılır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var69), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("geri_cevirme", new DoseInfo("0.2 mg IV bolus", "15 saniyede enjekte edilir. Gerekirse her 60 saniyede bir 0.1 - 0.3 mg eklenerek toplam 1.0 mg'a kadar titre edilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("geri_cevirme", new DoseInfo("0.01 mg/kg IV", "Maksimum tek doz 0.2 mg, gerekirse tekrarlanabilir.")));
      Pair[] var71 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde eliminasyonu gecikebilir, tekrarlayan dozlarda dikkatli olunmalıdır."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Genellikle güvenlidir, ancak uyanma sırasında ajitasyon riski izlenmelidir.")};
      var10015 = MapsKt.mapOf(var71);
      String[] var72 = new String[]{"Trisiklik antidepresan aşırı dozu veya zehirlenmesi", "Kafa içi basınç artışının olduğu durumlar"};
      var10017 = CollectionsKt.listOf(var72);
      var72 = new String[]{"Kronik benzodiazepin kullanan hastalarda aniden yoksunluk nöbetlerini tetikleyebilir.", "Yarı ömrü benzodiazepinlerden daha kısadır; hasta tekrar sedasyona girebilir (resedasyon takibi yapılmalıdır)."};
      var10018 = CollectionsKt.listOf(var72);
      var72 = new String[]{"Benzodiazepin doz aşımında veya sedasyonu sonlandırmada saniyeler içinde etki gösterir.", "Kronik benzodiazepin kullananlarda veya trisiklik antidepresan alanlarda nöbeti tetikleyebilir!"};
      var0[18] = new Drug("flumazenil", "Flumazenil", "Flumazenil", "Flumazenil", var10008, "reversal", (String)null, "Benzodiazepin Reseptör Antagonisti (Reversal)", "GABA-A reseptörü benzodiazepin bağlanma bölgesinde kompetitif antagonisttir.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var72), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var72 = new String[]{"Αkovaz;", "Bronkaid Max [OTC];", "Εmеrрhеԁ;", "Ρrimatеne [OTC];", "Rеziprеѕ [DSC]"};
      var10008 = CollectionsKt.listOf(var72);
      var10013 = MapsKt.mapOf(TuplesKt.to("bolus_hipotansiyon", new DoseInfo("5.0 - 10.0 mg IV bolus yavaş", "Gerekirse her 5-10 dakikada bir tekrarlanabilir. Genellikle spinal anestezi hipotansiyonunda tercih edilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("bolus_hipotansiyon", new DoseInfo("0.1 - 0.2 mg/kg IV bolus", "Çocuklarda bradikardinin eşlik ettiği hipotansiyon tedavisinde.")));
      Pair[] var76 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Dozaj standart ağırlığa göre titre edilir."), TuplesKt.to("geriatri", "Aritmi ve iskemik kalp hastalığı riskini artırabileceği için yaşlılarda doz düşürülmeli veya alternatif inotroplar düşünülmelidir.")};
      var10015 = MapsKt.mapOf(var76);
      String[] var77 = new String[]{"Taşiaritmi veya kontrolsüz hipertansiyon", "Dar açılı glokom"};
      var10017 = CollectionsKt.listOf(var77);
      var77 = new String[]{"Taşifilaksi: Tekrarlayan dozlarda noradrenalin depolarının tükenmesi sonucu ilacın etkisi azalır.", "Nabzı yüksek olan taşikardik hastalarda kaçınılmalıdır."};
      var0[19] = new Drug("ephedrine_systemic", "Ephedrine", "Ephedrine", "Ephedrine", var10008, "icu_metabolic", (String)null, "Sempatomimetik (Alfa ve Beta Adrenerjik Agonist)", "Klinik monograf bilgileri için kaynak dokümana başvurunuz.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, CollectionsKt.listOf(var77), (List)null, (List)null, CollectionsKt.listOf("UpToDate klinik monografından alınmıştır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var77 = new String[]{"Βiоrphеn;", "FT Nasal Decongestant PE [OTC];", "Ιmmрhentiv;", "Меԁi-Рhеnyl [OTC];", "Non-Pseudo Sinus Decongestant [OTC];"};
      var10008 = CollectionsKt.listOf(var77);
      Pair[] var80 = new Pair[]{TuplesKt.to("bolus_hipotansiyon", new DoseInfo("50 - 100 mcg IV bolus", "Tansiyon durumuna göre her 2-5 dakikada bir tekrarlanabilir.")), TuplesKt.to("infuzyon", new DoseInfo("0.1 - 1.5 mcg/kg/dk IV infüzyon", "Dirençli vazodilatasyon durumunda titre edilerek verilir."))};
      var10013 = MapsKt.mapOf(var80);
      var10014 = MapsKt.mapOf(TuplesKt.to("bolus_hipotansiyon", new DoseInfo("5.0 - 10.0 mcg/kg IV yavaş", "Çocuklarda vazodilatasyona bağlı hipotansiyon tedavisinde.")));
      var80 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek perfüzyonunu azaltabilir, dikkatli olunmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Dozaj ideal vücut ağırlığına göre titre edilmelidir."), TuplesKt.to("geriatri", "Refleks bradikardi yapma riski yaşlılarda daha yüksektir.")};
      var10015 = MapsKt.mapOf(var80);
      String[] var82 = new String[]{"Şiddetli bradikardi veya koroner arter hastalığı", "Ağır hipertansiyon"};
      var10017 = CollectionsKt.listOf(var82);
      var82 = new String[]{"Refleks Bradikardi: Tansiyonu yükseltirken kalp hızında baroreseptör aracılı düşüşe yol açar.", "Sol ventrikül yetmezliği olan hastalarda dikkatle kullanılmalıdır."};
      var0[20] = new Drug("phenylephrine_systemic", "Phenylephrine", "Phenylephrine", "Phenylephrine (systemic)", var10008, "icu_metabolic", (String)null, "Selektif Alfa-1 Adrenerjik Agonist", "Klinik monograf bilgileri için kaynak dokümana başvurunuz.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, CollectionsKt.listOf(var82), (List)null, (List)null, CollectionsKt.listOf("UpToDate klinik monografından alınmıştır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Լеvοрhеd");
      var10013 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("0.05 - 1.0 mcg/kg/dk IV", "Santral venöz kateter aracılığıyla titre edilerek uygulanmalıdır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("0.05 - 0.1 mcg/kg/dk IV", "Çocuklarda dirençli septik veya distributif şokta.")));
      Pair[] var84 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez, ancak renal perfüzyon yakından izlenmelidir."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Dozaj ideal ağırlığa göre yapılmalıdır."), TuplesKt.to("geriatri", "Ekstremitelerde vazokonstrüksiyon ve iskemi riski yaşlılarda yüksektir.")};
      var10015 = MapsKt.mapOf(var84);
      var10017 = CollectionsKt.listOf("Düzeltilmemiş ciddi hipovolemi (öncelikle sıvı resüsitasyonu yapılmalıdır)");
      String[] var85 = new String[]{"Ekstravazasyon Riski: Periferik damar dışına sızarsa şiddetli doku nekrozu yapar (santral hat zorunludur).", "Yüksek dozlarda mezenterik ve periferik organ kan akımını bozabilir."};
      var0[21] = new Drug("norepinephrine_noradrenaline", "Norepinephrine", "Norepinephrine", "Norepinephrine (noradrenaline)", var10008, "icu_metabolic", (String)null, "Güçlü Alfa ve Zayıf Beta-1 Agonist (Vazopresör)", "Klinik monograf bilgileri için kaynak dokümana başvurunuz.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, CollectionsKt.listOf(var85), (List)null, (List)null, CollectionsKt.listOf("UpToDate klinik monografından alınmıştır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var85 = new String[]{"Αԁreոаlin;", "Αԁrеոaliո-ΝаСl;", "Auvi-Q;", "Ерiոephriոe Professional;", "ЕΡΙΝЕΡΗriոеsnap;"};
      var10008 = CollectionsKt.listOf(var85);
      Pair[] var87 = new Pair[]{TuplesKt.to("kardiyak_arrest", new DoseInfo("1.0 mg IV/IO (her 3-5 dk)", "ACLS resüsitasyon standart dozudur.")), TuplesKt.to("anafilaksi", new DoseInfo("0.3 - 0.5 mg IM", "Uyluk dış yan kısmına (vastus lateralis) IM olarak uygulanır."))};
      var10013 = MapsKt.mapOf(var87);
      var87 = new Pair[]{TuplesKt.to("kardiyak_arrest", new DoseInfo("0.01 mg/kg IV/IO", "ACLS çocuk resüsitasyon dozu (0.1 mL/kg 1:10.000 solüsyonundan).")), TuplesKt.to("anafilaksi", new DoseInfo("0.01 mg/kg IM", "Maksimum tek doz 0.3 mg, IM olarak uyluk dış kısmına."))};
      var10014 = MapsKt.mapOf(var87);
      var87 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Resüsitasyonda standart dozlar kullanılır, infüzyonda ideal kiloya göre hesaplanır."), TuplesKt.to("geriatri", "Yaşlılarda taşiaritmi ve iskemik kalp hastalığı tetiklenme riski çok yüksektir.")};
      var10015 = MapsKt.mapOf(var87);
      var10017 = CollectionsKt.listOf("Mutlak bir kontrendikasyonu yoktur (kardiyak arrest ve anafilaksi durumlarında)");
      String[] var90 = new String[]{"Aşırı dozda şiddetli hipertansiyon, taşikardi ve aritmilere yol açar.", "İnfüzyon uygulamalarında santral hat kullanımı zorunludur."};
      var0[22] = new Drug("epinephrine_adrenaline_systemic", "Epinephrine", "Epinephrine", "Epinephrine (adrenaline) (systemic)", var10008, "icu_metabolic", (String)null, "Direkt Alfa ve Beta Adrenerjik Agonist (Katabolik)", "Klinik monograf bilgileri için kaynak dokümana başvurunuz.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, CollectionsKt.listOf(var90), (List)null, (List)null, CollectionsKt.listOf("UpToDate klinik monografından alınmıştır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      drugsList = CollectionsKt.listOf(var0);
      $stable = 8;
   }
}
