package com.anesthesiaclinic.anesthesiabriefs.data.repository;

import androidx.compose.runtime.internal.StabilityInferred;
import com.anesthesiaclinic.anesthesiabriefs.data.model.DoseInfo;
import com.anesthesiaclinic.anesthesiabriefs.data.model.Drug;
import com.anesthesiaclinic.anesthesiabriefs.data.model.PharmacokineticsInfo;
import java.util.List;
import java.util.Map;
import kotlin.Metadata;
import kotlin.Pair;
import kotlin.TuplesKt;
import kotlin.collections.CollectionsKt;
import kotlin.collections.MapsKt;
import kotlin.jvm.internal.DefaultConstructorMarker;
import org.jetbrains.annotations.NotNull;

@Metadata(
   mv = {2, 2, 0},
   k = 1,
   xi = 48,
   d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003R\u0017\u0010\u0004\u001a\b\u0012\u0004\u0012\u00020\u00060\u0005¢\u0006\b\n\u0000\u001a\u0004\b\u0007\u0010\b¨\u0006\t"},
   d2 = {"Lcom/anesthesiaclinic/anesthesiabriefs/data/repository/SeedDataDrugsPart1;", "", "<init>", "()V", "drugsList", "", "Lcom/anesthesiaclinic/anesthesiabriefs/data/model/Drug;", "getDrugsList", "()Ljava/util/List;", "app_debug"}
)
@StabilityInferred(
   parameters = 0
)
public final class SeedDataDrugsPart1 {
   @NotNull
   public static final SeedDataDrugsPart1 INSTANCE = new SeedDataDrugsPart1();
   @NotNull
   private static final List drugsList;
   public static final int $stable;

   private SeedDataDrugsPart1() {
   }

   @NotNull
   public final List getDrugsList() {
      return drugsList;
   }

   static {
      Drug[] var0 = new Drug[23];
      String[] var1 = new String[]{"Diprivan", "Propofol Lipuro"};
      List var10008 = CollectionsKt.listOf(var1);
      Pair[] var2 = new Pair[]{TuplesKt.to("induksiyon", new DoseInfo("1.5 - 2.5 mg/kg IV", "Yaşlı ve ASA III-IV hastalarda doz düşürülmelidir.")), TuplesKt.to("idame", new DoseInfo("100 - 200 mcg/kg/dk IV infüzyon", "TIVA (Total İntravenöz Anestezi) protokolünün temel taşıdır.")), TuplesKt.to("sedasyon", new DoseInfo("25 - 75 mcg/kg/dk IV infüzyon", "Yoğun bakım veya mekanik ventilasyon sedasyonu."))};
      Map var10013 = MapsKt.mapOf(var2);
      Map var10014 = MapsKt.mapOf(TuplesKt.to("induksiyon", new DoseInfo("2.5 - 4.0 mg/kg IV", "Çocuklarda dağılım hacmi daha yüksek olduğu için kilo başına doz daha fazladır.")));
      var2 = new Pair[]{TuplesKt.to("geriatri", "Doz 20-50% oranında düşürülmeli, yavaş titre edilmelidir."), TuplesKt.to("gebelik", "Gebelik kategorisi B. Plasentayı geçer, neonatal depresyona yol açabilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde klirens hafif azalabilir.")};
      Map var10015 = MapsKt.mapOf(var2);
      PharmacokineticsInfo var10016 = new PharmacokineticsInfo("30 - 45 saniye", "1 - 2 dakika", "5 - 10 dakika", "Dağılım yarı ömrü 2-4 dk, terminal yarı ömrü 24 saat", "Hızlı karaciğer metabolizması (konjugasyon), idrarla atılım");
      List var10017 = CollectionsKt.listOf("Yumurta, soya fasulyesi veya propofol bileşenlerine bilinen aşırı duyarlılık");
      String[] var4 = new String[]{"Ciddi hipotansiyon ve apne riski (özellikle hızlı enjeksiyonlarda)", "Yoğun bakımda 48 saatten uzun süre ve >4.8 mg/kg/saat dozda infüzyonlarda Propofol İnfüzyon Sendromu (PRIS) riski yakından izlenmelidir."};
      List var10018 = CollectionsKt.listOf(var4);
      var4 = new String[]{"Hipotansiyon", "Apne / Solunum Depresyonu", "Enjeksiyon yerinde şiddetli ağrı"};
      List var10019 = CollectionsKt.listOf(var4);
      var4 = new String[]{"Propofol İnfüzyon Sendromu (PRIS)", "Anafilaksi", "Şiddetli Bradyaritmi"};
      List var10020 = CollectionsKt.listOf(var4);
      var4 = new String[]{"Lipid emülsiyon bazlı olduğu için mikroorganizma üremesine çok elverişlidir. Enjektöre çekildikten sonra en geç 6 saat içinde tüketilmelidir.", "Enjeksiyon ağrısını azaltmak için öncesinde 10-20 mg lidokain IV olarak uygulanabilir."};
      var0[0] = new Drug("propofol", "Propofol", "Propofol", "Propofol", var10008, "induction", "N01AX10", "Kısa etkili genel anestezik (GABA-A Agonisti)", "GABA-A reseptör kompleksi üzerinde doğrudan agonist etki göstererek MSS depresyonu sağlar.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, var10020, CollectionsKt.listOf(var4), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var4 = new String[]{"Ketalar", "Ketamine"};
      var10008 = CollectionsKt.listOf(var4);
      Pair[] var9 = new Pair[]{TuplesKt.to("induksiyon", new DoseInfo("1.0 - 2.0 mg/kg IV veya 4.0 - 10.0 mg/kg IM", "Hemodinamik instabilite veya astımlı hastalarda tercih edilir.")), TuplesKt.to("analjezi", new DoseInfo("0.1 - 0.5 mg/kg IV bolus", "Multimodal analjezi veya postoperatif ağrı yönetimi."))};
      var10013 = MapsKt.mapOf(var9);
      var10014 = MapsKt.mapOf(TuplesKt.to("induksiyon", new DoseInfo("1.5 - 2.0 mg/kg IV veya 5.0 - 8.0 mg/kg IM", "Kooperasyon kurulamayan pediatrik hastalarda IM indüksiyonda etkilidir.")));
      var9 = new Pair[]{TuplesKt.to("geriatri", "Halüsinasyon ve deliryum riski nedeniyle yaşlılarda dozaj düşürülmeli, benzodiazepiner ile kombine edilmelidir."), TuplesKt.to("gebelik", "Gebelik kategorisi B. Yüksek dozlarda uterus tonusunu artırabilir.")};
      var10015 = MapsKt.mapOf(var9);
      var10016 = new PharmacokineticsInfo("30 saniye (IV), 3-4 dakika (IM)", "1 - 2 dakika (IV)", "10 - 20 dakika (IV), 60-120 dakika (IM)", "2 - 3 saat", "Karaciğerde aktif metabolit norketamine metabolize edilir, böbreklerden atılır");
      String[] var11 = new String[]{"Şiddetli kontrolsüz hipertansiyon, aktif iskemik kalp hastalığı", "Kafa içi basınç (ICP) artışının kritik olduğu durumlar (rölatif)"};
      var10017 = CollectionsKt.listOf(var11);
      var11 = new String[]{"Uyanma reaksiyonları (kabuslar, halüsinasyonlar, deliryum). Midazolam ön tedavisi bu riski azaltır.", "Sempatik stimülasyon: Hipertansiyon, taşikardi ve tükürük salgısında (salivasyon) artışa yol açar."};
      var10018 = CollectionsKt.listOf(var11);
      var11 = new String[]{"Taşikardi", "Hipertansiyon", "Salivasyon artışı", "Nistagmus"};
      var10019 = CollectionsKt.listOf(var11);
      var11 = new String[]{"Laringospazm", "Halüsinasyonlar / Uyanma deliryumu", "Göz içi basınç artışı"};
      var10020 = CollectionsKt.listOf(var11);
      var11 = new String[]{"Bronkodilatör etkisi nedeniyle şiddetli astım krizlerinde veya status asthmatikus olgularında hayat kurtarıcı bir indüksiyon ajanıdır.", "Kardiyak depresyonu sempatik deşarjla kompanse ettiği için hipovolemik şoktaki hastalarda ilk tercihtir."};
      var0[1] = new Drug("ketamine", "Ketamin", "Ketamine", "Ketamine Hydrochloride", var10008, "induction", "N01AX03", "Dissosiyatif anestezik (NMDA Reseptör Antagonisti)", "NMDA reseptörlerini bloke ederek talamokortikal sistemi dissosiye eder, güçlü analjezi ve amnezi sağlar.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, var10020, CollectionsKt.listOf(var11), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Hypnomidate");
      var10013 = MapsKt.mapOf(TuplesKt.to("induksiyon", new DoseInfo("0.2 - 0.3 mg/kg IV yavaş enjeksiyon", "Ciddi kardiyovasküler yetmezliği veya koroner arter hastalığı olanlarda tercih edilir.")));
      Pair[] var16 = new Pair[]{TuplesKt.to("geriatri", "Dozaj %20-30 oranında düşürülmeli, yavaş titre edilmelidir."), TuplesKt.to("sepsis", "Sepsisli hastalarda tek doz dahi olsa adrenal supresyon riski nedeniyle kaçınılmalıdır.")};
      var10015 = MapsKt.mapOf(var16);
      var10016 = new PharmacokineticsInfo("30 - 60 saniye", "1 dakika", "3 - 5 dakika", "2 - 5 saat", "Karaciğerde ester hidrolizi ile inaktif metabolitlerine ayrışır, idrarla atılır");
      String[] var17 = new String[]{"Etomidata karşı bilinen aşırı duyarlılık", "Adrenal yetmezlik, ciddi Addison hastalığı"};
      var10017 = CollectionsKt.listOf(var17);
      var17 = new String[]{"Geçici Adrenal Supresyon: 11-beta-hidroksilaz enzimini inhibe ederek kortizol sentezini 4-8 saat baskılar.", "Myoklonus riski yüksektir. Fentanil veya midazolam ön tedavisi myoklonusu azaltabilir."};
      var10018 = CollectionsKt.listOf(var17);
      var17 = new String[]{"Enjeksiyon yerinde ağrı", "Myoklonus (kas seğirmeleri)", "Bulantı ve kusma (postoperatif)"};
      var10019 = CollectionsKt.listOf(var17);
      var17 = new String[]{"Adrenokortikal supresyon", "Şiddetli bulantı kusma"};
      var0[2] = new Drug("etomidate", "Etomidat", "Etomidate", "Etomidate", var10008, "induction", "N01AX07", "Kısa etkili genel anestezik (GABA-A Agonisti)", "GABA-A reseptörlerine bağlanarak klor kanallarını açık tutar, hemodinamik parametreleri etkilemeden hipnoz sağlar.", var10013, (Map)null, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var17), CollectionsKt.listOf("Hemodinamik açıdan en stabil genel anesteziktir; kalp debisi, sistemik vasküler direnç ve miyokard kontraktilitesini neredeyse hiç değiştirmez."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201065472, (DefaultConstructorMarker)null);
      var17 = new String[]{"Dormicum", "Versed"};
      var10008 = CollectionsKt.listOf(var17);
      Pair[] var22 = new Pair[]{TuplesKt.to("premedikasyon", new DoseInfo("0.02 - 0.05 mg/kg IV veya 1.0 - 2.0 mg IV bolus", "Ameliyathaneye girmeden önce anksiyolitik etki sağlamak amacıyla kullanılır.")), TuplesKt.to("induksiyon", new DoseInfo("0.1 - 0.3 mg/kg IV", "Yalnızca diğer ajanların uygulanamadığı özel durumlarda indüksiyon dozu olarak tercih edilir.")), TuplesKt.to("sedasyon", new DoseInfo("0.05 - 0.1 mg/kg IV titre edilerek", "Girişimsel işlemler veya ICU sedasyonu."))};
      var10013 = MapsKt.mapOf(var22);
      var10014 = MapsKt.mapOf(TuplesKt.to("premedikasyon", new DoseInfo("0.5 mg/kg Oral (meyve suyu ile) veya 0.1 - 0.15 mg/kg IM", "Çocukları ebeveynlerinden ayırırken anksiyeteyi önlemek için çok etkilidir.")));
      var10016 = new PharmacokineticsInfo("1 - 2 dakika (IV), 15-20 dakika (Oral)", "3 - 5 dakika (IV)", "30 - 120 dakika (IV)", "1.5 - 2.5 saat (yaşlılarda ve karaciğer yetmezliğinde belirgin uzar)", "CYP3A4 ile metabolize edilerek idrarla atılır");
      String[] var23 = new String[]{"Akut dar açılı glokom", "Şiddetli KOAH veya solunum yetmezliği durumları"};
      var10017 = CollectionsKt.listOf(var23);
      var23 = new String[]{"Yaşlılarda uzamış sedasyon ve paradoksal ajitasyon (huzursuzluk) riskine dikkat edilmelidir.", "Opioidlerle kombine edildiğinde sinerjistik olarak şiddetli solunum depresyonu ve apneye yol açar."};
      var10018 = CollectionsKt.listOf(var23);
      var23 = new String[]{"Hafif hipotansiyon", "Solunum hızı azalması", "Anterograd amnezi (işlem anını hatırlamama)"};
      var10019 = CollectionsKt.listOf(var23);
      var23 = new String[]{"Apne / Solunum arresti", "Paradoksal reaksiyonlar (özellikle çocuklarda ve yaşlılarda ajitasyon)"};
      var10020 = CollectionsKt.listOf(var23);
      var23 = new String[]{"Etkisi Flumazenil (Anexate) ile saniyeler içinde tamamen geri döndürülebilir.", "Anterograd amnezi etkisi çok güçlüdür; hasta premedikasyon sonrası yaşanan olayları hatırlamaz."};
      var0[3] = new Drug("midazolam", "Midazolam", "Midazolam", "Midazolam Hydrochloride", var10008, "induction", "N05CD08", "Kısa etkili Benzodiazepin (GABA-A Pozitif Allosterik Modülatör)", "GABA-A reseptörlerindeki benzodiazepin bölgesine bağlanarak GABA'nın inhibitör etkisini güçlendirir; sedasyon, amnezi ve antikonvülzan etki sağlar.", var10013, var10014, (Map)null, var10016, var10017, var10018, var10019, var10020, CollectionsKt.listOf(var23), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201066496, (DefaultConstructorMarker)null);
      var23 = new String[]{"Fentanyl Citrate", "Talon"};
      var10008 = CollectionsKt.listOf(var23);
      Pair[] var29 = new Pair[]{TuplesKt.to("induksiyon", new DoseInfo("1 - 2 mcg/kg IV bolus", "Laringoskopiye hemodinamik yanıtı baskılamak için indüksiyondan 2-3 dk önce verilir.")), TuplesKt.to("intraoperatif_analjezi", new DoseInfo("2 - 10 mcg/kg IV", "Cerrahi uyarının şiddetine göre titre edilir.")), TuplesKt.to("postoperatif_agri", new DoseInfo("0.5 - 1.5 mcg/kg IV yavaş bolus", "Solunum hızı yakından izlenmelidir."))};
      var10013 = MapsKt.mapOf(var29);
      var29 = new Pair[]{TuplesKt.to("geriatri", "Klirens azalır, yarı ömür uzar. Doz %50 oranında düşürülmelidir."), TuplesKt.to("solunum_yetmezligi", "COPD veya uyku apnesi olan hastalarda ciddi solunum depresyonu riski.")};
      var10015 = MapsKt.mapOf(var29);
      var10016 = new PharmacokineticsInfo("1 - 2 dakika", "3 - 5 dakika", "30 - 60 dakika", "3 - 4 saat", "Karaciğerde CYP3A4 ile metabolize edilir, idrarla atılır");
      String[] var31 = new String[]{"Opioidlere karşı bilinen aşırı duyarlılık", "Akut veya şiddetli astım"};
      var10017 = CollectionsKt.listOf(var31);
      var31 = new String[]{"Hızlı IV enjeksiyonlarda göğüs duvarı rijiditesi (Ahşap Göğüs) gelişebilir. Bu durumda NMB veya naloksan gerekir.", "Diğer MSS depresanları ve inhalasyon ajanlarıyla sinerjistik etki göstererek şiddetli hipotansiyon ve apneye yol açar."};
      var10018 = CollectionsKt.listOf(var31);
      var31 = new String[]{"Bulantı / Kusma", "Kaşıntı (burun ucunda)", "Bradikardi", "Miyozis"};
      var10019 = CollectionsKt.listOf(var31);
      var31 = new String[]{"Solunum Depresyonu / Apne", "Göğüs Duvarı Rijiditesi"};
      var0[4] = new Drug("fentanyl", "Fentanil", "Fentanyl", "Fentanyl Citrate", var10008, "opioid", "N01AH01", "Sentetik güçlü opioid analjezik (Mu-Reseptör Agonisti)", "Mu-opioid reseptörlerine yüksek afiniteyle bağlanarak ağrı iletimini inhibe eder.", var10013, (Map)null, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var31), CollectionsKt.listOf("Morfine kıyasla yaklaşık 100 kat daha güçlüdür. Dozlama 'mcg' (mikrogram) cinsindendir, kesinlikle 'mg' ile karıştırılmamalıdır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201065472, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Ultiva");
      Pair[] var35 = new Pair[]{TuplesKt.to("induksiyon", new DoseInfo("0.5 - 1.0 mcg/kg IV yavaş enjeksiyon (1 dakikada)", "Hızlı bolus enjeksiyonları ciddi bradikardi ve hipotansiyona yol açar.")), TuplesKt.to("idame", new DoseInfo("0.05 - 0.25 mcg/kg/dk IV infüzyon", "TIVA veya dengeli anestezi infüzyon protokolü."))};
      var10013 = MapsKt.mapOf(var35);
      var10016 = new PharmacokineticsInfo("30 - 60 saniye", "1 - 2 dakika", "5 - 10 dakika (infüzyon kesildikten sonra)", "Kontekst-duyarlı yarı ömrü 3-4 dakikadır (infüzyon süresinden bağımsızdır)", "Kan ve doku non-spesifik esterazları ile hidroliz");
      String[] var36 = new String[]{"İnfüzyon kapatıldığı an analjezik etki dakikalar içinde tamamen biter. Bu nedenle ameliyat bitmeden önce uzun etkili bir analjezik (morfin, tramadol vb.) yapılmalıdır.", "Hızlı boluslarda şiddetli bradikardi, asistoli ve göğüs duvarı sertliği riski çok yüksektir."};
      var10018 = CollectionsKt.listOf(var36);
      var36 = new String[]{"Hipotansiyon", "Bradikardi", "Bulantı", "Kaşıntı"};
      var10019 = CollectionsKt.listOf(var36);
      var36 = new String[]{"Apne / Solunum arresti", "Asistoli", "Şiddetli kas rijiditesi"};
      var10020 = CollectionsKt.listOf(var36);
      var36 = new String[]{"Kontekst duyarlı yarı ömrü en kısa opiattır. Saatlerce infüzyon verilse dahi kapatıldıktan 5-10 dk sonra hasta uyanır ve solunumu tamamen geri döner.", "Böbrek ve karaciğer yetmezliği olan hastalarda organ eliminasyonuna ihtiyaç duymadığı için son derece güvenlidir."};
      var0[5] = new Drug("remifentanil", "Remifentanil", "Remifentanil", "Remifentanil Hydrochloride", var10008, "opioid", "N01AH06", "Çok kısa etkili sentetik opioid (Mu-Reseptör Agonisti)", "Mu-opioid reseptör agonistidir. Plazmada ve dokularda non-spesifik esterazlar tarafından çok hızlı yıkılır.", var10013, (Map)null, (Map)null, var10016, (List)null, var10018, var10019, var10020, CollectionsKt.listOf(var36), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201075712, (DefaultConstructorMarker)null);
      var36 = new String[]{"Morphine", "Morfin Ampul"};
      var10008 = CollectionsKt.listOf(var36);
      Pair[] var41 = new Pair[]{TuplesKt.to("intraoperatif_analjezi", new DoseInfo("0.05 - 0.15 mg/kg IV yavaş bolus", "Uzun süreli cerrahilerde stabil analjezi sağlamak için kullanılır.")), TuplesKt.to("postoperatif_agri", new DoseInfo("2.0 - 5.0 mg IV yavaş bolus (titre edilerek)", "Ağrı şiddetine göre her 4-6 saatte bir tekrarlanabilir."))};
      var10013 = MapsKt.mapOf(var41);
      var10016 = new PharmacokineticsInfo("5 - 10 dakika (IV)", "20 - 30 dakika (IV)", "3 - 5 saat", "2 - 3 saat", "Karaciğerde glukuronidasyona uğrar. Aktif metaboliti Morfin-6-Glukuronid böbreklerden atılır.");
      String[] var42 = new String[]{"Histamin Salınımı: Morfin belirgin histamin salınımına yol açarak periferik vazodilatasyona, hipotansiyona, yüzde kızarıklığa ve bronkospazma (astım hastalarında riskli) neden olabilir.", "Aktif metabolitleri böbrek yetmezliğinde birikir, bu durumda uzamış solunum depresyonuna yol açabilir. Böbrek yetmezliğinde fentanil tercih edilmelidir."};
      var10018 = CollectionsKt.listOf(var42);
      var42 = new String[]{"Bulantı / Kusma", "Yüzde kızarıklık / Kaşıntı", "Kabızlık (uzun kullanımda)", "Miyozis"};
      var10019 = CollectionsKt.listOf(var42);
      var42 = new String[]{"Şiddetli Solunum Depresyonu", "Bronkospazm (astımlılarda)"};
      var10020 = CollectionsKt.listOf(var42);
      var42 = new String[]{"Histamin salınımını en aza indirmek için IV dozlar çok yavaş (en az 4-5 dakikada) enjekte edilmelidir.", "Epidural ve spinal analjezi uygulamalarında (morfin sızması riskiyle) geç başlayan (24 saate kadar) solunum depresyonu riski yakından izlenmelidir."};
      var0[6] = new Drug("morphine", "Morfin", "Morphine", "Morphine Sulfate", var10008, "opioid", "N02AA01", "Doğal opioid analjezik (Mu-Reseptör Agonisti)", "Merkezi sinir sistemindeki mu-opioid reseptörlerini aktive ederek ağrı algısını değiştirir, spinal ve supraspinal analjezi sağlar.", var10013, (Map)null, (Map)null, var10016, (List)null, var10018, var10019, var10020, CollectionsKt.listOf(var42), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201075712, (DefaultConstructorMarker)null);
      var42 = new String[]{"Lysthenon", "Anectine"};
      var10008 = CollectionsKt.listOf(var42);
      var10013 = MapsKt.mapOf(TuplesKt.to("entubasyon", new DoseInfo("1.0 - 1.5 mg/kg IV bolus", "Hızlı ardışık indüksiyon (RSI) ve acil havayolu yönetiminde altın standarttır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("entubasyon", new DoseInfo("2.0 mg/kg IV veya 4.0 mg/kg IM", "Çocuklarda laringospazm acil tedavisinde IM yol hayat kurtarıcı olabilir.")));
      var10016 = new PharmacokineticsInfo("30 - 60 saniye (IV), 2-3 dakika (IM)", "1 - 2 dakika (IV)", "5 - 10 dakika (IV)", "2 - 4 dakika", "Plazma kolinesterazı (Psödokolinesteraz) tarafından çok hızlı hidroliz edilir");
      var42 = new String[]{"Malign Hipertermi öyküsü veya genetik yatkınlığı", "Hiperkalemi riski yüksek durumlar: Ciddi yanıklar (>24 saat geçmiş), ezilme travmaları (crush), spinal kord hasarı, uzamış immobilizasyon", "Atipik plazma kolinesteraz enzimi varlığı", "Penetran göz yaralanmaları (göz içi basıncını artırır)"};
      var10017 = CollectionsKt.listOf(var42);
      var42 = new String[]{"Potasyum Artışı: Sağlıklı bireylerde plazma potasyumunu yaklaşık 0.5 mEq/L yükseltir. Yanık, travma veya denervasyon hastalarında bu artış masif olabilir ve kardiak arreste yol açabilir.", "Kas Seyirmeleri (Fasikülasyon): İndüksiyon sonrası tüm vücutta ağrılı kas seğirmeleri yapabilir. Küçük doz depolarizan olmayan NMB ile önleme (prekürarizasyon) yapılabilir."};
      var10018 = CollectionsKt.listOf(var42);
      var42 = new String[]{"Fasikülasyon", "Postoperatif kas ağrısı (myalji)", "Geçici bradikardi (özellikle çocuklarda tekrarlayan dozlarda)"};
      var10019 = CollectionsKt.listOf(var42);
      var42 = new String[]{"Malign Hipertermi tetiklenmesi", "Kritik Hiperkalemi / Kardiyak Arrest", "Uzamış apne (psödokolinesteraz eksikliğinde)"};
      var10020 = CollectionsKt.listOf(var42);
      var42 = new String[]{"Pediatrik hastalarda ikinci bolus doz mutlaka atropin ön tedavisi ile yapılmalıdır, aksi halde şiddetli bradikardi veya asistoli gelişebilir.", "Etkisi geri döndürülemez; psödokolinesteraz eksikliğine bağlı uzamış apnede hasta ventilatörde takip edilmelidir."};
      var0[7] = new Drug("succinylcholine", "Süksinilkolin", "Succinylcholine", "Succinylcholine Chloride / Suxamethonium", var10008, "nmb", "M03AB01", "Depolarizan nöromüsküler blokör (Asetilkolin Agonisti)", "Nikotinik asetilkolin reseptörlerine bağlanarak uç plakta sürekli depolarizasyon yaratır, kasları refrakter dönemde bırakarak gevşeme sağlar.", var10013, var10014, (Map)null, var10016, var10017, var10018, var10019, var10020, CollectionsKt.listOf(var42), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201066496, (DefaultConstructorMarker)null);
      var42 = new String[]{"Esmeron", "Curon"};
      var10008 = CollectionsKt.listOf(var42);
      Pair[] var53 = new Pair[]{TuplesKt.to("entubasyon", new DoseInfo("0.6 mg/kg IV", "Klinik gevşeme süresi yaklaşık 30-40 dakikadır.")), TuplesKt.to("hizli_ardisik_induksiyon", new DoseInfo("1.0 - 1.2 mg/kg IV", "60 saniyede mükemmel entübasyon koşulları sağlar. Süresi 60-75 dakikaya uzar.")), TuplesKt.to("idame", new DoseInfo("0.1 - 0.2 mg/kg IV", "TOF takibine göre titre edilmelidir."))};
      var0[8] = new Drug("rocuronium", "Roküronyum", "Rocuronium", "Rocuronium Bromide", var10008, "nmb", "M03AC09", "Depolarizan olmayan nöromüsküler blokör (Asetilkolin Antagonisti)", "Nikotinik asetilkolin reseptörleri için asetilkolin ile yarışarak kompetitif antagonist olarak bağlanır.", MapsKt.mapOf(var53), (Map)null, (Map)null, (PharmacokineticsInfo)null, (List)null, (List)null, (List)null, (List)null, (List)null, (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201325568, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Nimbex");
      var53 = new Pair[]{TuplesKt.to("entubasyon", new DoseInfo("0.15 - 0.2 mg/kg IV bolus", "Entübasyon süresi yaklaşık 2-3 dakikadır.")), TuplesKt.to("idame", new DoseInfo("0.03 mg/kg IV bolus veya 1.0 - 2.0 mcg/kg/dk infüzyon", "Yoğun bakımda uzun süreli infüzyon için idealdir."))};
      var10013 = MapsKt.mapOf(var53);
      var10016 = new PharmacokineticsInfo("2 - 3 dakika", "3 - 5 dakika", "40 - 55 dakika (orta etkili)", "20 - 25 dakika", "Hofmann Eliminasyonu: Plazma pH ve sıcaklığına bağlı spontan kimyasal parçalanma (karaciğer ve böbrekten bağımsızdır)");
      String[] var55 = new String[]{"Hofmann eliminasyonu nedeniyle asidoz ve hipotermi durumlarında ilacın etkisi belirgin şekilde uzar.", "Entübasyon başlangıç hızı roküronyuma göre daha yavaştır; hızlı ardışık indüksiyonlarda (RSI) ilk tercih değildir."};
      var10018 = CollectionsKt.listOf(var55);
      var10019 = CollectionsKt.listOf("Minimal kardiyovasküler etki (minimal histamin salınımı)");
      var10020 = CollectionsKt.listOf("Laudanosin birikimi (çok yüksek doz infüzyonlarda merkezi sinir sistemi uyarılması ve nöbet riski; klinik dozlarda nadirdir)");
      var55 = new String[]{"Organ eliminasyonuna ihtiyaç duymadığı için **Karaciğer ve Böbrek yetmezliği** olan hastalarda en güvenli nöromüsküler blokördür.", "Atrakuryuma kıyasla histamin salınımı yapma riski yok denecek kadar azdır, astım ve hipotansif hastalarda güvenle kullanılabilir."};
      var0[9] = new Drug("cisatracurium", "Sisatrakuryum", "Cisatracurium", "Cisatracurium Besylate", var10008, "nmb", "M03AC11", "Depolarizan olmayan nöromüsküler blokör (Benzilizokinolin grubu)", "Motor uç plaktaki asetilkolin reseptörlerini kompetitif olarak bloke eder. Hofmann eliminasyonu ile vücuttan atılır.", var10013, (Map)null, (Map)null, var10016, (List)null, var10018, var10019, var10020, CollectionsKt.listOf(var55), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201075712, (DefaultConstructorMarker)null);
      var55 = new String[]{"Ephedrine", "Efedrin Ampul"};
      var10008 = CollectionsKt.listOf(var55);
      var10013 = MapsKt.mapOf(TuplesKt.to("bolus_hipotansiyon", new DoseInfo("5.0 - 10.0 mg IV bolus yavaş", "Gerekirse her 5-10 dakikada bir tekrarlanabilir. Genellikle spinal anestezi hipotansiyonunda tercih edilir.")));
      var10016 = new PharmacokineticsInfo("1 - 2 dakika (IV)", "2 - 5 dakika", "10 - 60 dakika", "3 - 6 saat", "Büyük kısmı böbreklerden değişmeden idrarla atılır");
      var55 = new String[]{"Şiddetli koroner arter hastalığı, taşiaritmi varlığı", "Dar açılı glokom"};
      var10017 = CollectionsKt.listOf(var55);
      var55 = new String[]{"Taşifilaksi: Tekrarlayan dozlarda endojen noradrenalin depoları tükeneceği için ilacın etkisi hızla azalır (taşifilaksi gelişir).", "Belirgin taşikardi ve çarpıntı yapabilir. Nabzı yüksek olan hastalarda fenilefrin veya noradrenalin tercih edilmelidir."};
      var10018 = CollectionsKt.listOf(var55);
      var55 = new String[]{"Taşikardi (nabız artışı)", "Çarpıntı", "Hipertansiyon", "Anksiyete"};
      var10019 = CollectionsKt.listOf(var55);
      var55 = new String[]{"Myokard iskemisi tetiklenmesi", "Ciddi aritmiler"};
      var10020 = CollectionsKt.listOf(var55);
      var55 = new String[]{"Spinal/Epidural anestezi sonrası gelişen ve bradikardinin eşlik ettiği hipotansiyon tablolarında mükemmel bir seçenektir; çünkü hem tansiyonu hem nabzı yükseltir.", "Plasental kan akımını koruduğu için obstetrik anestezide (sezaryen operasyonlarında) tarihsel olarak ilk tercihlerden biridir."};
      var0[10] = new Drug("ephedrine", "Efedrin", "Ephedrine", "Ephedrine Sulfate", var10008, "vasopressor", "C01CA24", "Sempatomimetik (Alfa ve Beta Adrenerjik Agonist)", "Hem alfa hem beta reseptörleri uyarır. Esas olarak endojen noradrenalin salınımını tetikleyerek (indirekt etki) sempatik aktiviteyi artırır.", var10013, (Map)null, (Map)null, var10016, var10017, var10018, var10019, var10020, CollectionsKt.listOf(var55), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201067520, (DefaultConstructorMarker)null);
      var55 = new String[]{"Phenylephrine", "Neo-Synephrine"};
      var10008 = CollectionsKt.listOf(var55);
      Pair[] var64 = new Pair[]{TuplesKt.to("bolus_hipotansiyon", new DoseInfo("50 - 100 mcg IV bolus", "Tansiyon durumuna göre her 2-5 dakikada bir tekrarlanabilir.")), TuplesKt.to("infuzyon", new DoseInfo("0.1 - 1.5 mcg/kg/dk IV infüzyon", "Dirençli intraoperatif vazodilatasyon veya nörojenik şok tablolarında."))};
      var10013 = MapsKt.mapOf(var64);
      var10016 = new PharmacokineticsInfo("30 - 60 saniye (IV)", "1 - 2 dakika", "15 - 20 dakika", "2 - 3 saat", "Karaciğerde monoamin oksidaz (MAO) enzimi ile metabolize edilir");
      String[] var65 = new String[]{"Refleks Bradikardi: Periferik vazokonstrüksiyon tansiyonu hızla yükseltirken, baroreseptör uyarımı sonucu kalp hızında belirgin düşüşe (refleks bradikardi) yol açar.", "Kalp debisini (kardiyak çıktı) hafif azaltabilir; bu nedenle kalp yetmezliği veya ciddi sol ventrikül disfonksiyonu olanlarda dikkatli kullanılmalıdır."};
      var10018 = CollectionsKt.listOf(var65);
      var65 = new String[]{"Refleks Bradikardi", "Hipertansiyon", "Baş ağrısı"};
      var10019 = CollectionsKt.listOf(var65);
      var65 = new String[]{"Şiddetli bradikardi / asistoli riski", "Myokard iskemisi"};
      var10020 = CollectionsKt.listOf(var65);
      var65 = new String[]{"Sezaryen operasyonlarında spinal anesteziye bağlı hipotansiyon yönetiminde efedrine kıyasla neonatal asidoz riskini azalttığı için modern kılavuzlarda ilk sıradadır.", "Efedrinden farklı olarak doğrudan sempatik depoları tüketmez, taşifilaksi yapmaz."};
      var0[11] = new Drug("phenylephrine", "Fenilefrin", "Phenylephrine", "Phenylephrine Hydrochloride", var10008, "vasopressor", "C01CA06", "Selektif Alfa-1 Adrenerjik Agonist", "Saf alfa-1 reseptör agonistidir. Periferik vazokonstrüksiyon yaparak sistemik vasküler direnci ve kan basıncını yükseltir.", var10013, (Map)null, (Map)null, var10016, (List)null, var10018, var10019, var10020, CollectionsKt.listOf(var65), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201075712, (DefaultConstructorMarker)null);
      var65 = new String[]{"Levophed", "Noralin"};
      var10008 = CollectionsKt.listOf(var65);
      var10013 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("0.05 - 1.0 mcg/kg/dk IV infüzyon (titre edilerek)", "Santral venöz kateter aracılığıyla uygulanması zorunludur. Septik şok, yoğun bakım ve ameliyathanede majör vazodilatasyon tedavisinde ilk tercihtir.")));
      var10016 = new PharmacokineticsInfo("Hemen (IV)", "1 - 2 dakika", "2 - 5 dakika (infüzyon durdurulduktan sonra)", "2 - 3 dakika", "Hücre içine geri alınım (uptake) ve COMT/MAO enzimleri ile hızlı yıkım");
      var10017 = CollectionsKt.listOf("Ciddi hipovolemi varlığı (öncelikle sıvı açığı kapatılmalıdır)");
      var65 = new String[]{"Ektravazasyon Riski: Periferik damar yolundan kaçarsa şiddetli lokal vazokonstrüksiyona ve doku nekrozuna (gangren) yol açar. Kaçış durumunda Pentalomin lokal enjeksiyonu endikedir.", "Yüksek dozlarda böbrek, mezenter ve periferik organ perfüzyonunu bozabilir."};
      var10018 = CollectionsKt.listOf(var65);
      var65 = new String[]{"Hafif taşikardi veya bradikardi", "Aritmi tetiklenmesi", "Ekstremitelerde soğukluk"};
      var10019 = CollectionsKt.listOf(var65);
      var65 = new String[]{"Lokal doku nekrozu (ekstravazasyon durumunda)", "Masif miyokard iskemisi"};
      var10020 = CollectionsKt.listOf(var65);
      var65 = new String[]{"Modern yoğun bakım ve şok kılavuzlarında **Septik Şok** tablosunda ortalama arter basıncını >65 mmHg düzeyinde tutmak için ilk tercih vazopressördür.", "Efedrin ve fenilefrine yanıt vermeyen dirençli intraoperatif hipotansiyonda erken infüzyon olarak başlanması kritik organ hasarını önlemede etkilidir."};
      var0[12] = new Drug("norepinephrine", "Noradrenalin", "Norepinephrine", "Norepinephrine Bitartrate", var10008, "vasopressor", "C01CA03", "Güçlü Alfa ve Zayıf Beta-1 Agonist", "Güçlü alfa-1 uyarısıyla periferik vazokonstrüksiyon sağlarken, hafif beta-1 uyarısıyla miyokard kontraktilitesini ve kalp debisini destekler.", var10013, (Map)null, (Map)null, var10016, var10017, var10018, var10019, var10020, CollectionsKt.listOf(var65), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201067520, (DefaultConstructorMarker)null);
      var65 = new String[]{"Adrenalin Biofarma", "Epinephrine"};
      var10008 = CollectionsKt.listOf(var65);
      Pair[] var75 = new Pair[]{TuplesKt.to("kardiyak_arrest", new DoseInfo("1 mg IV/IO (her 3-5 dakikada bir)", "Resüsitasyon (CPR) sırasında standart ACLS dozudur.")), TuplesKt.to("anafilaksi", new DoseInfo("0.3 - 0.5 mg IM (uyluk dış yan yüzüne) veya acil IV 10 - 50 mcg (yavaş titre)", "Şiddetli anafilaktik şokta hayat kurtarıcıdır.")), TuplesKt.to("infuzyon", new DoseInfo("0.05 - 0.5 mcg/kg/dk IV infüzyon", "Kardiyojenik şok ve ciddi inotropik yetmezlik durumunda."))};
      var10013 = MapsKt.mapOf(var75);
      var75 = new Pair[]{TuplesKt.to("kardiyak_arrest", new DoseInfo("0.01 mg/kg IV/IO (0.1 mL/kg 1:10.000 solüsyonundan)", "Çocuklarda CPR CPR ve anafilaksi IV standart dozu.")), TuplesKt.to("anafilaksi", new DoseInfo("0.01 mg/kg IM (Maksimum 0.3 mg)", "IM olarak uyluk dış yan kısmına hızla uygulanmalıdır."))};
      var10014 = MapsKt.mapOf(var75);
      var75 = new Pair[]{TuplesKt.to("geriatri", "Aritmi ve koroner iskemi riski çok yüksektir; son derece dikkatli ve titre edilerek kullanılmalıdır."), TuplesKt.to("gebelik", "Gebelik kategorisi C. Uterus perfüzyonunu azaltabilir.")};
      var10015 = MapsKt.mapOf(var75);
      var10016 = new PharmacokineticsInfo("Hemen (IV), 5-10 dk (IM)", "1-2 dk (IV), 20 dk (IM)", "5 - 10 dakika (IV)", "2 - 3 dakika", "Sempatik sinir uçlarına geri alınım ve COMT/MAO ile hızlı metabolizma");
      var10017 = CollectionsKt.listOf("Mutlak kontrendikasyonu yoktur (kardiyak arrest ve şiddetli anafilaksi durumunda)");
      String[] var78 = new String[]{"Ciddi taşikardi, miyokard iskemisi ve ventriküler aritmileri tetikleyebilir.", "Ektravazasyon durumunda lokal doku nekrozu yapar. Santral venöz hat tercih edilmelidir."};
      var10018 = CollectionsKt.listOf(var78);
      var78 = new String[]{"Taşikardi", "Aritmi", "Hipertansiyon", "Anksiyete", "Tremor"};
      var10019 = CollectionsKt.listOf(var78);
      var78 = new String[]{"Ventriküler Fibrilasyon", "Miyokard İskemisi / Akut MI", "İntraserebral Kanama"};
      var0[13] = new Drug("adrenaline", "Adrenalin", "Epinephrine", "Epinephrine Hydrochloride", var10008, "vasopressor", "C01CA24", "Sempatomimetik (Direkt Alfa ve Beta Adrenerjik Agonist)", "Alfa-1 (vazokonstrüksiyon), Beta-1 (pozitif inotrop/kronotrop) ve Beta-2 (bronkodilasyon) reseptörlerini güçlü şekilde uyarır.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var78), CollectionsKt.listOf("Ameliyathanede 1 mg (1 ampul) Adrenalin 100 mL SF içine çekilerek 10 mcg/mL 'Anestezi Adrenalini' solüsyonu hazırlanır; hipotansif krizlerde 10-20 mcg (1-2 mL) boluslar halinde titre edilir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Bridion");
      Pair[] var81 = new Pair[]{TuplesKt.to("rutin_reversal", new DoseInfo("2.0 mg/kg IV bolus", "TOF'ta en az 2 yanıt (orta dereceli blok) alındığında nöromüsküler bloğu sonlandırmak için.")), TuplesKt.to("derin_reversal", new DoseInfo("4.0 mg/kg IV bolus", "Nöromüsküler blok derin ise (post-tetanic count PTC >= 1-2 ve TOF = 0).")), TuplesKt.to("acil_reversal", new DoseInfo("16.0 mg/kg IV bolus", "Roküronyum (1.2 mg/kg) indüksiyonu sonrası entübe edilemeyen / havalandırılamayan (CICO) acil durumlarda derhal kurtarma amacıyla."))};
      var10013 = MapsKt.mapOf(var81);
      var10014 = MapsKt.mapOf(TuplesKt.to("rutin_reversal", new DoseInfo("2.0 mg/kg IV bolus", "2 yaş ve üzeri çocuklarda roküronyuma bağlı orta dereceli bloğun geri çevrilmesinde güvenle kullanılır.")));
      var81 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Şiddetli böbrek yetmezliğinde (eGFR <30 mL/dk) birikim riski nedeniyle önerilmemektedir."), TuplesKt.to("gebelik", "Gebelik kategorisi C. Hormonal kontraseptiflerin etkinliğini azaltabilir; hastaya ek korunma yöntemleri önerilmelidir.")};
      var10015 = MapsKt.mapOf(var81);
      var10016 = new PharmacokineticsInfo("1.5 - 3 dakika", "2 dakika", "Klinik etki kalıcıdır (tekrar bloklanma nadirdir)", "2 saat", "Değişmeden böbrekler yoluyla hızlı renal atılım");
      var10017 = CollectionsKt.listOf("Sugammadeks bileşenlerine karşı bilinen aşırı duyarlılık (anafilaksi riski)");
      String[] var83 = new String[]{"Nadiren şiddetli aşırı duyarlılık reaksiyonları (anafilaksi) bildirilmiştir; uygulama sonrası hasta alerjik reaksiyonlar yönünden izlenmelidir.", "Geçici parsiyel tromboplastin zamanı (aPTT) ve PT artışına yol açabilir."};
      var10018 = CollectionsKt.listOf(var83);
      var83 = new String[]{"Bulantı", "Baş ağrısı", "Uyanma sırasında hafif öksürük"};
      var10019 = CollectionsKt.listOf(var83);
      var83 = new String[]{"Anafilaktik şok", "Ciddi Bradyaritmi / Kalp Durması"};
      var0[14] = new Drug("sugammadex", "Sugammadeks", "Sugammadex", "Sugammadex Sodium", var10008, "reversal", "V03AB35", "Selektif Relaksant Bağlayıcı Ajan (Modifiye Gamma-Siklodekstrin)", "Roküronyum ve veküronyum moleküllerini 1:1 oranında enkapsüle (kapsül içine alma) ederek nöromüsküler kavşaktan uzaklaştırır ve bloğu hızla sonlandırır.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var83), CollectionsKt.listOf("Nöromüsküler bloğun Sugammadeks ile sonlandırılmasından sonraki ilk 24 saat içinde hastaya tekrar kas gevşetici gerekirse, roküronyum/veküronyum yerine benzilizokinolin grubu kas gevşeticiler (sisatrakuryum veya atrakuryum) tercih edilmelidir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var83 = new String[]{"Neostigmin", "Prostigmin"};
      var10008 = CollectionsKt.listOf(var83);
      var10013 = MapsKt.mapOf(TuplesKt.to("reversal", new DoseInfo("0.03 - 0.07 mg/kg IV (Maksimum 5 mg)", "Her zaman bir antikolinerjik (Atropin veya Glikopirolat) ile kombine edilmelidir. TOF'ta en az 2-4 yanıt olmalıdır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("reversal", new DoseInfo("0.02 - 0.05 mg/kg IV", "Atropin (0.02 mg/kg) ile birlikte yavaş IV bolus olarak uygulanmalıdır.")));
      Pair[] var87 = new Pair[]{TuplesKt.to("geriatri", "Eliminasyonu yavaşlayabilir. Antikolinerjik yan etkiler (deliryum, idrar retansiyonu) yönünden dikkatli olunmalıdır."), TuplesKt.to("gebelik", "Gebelik kategorisi C. Plasentayı geçebilir, uterus kontraksiyonlarını uyarabilir.")};
      var10015 = MapsKt.mapOf(var87);
      var10016 = new PharmacokineticsInfo("3 - 10 dakika", "7 - 15 dakika", "1 - 2 saat", "50 - 90 dakika", "Karaciğerde metabolize edilir ve böbrekler yoluyla atılır");
      String[] var88 = new String[]{"Mekanik intestinal veya üriner sistem obstrüksiyonu", "Peritonit varlığı"};
      var10017 = CollectionsKt.listOf(var88);
      var88 = new String[]{"Ciddi muskarinik etkiler: Bradikardi, bronkospazm, aşırı sekresyon, barsak motilitesinde artış. Bu yan etkileri bloke etmek için mutlaka Atropin eş zamanlı veya öncesinde verilmelidir.", "Derin nöromüsküler blokta (TOF = 0) uygulanırsa bloğu daha da derinleştirebilir (reversal tavan etkisi)."};
      var10018 = CollectionsKt.listOf(var88);
      var88 = new String[]{"Tükürük salgısı artışı (salivasyon)", "Terleme", "Miyozis", "Bulantı/Kusma"};
      var10019 = CollectionsKt.listOf(var88);
      var88 = new String[]{"Ciddi Bradikardi / Asistoli", "Bronkospazm", "Kardiyak Aritmiler"};
      var0[15] = new Drug("neostigmine", "Neostigmin", "Neostigmine", "Neostigmine Methylsulfate", var10008, "reversal", "N07AA01", "Reversibl Asetilkolinesteraz İnhibitörü", "Asetilkolini yıkan asetilkolinesteraz enzimini inhibe ederek nöromüsküler kavşakta asetilkolin miktarını artırır ve non-depolarizan blokörlerin etkisini yarışmalı olarak geri çevirir.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var88), CollectionsKt.listOf("Neostigmin (0.05 mg/kg) uygularken, eşlik edecek bradikardiyi önlemek için her 1 mg Neostigmin başına 0.4-0.5 mg Atropin aynı enjektörde karıştırılarak yavaşça IV enjekte edilir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Atropin Sülfat");
      Pair[] var92 = new Pair[]{TuplesKt.to("bradikardi", new DoseInfo("0.5 - 1.0 mg IV bolus (her 3-5 dk, maksimum 3 mg)", "Klinik bradikardi ve vagal reflekslerin önlenmesi/tedavisinde.")), TuplesKt.to("reversal_eslik", new DoseInfo("0.015 - 0.02 mg/kg IV", "Neostigmin ile birlikte muskarinik yan etkileri önlemek için."))};
      var10013 = MapsKt.mapOf(var92);
      var10014 = MapsKt.mapOf(TuplesKt.to("bradikardi", new DoseInfo("0.02 mg/kg IV (Minimum 0.1 mg, maksimum 0.5 mg tek doz)", "Paradoksikal bradikardiye yol açmamak için minimum 0.1 mg dozun altında verilmemelidir.")));
      var92 = new Pair[]{TuplesKt.to("geriatri", "Santral antikolinerjik sendrom (konfüzyon, deliryum) riski yaşlılarda oldukça yüksektir."), TuplesKt.to("koroner_hastalik", "Kalp hızını aşırı artırarak miyokardın oksijen ihtiyacını artırır ve iskemiyi tetikleyebilir.")};
      var10015 = MapsKt.mapOf(var92);
      var10016 = new PharmacokineticsInfo("30 saniye - 1 dakika (IV)", "2 - 4 dakika", "1 - 2 saat", "2 - 4 saat", "Karaciğerde enzimatik hidroliz ve değişmeden idrarla atılım");
      String[] var94 = new String[]{"Dar açılı glokom", "Mekanik prostat obstrüksiyonu (üriner retansiyon riski)", "Taşiaritmiler"};
      var10017 = CollectionsKt.listOf(var94);
      var94 = new String[]{"Santral Sinir Sistemine geçebilir (Kan-beyin bariyerini aşar) ve konfüzyon, deliryum, halüsinasyon yapabilir (premedikasyonda glikopirolat bu açıdan daha üstündür).", "Sekresyonları kurutarak balgam koyulaşmasına (mukus tıkacı) yol açabilir."};
      var10018 = CollectionsKt.listOf(var94);
      var94 = new String[]{"Ağız kuruluğu", "Göz bebeklerinde büyüme (midriyazis)", "Taşikardi", "Kabızlık"};
      var10019 = CollectionsKt.listOf(var94);
      var94 = new String[]{"Santral Antikolinerjik Sendrom", "Akut Üriner Retansiyon", "Dar Açılı Glokom Atağı"};
      var0[16] = new Drug("atropine", "Atropin", "Atropine", "Atropine Sulfate", var10008, "anticholinergic", "A03BA01", "Antimuskarinik (Antikolinerjik)", "Parasempatik sinir uçlarındaki postgangliyonik muskarinik reseptörleri yarışmalı olarak bloke eder, vagal tonusu baskılayarak kalp hızını ve sekresyonları azaltır.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var94), CollectionsKt.listOf("0.1 mg'dan daha düşük dozlarda IV uygulandığında, santral vagal çekirdek uyarımı nedeniyle paradoksikal (geçici) bradikardiye yol açabilir; bu nedenle her zaman hızlı ve yeterli dozda enjekte edilmelidir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Robinul");
      Pair[] var98 = new Pair[]{TuplesKt.to("sekresyon_kontrol", new DoseInfo("0.1 - 0.2 mg IV veya IM", "Premedikasyonda sekresyonları kurutmak amacıyla.")), TuplesKt.to("reversal_eslik", new DoseInfo("0.2 mg IV (her 1 mg Neostigmin için)", "Neostigminin muskarinik etkilerini antagonize etmek için en ideal ajandır."))};
      var10013 = MapsKt.mapOf(var98);
      var10014 = MapsKt.mapOf(TuplesKt.to("reversal_eslik", new DoseInfo("0.01 mg/kg IV", "Neostigmin ile kombine edilerek çocuklarda güvenle uygulanır.")));
      var10015 = MapsKt.mapOf(TuplesKt.to("geriatri", "Kan-beyin bariyerini geçmediği için yaşlılarda atropine kıyasla konfüzyon/deliryum riski son derece düşüktür."));
      var10016 = new PharmacokineticsInfo("1 - 2 dakika (IV)", "5 - 10 dakika", "2 - 4 saat (kardiyak), 7 saate kadar (anti-sekretuvar)", "0.8 - 1.2 saat", "Büyük oranda değişmeden idrar ve safra ile atılım");
      String[] var99 = new String[]{"Dar açılı glokom", "Şiddetli ülseratif kolit, toksik megakolon"};
      var10017 = CollectionsKt.listOf(var99);
      var99 = new String[]{"Atropine göre daha az taşikardi yapar, ancak yüksek dozlarda taşiaritmi riski yine de mevcuttur.", "Terlemeyi azaltarak vücut sıcaklığının artmasına (hipertermi) yol açabilir."};
      var10018 = CollectionsKt.listOf(var99);
      var99 = new String[]{"Ağız kuruluğu", "Görme bulanıklığı", "Üriner retansiyon riski", "Konstipasyon"};
      var10019 = CollectionsKt.listOf(var99);
      var99 = new String[]{"Şiddetli taşiaritmiler", "Isı çarpanı/Hipertermi"};
      var0[17] = new Drug("glycopyrrolate", "Glikopirolat", "Glycopyrrolate", "Glycopyrronium Bromide", var10008, "anticholinergic", "A03AB02", "Kuaterner Amonyum Antimuskarinik", "Muskarinik reseptörleri seçici olarak bloke ederek tükürük, bronşiyal ve gastrik sekresyonları azaltır, kalp hızını dengeler.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var99), CollectionsKt.listOf("Kuaterner amonyum yapısı nedeniyle yüklü bir moleküldür. Bu kimyasal özelliği sayesinde kan-beyin bariyerini ve plasentayı geçemez. Dolayısıyla santral yan etki ve fetal depresyon yapmaz."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Precedex");
      Pair[] var103 = new Pair[]{TuplesKt.to("yukleme", new DoseInfo("0.5 - 1.0 mcg/kg IV (10 dakika içinde)", "Hızlı bolus enjeksiyonlardan kaçınılmalıdır, geçici hipertansiyon ve bradikardi yapabilir.")), TuplesKt.to("idame", new DoseInfo("0.2 - 0.7 mcg/kg/saat IV infüzyon", "Yoğun bakımda veya uyanık entübasyon sırasında kooperasyonun korunduğu sedasyon sağlamak için."))};
      var10013 = MapsKt.mapOf(var103);
      var10014 = MapsKt.mapOf(TuplesKt.to("idame", new DoseInfo("0.2 - 0.6 mcg/kg/saat IV infüzyon", "Çocuklarda yoğun bakım sedasyonunda ve ajitasyon yönetiminde kullanılır.")));
      var103 = new Pair[]{TuplesKt.to("geriatri", "Hipotansiyon ve bradikardi riski artmıştır; yükleme dozu atlanabilir veya azaltılabilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde klirens belirgin azalır, infüzyon dozları düşürülmelidir.")};
      var10015 = MapsKt.mapOf(var103);
      var10016 = new PharmacokineticsInfo("5 - 10 dakika", "15 - 30 dakika", "1 - 2 saat (infüzyon kesildikten sonra)", "2 saat", "Karaciğerde glukuronidasyon ve CYP2D6 ile metabolizma, idrarla atılım");
      String[] var105 = new String[]{"İleri derece kalp blokları (2. veya 3. derece AV blok)", "Ciddi kontrolsüz hipotansiyon veya bradikardi"};
      var10017 = CollectionsKt.listOf(var105);
      var105 = new String[]{"Sempatolitik etkisi nedeniyle belirgin bradikardi, sinüs durması ve hipotansiyona yol açabilir.", "Yükleme dozu çok hızlı verilirse, periferik alfa-2B reseptör uyarımı sonucu geçici hipertansiyon gelişebilir."};
      var10018 = CollectionsKt.listOf(var105);
      var105 = new String[]{"Bradikardi", "Hipotansiyon", "Ağız kuruluğu", "Bulantı"};
      var10019 = CollectionsKt.listOf(var105);
      var105 = new String[]{"Sinüs durması / Asistoli", "Ciddi Rebound Hipertansiyon (ani kesilmede)"};
      var0[18] = new Drug("dexmedetomidine", "Deksmedetomidin", "Dexmedetomidine", "Dexmedetomidine Hydrochloride", var10008, "sedative", "N05CM18", "Selektif Alfa-2 Adrenerjik Reseptör Agonisti", "Locus coeruleus'taki presinaptik alfa-2 reseptörlerini uyararak noradrenalin salınımını inhibe eder; uykuyu andıran (doğal uyku) sedasyon ve analjezi sağlar.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var105), CollectionsKt.listOf("Hastayı solunum depresyonuna sokmadan kooperasyon kurabilen (uyandırılabilen) benzersiz bir 'kooperatif sedasyon' sağlar. Bu özelliğiyle uyanık kraniyotomilerde ve zor havayolunda uyanık fiberoptik entübasyonda altın standarttır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var105 = new String[]{"Sevorane", "Sofrane"};
      var10008 = CollectionsKt.listOf(var105);
      Pair[] var110 = new Pair[]{TuplesKt.to("mac", new DoseInfo("%1.8 - 2.0 (O2/N2O karışımında)", "Minimum Alveoler Konsantrasyon (MAC) yaşla birlikte azalır.")), TuplesKt.to("induksiyon", new DoseInfo("%4.0 - 8.0 (yüksek akışlı oksijen ile)", "Erişkinlerde nadir, pediatride maske indüksiyonu için standarttır."))};
      var10013 = MapsKt.mapOf(var110);
      var10014 = MapsKt.mapOf(TuplesKt.to("induksiyon", new DoseInfo("%4.0 - 8.0 (yavaşça artırılarak maskeyle)", "Havayolu iritasyonu yapmadığı için çocuklarda inhalasyon indüksiyonunun temel ilacıdır.")));
      var110 = new Pair[]{TuplesKt.to("malign_hipertermi", "\ud83d\udea8 KESİNLİKLE KONTRENDİKEDİR! Malign Hipertermiyi tetikleyen güçlü bir ajandır."), TuplesKt.to("geriatri", "MAC değeri belirgin olarak düşer, doz titre edilmelidir.")};
      var10015 = MapsKt.mapOf(var110);
      var10016 = new PharmacokineticsInfo("1 - 2 dakika (hızlı indüksiyon)", "Alveoler konsantrasyona bağlı", "Gaz kesildikten sonra 5-10 dk içinde hızlı uyanma", "Çok düşük kan/gaz çözünürlük katsayısı (0.65-0.69)", "Neredeyse tamamen akciğerlerden değişmeden atılım, %2-5 oranında karaciğerde yıkım");
      String[] var112 = new String[]{"Malign hipertermi öyküsü veya genetik yatkınlığı", "Sevoflurana karşı bilinen aşırı duyarlılık"};
      var10017 = CollectionsKt.listOf(var112);
      var112 = new String[]{"Malign Hipertermi (MH) tetikleme riski en kritik uyarısıdır.", "Karbondioksit absorbanları (soda-lime) ile reaksiyona girerek böbrek hasarı yapabilen 'Compound A' (Bileşik A) üretebilir; bu riski önlemek için taze gaz akışı minimum 1-2 L/dk altında tutulmamalıdır."};
      var10018 = CollectionsKt.listOf(var112);
      var112 = new String[]{"Bulantı/Kusma", "Öksürük/Sekresyon artışı", "Postoperatif ajitasyon (özellikle çocuklarda)"};
      var10019 = CollectionsKt.listOf(var112);
      var112 = new String[]{"Malign Hipertermi", "Şiddetli Hepatotoksisite (Nadir, Halotan hepatitine benzer)", "Kardiyak Aritmi"};
      var0[19] = new Drug("sevoflurane", "Sevofluran", "Sevoflurane", "Sevoflurane", var10008, "inhalational", "N01AB08", "Halojenli Eter (Florlu İnhaler Anestezik)", "MSS'de GABA-A ve glisin reseptörlerini potansiyalize ederken, NMDA ve nikotinik asetilkolin reseptörlerini bloke ederek anestezi, amnezi ve immobilizasyon sağlar.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var112), CollectionsKt.listOf("Keskin, irite edici bir kokusu olmadığı ve bronkodilatör etki gösterdiği için çocuklarda maske indüksiyonu ile damar yolu açılmadan anestezi başlatılmasında en popüler inhaler anesteziktir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var112 = new String[]{"Aritmal", "Jetokain"};
      var10008 = CollectionsKt.listOf(var112);
      Pair[] var117 = new Pair[]{TuplesKt.to("lokal_infiltrasyon", new DoseInfo("Maks 4.5 mg/kg (adrenalinsiz), Maks 7.0 mg/kg (adrenalinli)", "Dozaj aşılmamalı, LAST riski göz önünde bulundurulmalıdır.")), TuplesKt.to("iv_bolus", new DoseInfo("1.0 - 1.5 mg/kg IV", "Entübasyona bağlı sempatik yanıtı ve propofol enjeksiyon ağrısını azaltmak için indüksiyonda."))};
      var10013 = MapsKt.mapOf(var117);
      var10014 = MapsKt.mapOf(TuplesKt.to("lokal_infiltrasyon", new DoseInfo("3.0 - 4.0 mg/kg (adrenalinsiz)", "Çocuklarda toksisite sınırı daha düşüktür, dikkatle hesaplanmalıdır.")));
      var117 = new Pair[]{TuplesKt.to("karaciger_yetmezligi", "Amid grubu olduğu için karaciğerde metabolize edilir; yetmezlikte toksisite riski yüksektir."), TuplesKt.to("geriatri", "LAST duyarlılığı artmıştır; doz %20-30 oranında düşürülmelidir.")};
      var10015 = MapsKt.mapOf(var117);
      var10016 = new PharmacokineticsInfo("2 - 5 dakika (lokal), 1-2 dk (IV)", "15 - 30 dakika (lokal)", "30 - 120 dakika (adrenalin ile 3 saate kadar uzar)", "1.5 - 2 saat", "Karaciğerde CYP3A4 ile aktif metabolitlerine (MEGX) metabolize edilir, renal atılım");
      String[] var119 = new String[]{"Amid grubu lokal anesteziklere bilinen aşırı duyarlılık", "Ciddi kalp blokları (özellikle 2. ve 3. derece AV bloklar)"};
      var10017 = CollectionsKt.listOf(var119);
      var119 = new String[]{"Lokal Anestezik Sistemik Toksisitesi (LAST): Yanlışlıkla IV enjeksiyonda veya aşırı dozda nöbetler, koma ve kardiyovasküler kollaps gelişebilir.", "Epinefrinli solüsyonlar uç ekstremitelere (parmak, burun ucu, penis, kulak memesi) nekroz riski nedeniyle enjekte edilmemelidir."};
      var10018 = CollectionsKt.listOf(var119);
      var119 = new String[]{"Uyuşukluk", "Metalik tat", "Ağız çevresinde karıncalanma (parestezi)", "Kulak çınlaması"};
      var10019 = CollectionsKt.listOf(var119);
      var119 = new String[]{"Nöbet (LAST bulgusu)", "Kardiyak Aritmi / Asistoli", "Şiddetli Anafilaksi"};
      var0[20] = new Drug("lidocaine", "Lidokain", "Lidocaine", "Lidocaine Hydrochloride", var10008, "local_anesthetic", "N01BB02", "Amid Grubu Lokal Anestezik ve Sınıf 1B Antihiperaktif", "Voltaj kapılı sodyum kanallarını bloke ederek sinir liflerinde aksiyon potansiyeli iletimini engeller, duyusal ve motor blok sağlar.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var119), CollectionsKt.listOf("Lidokain, LAST şüphesinde hızlıca tanınması gereken sss bulgularına (perioral uyuşukluk, kulak çınlaması, metalik tat, çift görme) yol açar. Bu bulgular geliştiğinde enjeksiyon derhal durdurulmalıdır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var119 = new String[]{"Marcaine", "Bupivacaine"};
      var10008 = CollectionsKt.listOf(var119);
      Pair[] var124 = new Pair[]{TuplesKt.to("spinal_anestezi", new DoseInfo("5.0 - 15.0 mg (Hyperbaric/Marcaine heavy)", "Sezaryen veya alt ekstremite ameliyatları için spinal aralığa uygulanır.")), TuplesKt.to("epidural", new DoseInfo("%0.125 - 0.25 infüzyon veya bolus", "Ağrısız doğum veya postoperatif analjezi için.")), TuplesKt.to("lokal_infiltrasyon", new DoseInfo("Maks 2.0 mg/kg (adrenalinsiz), Maks 2.5 mg/kg (adrenalinli)", "Kesinlikle damar içine enjekte edilmemelidir!"))};
      var10013 = MapsKt.mapOf(var124);
      var124 = new Pair[]{TuplesKt.to("gebelik", "Gebelerde kardiak toksisiteye duyarlılık artmıştır. Dozaj spinalde %20-30 oranında azaltılmalıdır."), TuplesKt.to("geriatri", "LAST riski yüksektir, spinal ve epidural dozları azaltılmalıdır.")};
      var10015 = MapsKt.mapOf(var124);
      var10016 = new PharmacokineticsInfo("5 - 10 dakika (spinal), 15-20 dk (epidural)", "30 - 45 dakika", "3 - 6 saat (epidural), 2-3 saat (spinal)", "2.7 saat", "Karaciğerde metabolize edilir, değişmeyen kısmı idrarla atılır");
      String[] var126 = new String[]{"Şiddetli sistemik enfeksiyon veya spinal girişim yerinde lokal enfeksiyon", "Ciddi koagülopati veya aktif antikoagülan kullanımı (neuraxial bloklar için)"};
      var10017 = CollectionsKt.listOf(var126);
      var126 = new String[]{"\ud83d\udea8 YÜKSEK KARDİYOTOKSİSİTE: Yanlışlıkla damar içi enjeksiyonunda gelişen kardiyak arrest dirençlidir ve standart resüsitasyon önlemlerine yanıt vermez. Lipid Emülsiyon tedavisi derhal başlanmalıdır.", "Damar dışı enjeksiyon sırasında aspire edilerek kan gelmediği kesinleştirilmelidir."};
      var10018 = CollectionsKt.listOf(var126);
      var126 = new String[]{"Hipotansiyon (neuraxial blok sonrası)", "Bradikardi", "İdrar retansiyonu"};
      var10019 = CollectionsKt.listOf(var126);
      var126 = new String[]{"Kardiyovasküler Kollaps / Dirençli VF / Asistoli (LAST)", "Nöbet", "Yüksek / Total Spinal"};
      var0[21] = new Drug("bupivacaine", "Bupivakain", "Bupivacaine", "Bupivacaine Hydrochloride", var10008, "local_anesthetic", "N01BB01", "Uzun Etkili Amid Grubu Lokal Anestezik", "Sodyum kanallarını güçlü ve uzun süreli bloke eder. Kalpteki sodyum kanallarından yavaş ayrıldığı için kardiyotoksik potansiyeli çok yüksektir.", var10013, (Map)null, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var126), CollectionsKt.listOf("Bupivakain, kalbin iletim sisteminde yer alan sodyum kanallarına çok sıkı bağlanır ve diyastol sırasında kanaldan çok yavaş ayrılır ('slow-in, slow-out'). Bu durum, toksik dozlarda geri dönüşümsüz ventriküler aritmilere ve ölüme yol açan kardiak arrestin ana nedenidir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201065472, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Naropin");
      Pair[] var130 = new Pair[]{TuplesKt.to("epidural", new DoseInfo("%0.2 - 0.75 infüzyon veya bolus", "Cerrahi anestezi için %0.75, analjezi için %0.2 tercih edilir.")), TuplesKt.to("periferik_blok", new DoseInfo("10 - 40 mL %0.5 veya %0.75 solüsyon", "Pleksus ve periferik sinir blokajı için.")), TuplesKt.to("lokal_infiltrasyon", new DoseInfo("Maks 3.0 mg/kg", "Yumuşak doku infiltrasyonu ve yara yeri ağrısı için."))};
      var10013 = MapsKt.mapOf(var130);
      var10015 = MapsKt.mapOf(TuplesKt.to("geriatri", "LAST riski nedeniyle dozlar dikkatle titre edilmelidir."));
      var10016 = new PharmacokineticsInfo("10 - 20 dakika", "30 - 45 dakika", "3 - 8 saat (blok tipine bağlı)", "4.2 saat", "Karaciğerde CYP1A2 ile metabolizma, idrarla atılım");
      String[] var131 = new String[]{"Amid grubu lokal anesteziklere karşı bilinen aşırı duyarlılık", "İntravenöz rejyonel anestezi (IVRA / Bier Bloğu) uygulamalarında kullanılması kontrendikedir."};
      var10017 = CollectionsKt.listOf(var131);
      var131 = new String[]{"Bupivakainden daha güvenli olsa da, yüksek dozlarda veya yanlışlıkla IV enjeksiyonda yine de ciddi nöbet ve kardiak toksisiteye yol açabilir.", "Duyusal ve motor blok ayrımı (sensory-motor dissociation) belirgindir; motor bloğu bupivakaine göre daha hafiftir."};
      var10018 = CollectionsKt.listOf(var131);
      var131 = new String[]{"Hipotansiyon", "Bulantı", "Baş ağrısı", "Parestazi"};
      var10019 = CollectionsKt.listOf(var131);
      var131 = new String[]{"Nöbet (LAST)", "Aritmi / Kardiyak arrest (LAST)"};
      var0[22] = new Drug("ropivacaine", "Ropivakain", "Ropivacaine", "Ropivacaine Hydrochloride", var10008, "local_anesthetic", "N01BB09", "Uzun Etkili Amid Grubu Lokal Anestezik (Saf S-Enantiyomer)", "Voltaj kapılı sodyum kanallarını bloke ederek sinir iletimini engeller. Saf S-enantiyomer yapısı sayesinde bupivakaine göre kardiyotoksik potansiyeli belirgin olarak daha düşüktür.", var10013, (Map)null, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var131), CollectionsKt.listOf("Ropivakain, bupivakaine göre daha az motor blok yaptığı için 'yürüyen epidural' (walking epidural) olarak adlandırılan ağrısız doğum anestezi protokollerinde ve postoperatif erken mobilizasyon istenen hastalarda ilk tercihtir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201065472, (DefaultConstructorMarker)null);
      drugsList = CollectionsKt.listOf(var0);
      $stable = 8;
   }
}
