package com.anesthesiaclinic.anesthesiabriefs.data.repository;

import androidx.compose.runtime.internal.StabilityInferred;
import com.anesthesiaclinic.anesthesiabriefs.data.model.DoseInfo;
import com.anesthesiaclinic.anesthesiabriefs.data.model.Drug;
import com.anesthesiaclinic.anesthesiabriefs.data.model.PharmacokineticsInfo;
import java.util.List;
import java.util.Map;
import kotlin.Metadata;
import kotlin.Pair;
import kotlin.TuplesKt;
import kotlin.collections.CollectionsKt;
import kotlin.collections.MapsKt;
import kotlin.jvm.internal.DefaultConstructorMarker;
import org.jetbrains.annotations.NotNull;

@Metadata(
   mv = {2, 2, 0},
   k = 1,
   xi = 48,
   d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003R\u0017\u0010\u0004\u001a\b\u0012\u0004\u0012\u00020\u00060\u0005¢\u0006\b\n\u0000\u001a\u0004\b\u0007\u0010\b¨\u0006\t"},
   d2 = {"Lcom/anesthesiaclinic/anesthesiabriefs/data/repository/SeedDataDrugsPart2;", "", "<init>", "()V", "drugsList", "", "Lcom/anesthesiaclinic/anesthesiabriefs/data/model/Drug;", "getDrugsList", "()Ljava/util/List;", "app_debug"}
)
@StabilityInferred(
   parameters = 0
)
public final class SeedDataDrugsPart2 {
   @NotNull
   public static final SeedDataDrugsPart2 INSTANCE = new SeedDataDrugsPart2();
   @NotNull
   private static final List drugsList;
   public static final int $stable;

   private SeedDataDrugsPart2() {
   }

   @NotNull
   public final List getDrugsList() {
      return drugsList;
   }

   static {
      Drug[] var0 = new Drug[23];
      String[] var1 = new String[]{"Dantrium", "Ryanodex"};
      List var10008 = CollectionsKt.listOf(var1);
      Map var10013 = MapsKt.mapOf(TuplesKt.to("mh_kriz", new DoseInfo("2.5 mg/kg IV bolus (hızla)", "Semptomlar kontrol altına alınana veya maksimum 10 mg/kg doza ulaşılana kadar 5-10 dakikada bir tekrarlanabilir.")));
      Map var10014 = MapsKt.mapOf(TuplesKt.to("mh_kriz", new DoseInfo("2.5 mg/kg IV bolus (hızla)", "Çocuklarda doz yetişkinlerle aynıdır, kilo başına hesaplanarak derhal uygulanmalıdır.")));
      Map var10015 = MapsKt.mapOf(TuplesKt.to("gebelik", "Gebelik kategorisi C. Endike olduğunda hayat kurtarıcıdır, tereddüt edilmeden verilmelidir."));
      PharmacokineticsInfo var10016 = new PharmacokineticsInfo("2 - 5 dakika (IV)", "Enjeksiyon sonu", "4 - 8 saat", "12 saat", "Karaciğerde metabolize edilir, renal ve fekal atılım");
      List var10017 = CollectionsKt.listOf("Akut acil Malign Hipertermi krizinde mutlak bir kontrendikasyonu yoktur.");
      var1 = new String[]{"Flakon hazırlama zordur: Klasik dantrolen flakonları (Dantrium) 20 mg etken madde içerir ve her flakon 60 mL steril distile su (SF değil!) ile dakikalarca çalkalanarak sulandırılmalıdır. 80 kg bir hasta için en az 10 flakon ve 600 mL su gerekir.", "Ryanodex formu ise çok daha hızlı çözünür (tek flakonda 250 mg, 5 mL su ile çözünür)."};
      List var10018 = CollectionsKt.listOf(var1);
      var1 = new String[]{"Kas güçsüzlüğü", "Hafif sedasyon", "Enjeksiyon yerinde irritasyon"};
      List var10019 = CollectionsKt.listOf(var1);
      var1 = new String[]{"Solunum yetmezliği (kas güçsüzlüğüne bağlı)", "Hepatoselüler hasar (kronik kullanımda)"};
      var0[0] = new Drug("dantrolene", "Dantrolen", "Dantrolene", "Dantrolene Sodium", var10008, "crisis", "M03CA01", "Direkt Etkili İskelet Kası Gevşetici (Ryanodin Reseptör Antagonisti)", "İskelet kası sarkoplazmik retikulumundaki ryanodin reseptörlerini (RyR1) bloke ederek kalsiyum salınımını engeller, kasılmayı ve hipermetabolik süreci durdurur.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var1), CollectionsKt.listOf("Malign Hipertermi (MH) atağı şüphesinde anestezi cihazında bulunan inhaler gazlar kapatılmalı, devre ve soda-lime değiştirilmeli, %100 O2 ile hiperventilasyona başlanmalı ve derhal Dantrolen hazırlanarak uygulanmalıdır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var1 = new String[]{"Intralipid 20%", "Lipofundin"};
      var10008 = CollectionsKt.listOf(var1);
      Pair[] var6 = new Pair[]{TuplesKt.to("last_bolus", new DoseInfo("1.5 mL/kg IV bolus (1 dakikada)", "Kardiyotoksisite belirtileri varsa bolus uygulanır. 3-5 dk arayla 2 kez tekrarlanabilir (Maksimum 3 bolus).")), TuplesKt.to("last_infuzyon", new DoseInfo("0.25 mL/kg/dk IV infüzyon", "Hemodinamik stabilite sağlanana kadar sürekli infüzyon olarak başlanır. Dirençli durumlarda hız 0.5 mL/kg/dk'ya çıkarılabilir."))};
      var10013 = MapsKt.mapOf(var6);
      var10014 = MapsKt.mapOf(TuplesKt.to("last_rescue", new DoseInfo("1.5 mL/kg IV bolus, ardından 0.25 mL/kg/dk infüzyon", "Çocuklarda lokal anestezi toksisitesi (LAST) durumunda standart hayat kurtarıcı dozdur.")));
      var10015 = MapsKt.mapOf(TuplesKt.to("mh_kriz", "Malign hipertermide kullanımı yoktur, karıştırılmamalıdır."));
      var10016 = new PharmacokineticsInfo("Hemen", "Enjeksiyon sonu", "Dolaşımdan klirensi hızlıdır", "30 - 45 dakika", "Retiküloendotelyal sistem ve kas/adipoz doku tarafından lipoprotein lipaz ile yıkım");
      String[] var7 = new String[]{"Lokal anestezik sistemik toksisitesi durumunda mutlak kontrendikasyonu yoktur.", "Ağır yumurta/soya alerjisi rölatif kontrendikedir."};
      var10017 = CollectionsKt.listOf(var7);
      var7 = new String[]{"LAST dışı durumlarda aşırı dozda uygulanırsa hipertrigliseridemi, pankreatit ve pulmoner perfüzyon bozukluğu yapabilir.", "Maksimum toplam güvenli günlük doz 12 mL/kg'ı aşmamalıdır."};
      var10018 = CollectionsKt.listOf(var7);
      var7 = new String[]{"Hipertrigliseridemi", "Bulantı", "Hafif ateş artışı"};
      var10019 = CollectionsKt.listOf(var7);
      var7 = new String[]{"Pankreatit", "Lipid yüklenme sendromu", "Akut Akciğer Hasarı"};
      var0[1] = new Drug("lipid_emulsion", "%20 Lipid Emülsiyonu", "20% Lipid Emulsion", "Intravenous Lipid Emulsion (ILE)", var10008, "crisis", "B05XX", "LAST Resüsitasyon antidotu ve Nutrisyonel Lipid Solüsyonu", "1. 'Lipid Sink' (Lipid Lavabosu) etkisiyle kandaki lipofilik lokal anestezikleri içine çekerek kalpten uzaklaştırır. 2. Miyokard hücrelerine doğrudan serbest yağ asidi sağlayarak ATP üretimini destekler.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var7), CollectionsKt.listOf("Lokal anesteziye bağlı gelişen dirençli kardiak arrest resüsitasyonunda, klasik ACLS protokolünden farklı olarak Adrenalin dozları <1 mcg/kg (örn. 10-100 mcg) olarak düşük tutulmalı, vazopressin verilmemelidir. Çünkü yüksek adrenalin lipid sink etkisini zayıflatabilir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var7 = new String[]{"Zofran", "Zofer"};
      var10008 = CollectionsKt.listOf(var7);
      Pair[] var12 = new Pair[]{TuplesKt.to("ponv_profilaksi", new DoseInfo("4 mg IV (cerrahi bitiminden 30 dk önce)", "Postoperatif Bulantı ve Kusmanın (PONV) önlenmesinde temel seçenektir.")), TuplesKt.to("ponv_tedavi", new DoseInfo("4 mg IV bolus (yavaş)", "Profilaksi almamış ve bulantısı başlamış hastalarda tedavi edici olarak."))};
      var10013 = MapsKt.mapOf(var12);
      var10014 = MapsKt.mapOf(TuplesKt.to("ponv_profilaksi", new DoseInfo("0.1 mg/kg IV (Maksimum 4 mg)", "1 ayın üzerindeki çocuklarda cerrahi bitiminde uygulanabilir.")));
      var12 = new Pair[]{TuplesKt.to("qt_uzamasi", "QT aralığını uzatabileceği için konjenital uzun QT sendromu olanlarda kontrendikedir."), TuplesKt.to("karaciger_yetmezligi", "Şiddetli karaciğer yetmezliğinde günlük maksimum doz 8 mg ile sınırlandırılmalıdır.")};
      var10015 = MapsKt.mapOf(var12);
      var10016 = new PharmacokineticsInfo("15 - 30 dakika (IV)", "30 dakika", "4 - 8 saat", "3 - 5 saat", "Karaciğerde CYP2D6, CYP3A4 ve CYP1A2 ile metabolize edilir, renal atılım");
      String[] var14 = new String[]{"Ondansetrona karşı bilinen aşırı duyarlılık", "Apomorfin ile eş zamanlı kullanımı (şiddetli hipotansiyon riski nedeniyle)"};
      var10017 = CollectionsKt.listOf(var14);
      var14 = new String[]{"Elektrokardiyogramda doza bağımlı QT uzaması ve Torsades de Pointes riskine yol açabilir; aritmi riski olanlarda yakın EKG takibi yapılmalıdır.", "Serotonerjik ilaçlarla (SSRİ, SNRI) birlikte kullanıldığında Serotonin Sendromu riski mevcuttur."};
      var10018 = CollectionsKt.listOf(var14);
      var14 = new String[]{"Baş ağrısı", "Konstipasyon", "Sıcaklık hissi/Flushing", "Hafif karaciğer transaminaz artışı"};
      var10019 = CollectionsKt.listOf(var14);
      var14 = new String[]{"QT Uzaması / Torsades de Pointes", "Serotonin Sendromu", "Anafilaksi"};
      var0[2] = new Drug("ondansetron", "Ondansetron", "Ondansetron", "Ondansetron Hydrochloride", var10008, "antiemetic", "A04AA01", "Selektif 5-HT3 (Serotonin) Reseptör Antagonisti", "Kemoreseptör tetikleme zonunda (CTZ) ve periferik vagal sinir uçlarındaki 5-HT3 reseptörlerini bloke ederek bulantı ve kusma refleksini güçlü şekilde önler.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var14), CollectionsKt.listOf("PONV gelişimini önlemek için Deksametazon ile kombine edildiğinde sinerjik etki göstererek koruyuculuğu anlamlı şekilde artırır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var14 = new String[]{"Dekort", "Onadron"};
      var10008 = CollectionsKt.listOf(var14);
      Pair[] var19 = new Pair[]{TuplesKt.to("ponv_profilaksi", new DoseInfo("4 - 8 mg IV bolus", "Anestezi indüksiyonu sırasında (ameliyat başında) uygulanması etkinliği maksimuma çıkarır.")), TuplesKt.to("havayolu_odemi", new DoseInfo("4 - 12 mg IV (bölünmüş dozlarda)", "Havayolu ödemi şüphesinde veya zor havayolu müdahaleleri sonrasında ödemi önlemek için."))};
      var10013 = MapsKt.mapOf(var19);
      var19 = new Pair[]{TuplesKt.to("ponv_profilaksi", new DoseInfo("0.15 mg/kg IV (Maksimum 8 mg)", "İndüksiyon sırasında yavaş IV bolus.")), TuplesKt.to("krup_stridor", new DoseInfo("0.6 mg/kg IV/IM (Maksimum 16 mg)", "Ekstübasyon sonrası stridor veya krup tablosunda."))};
      var10014 = MapsKt.mapOf(var19);
      var19 = new Pair[]{TuplesKt.to("diyabet", "Glukoz toleransını bozarak ameliyat sonrası kan şekerinde geçici belirgin yükselmeye (hiperglisemi) yol açar."), TuplesKt.to("aktif_enfeksiyon", "Bağışıklık sistemini baskılayabileceği için kontrolsüz aktif enfeksiyonlarda dikkatli olunmalıdır.")};
      var10015 = MapsKt.mapOf(var19);
      var10016 = new PharmacokineticsInfo("1 - 2 saat (antiemetik etki)", "4 - 8 saat", "36 - 72 saat (biyolojik yarı ömür)", "3 - 4.5 saat (plazma yarı ömrü)", "Karaciğerde metabolize edilir, metabolitleri idrarla atılır");
      String[] var22 = new String[]{"Sistemik mantar enfeksiyonları", "Deksametazona karşı bilinen aşırı duyarlılık"};
      var10017 = CollectionsKt.listOf(var22);
      var22 = new String[]{"Uyanık hastalarda hızlı IV bolus enjeksiyonu perineal bölgede şiddetli yanma, kaşıntı ve paresteziye yol açabilir; bu nedenle yavaş veya serum içinde sulandırılarak verilmelidir.", "Yara iyileşmesini hafif geciktirebilir (özellikle yüksek ve tekrarlayan dozlarda)."};
      var10018 = CollectionsKt.listOf(var22);
      var22 = new String[]{"Geçici hiperglisemi", "Perineal kaşıntı/yanma (hızlı enjeksiyonda)", "Uykusuzluk"};
      var10019 = CollectionsKt.listOf(var22);
      var22 = new String[]{"Adrenal Aks Baskılanması (uzun süreli kullanımda)", "Psikoz / Deliryum reaksiyonları"};
      var0[3] = new Drug("dexamethasone", "Deksametazon", "Dexamethasone", "Dexamethasone Sodium Phosphate", var10008, "antiemetic", "H02AB02", "Uzun Etkili Glukokortikoid (Kortikosteroid)", "Prostaglandin sentezini inhibe eder, inflamasyonu ve kapiller geçirgenliği azaltır. CTZ'de serotonin ve endorfin yollarını modüle ederek antiemetik etki gösterir.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var22), CollectionsKt.listOf("Antiemetik etkisi geç başladığı için ameliyat sonunda değil, **indüksiyon sırasında** verilmelidir. Böylece cerrahi bitimindeki postoperatif bulantı pik yaptığı sırada maksimum plazma seviyesine ulaşmış olur."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Ventolin");
      Pair[] var26 = new Pair[]{TuplesKt.to("bronkospazm_akut", new DoseInfo("ETT içinden MDI/Spacer ile 4-8 puf veya inhaler maske ile 2.5-5 mg nebül", "İntraoperatif akut bronkospazm krizlerinde ilk tedavi adımıdır.")), TuplesKt.to("hiperkalemi", new DoseInfo("10 - 20 mg nebülizatör ile sürekli inhalasyon", "Potasyumu hücre içine kaydırmak amacıyla (insülin tedavisinin yanına ek olarak)."))};
      var10013 = MapsKt.mapOf(var26);
      var10014 = MapsKt.mapOf(TuplesKt.to("bronkospazm", new DoseInfo("2-4 puf MDI veya 1.25 - 2.5 mg nebül", "Pediatrik intraoperatif havayolu basınç artışlarında veya astımlı çocuklarda.")));
      var10015 = MapsKt.mapOf(TuplesKt.to("koroner_hastalik", "Beta-2 seçici olsa da yüksek dozlarda beta-1 uyarımı yaparak ciddi taşikardi ve miyokard iskemisi yapabilir."));
      var10016 = new PharmacokineticsInfo("5 - 15 dakika (inhalasyon)", "30 - 60 dakika", "3 - 6 saat", "4 - 6 saat", "Akciğer dokusunda ve karaciğerde sülfat konjugasyonuna uğrar, idrarla atılır");
      String[] var27 = new String[]{"Salbutamole karşı bilinen aşırı duyarlılık", "Şiddetli taşiaritmiler"};
      var10017 = CollectionsKt.listOf(var27);
      var27 = new String[]{"Aşırı dozda sempatik stimülasyon: Titreme (tremor), taşikardi, çarpıntı ve ciddi anksiyete yapabilir.", "Kan potasyum düzeyini hücre içine kaydırma etkisi nedeniyle düşürür (hipokalemi riski)."};
      var10018 = CollectionsKt.listOf(var27);
      var27 = new String[]{"Tremor (el titremesi)", "Taşikardi / Çarpıntı", "Baş ağrısı", "Kas krampları"};
      var10019 = CollectionsKt.listOf(var27);
      var27 = new String[]{"Kardiyak Aritmiler (Atriyal Fibrilasyon, VT)", "Miyokard İskemisi", "Şiddetli Hipokalemi"};
      var0[4] = new Drug("salbutamol", "Salbutamol", "Albuterol / Salbutamol", "Salbutamol Sulfate", var10008, "crisis", "R03AC02", "Selektif Kısa Etkili Beta-2 Adrenerjik Agonist (SABA)", "Bronş düz kaslarındaki beta-2 adrenerjik reseptörleri seçici olarak uyararak adenilat siklazı aktive eder, cAMP artışı ile güçlü bronkodilasyon sağlar.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var27), CollectionsKt.listOf("Entübe hastada nebül formunun akciğere ulaşması zordur. MDI (puf) formu, özel bir konnektör/spacer aracılığıyla solunum devresinin endotrakeal tüpe bağlandığı noktadan sıkılarak doğrudan tüp içine verilmelidir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Magnezyum Sülfat %15");
      Pair[] var31 = new Pair[]{TuplesKt.to("preeklampsi", new DoseInfo("4 - 6 g IV yükleme dozu (15-20 dakikada), ardından 1 - 2 g/saat infüzyon", "Gebelik ilişkili eklampsi nöbetlerinin önlenmesi ve tedavisinde altın standarttır.")), TuplesKt.to("torsades_de_pointes", new DoseInfo("1 - 2 g IV bolus (1-2 dakikada)", "Hayatı tehdit eden Torsades de Pointes aritmisinde ilk tedavidir.")), TuplesKt.to("bronkospazm", new DoseInfo("2 g IV infüzyon (10-20 dakikada)", "Dirençli akut bronkospazm krizlerinde bronkodilasyon amacıyla."))};
      var10013 = MapsKt.mapOf(var31);
      var10014 = MapsKt.mapOf(TuplesKt.to("bronkospazm_direncli", new DoseInfo("25 - 50 mg/kg IV (Maksimum 2 g, 20 dakikada)", "Ağır pediatrik astım krizlerinde kurtarma tedavisi olarak.")));
      var31 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Magnezyum böbreklerle atılır; yetmezlikte birikerek magnezyum toksisitesine yol açar. Dozlar yarı yarıya düşürülmeli, serum seviyeleri izlenmelidir."), TuplesKt.to("noromuskuler_hastalik", "Miyasteni gravis (Myasthenia Gravis) hastalarında nöromüsküler kavşak blokajını tehlikeli düzeyde derinleştirir; kullanılmamalıdır.")};
      var10015 = MapsKt.mapOf(var31);
      var10016 = new PharmacokineticsInfo("Hemen (IV)", "Enjeksiyon sonu", "30 dakika (IV enjeksiyondan sonra)", "4 saat (renal fonksiyon normalken)", "Tamamen böbrekler yoluyla glomerüler filtrasyon ile atılım");
      String[] var33 = new String[]{"Myasthenia Gravis", "İleri derece kalp blokları", "Şiddetli renal yetmezlik (diyaliz gerektiren)"};
      var10017 = CollectionsKt.listOf(var33);
      var33 = new String[]{"Magnezyum Toksisitesi: Derin tendon reflekslerinin (DTR) kaybolması (ilk belirti, >4-5 mEq/L), solunum depresyonu (>10 mEq/L) ve kardiyak arrest (>15 mEq/L). Tedavide IV Kalsiyum Glukonat antidot olarak kullanılır.", "Kas gevşeticilerin (özellikle roküronyum, veküronyum) etkisini belirgin olarak uzatır ve güçlendirir."};
      var10018 = CollectionsKt.listOf(var33);
      var33 = new String[]{"Sıcak basması / Flushing", "Terleme", "Hipotansiyon", "DTR'de azalma"};
      var10019 = CollectionsKt.listOf(var33);
      var33 = new String[]{"Solunum Paralizisi / Apne", "Kardiyak İletim Blokları / Asistoli"};
      var0[5] = new Drug("magnesium_sulfate", "Magnezyum Sülfat", "Magnesium Sulfate", "Magnesium Sulfate Heptahydrate", var10008, "crisis", "B05XA05", "Doğal Kalsiyum Antagonisti ve NMDA Blokörü", "Voltaj bağımlı kalsiyum kanallarını bloke ederek nörotransmitter salınımını ve kas kasılmasını azaltır. Uterus düz kasını gevşetir, membran stabilitesini artırır.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var33), CollectionsKt.listOf("Magnezyum toksisitesi şüphesinde (örn. eklampsi tedavisinde solunum yavaşlaması veya DTR kaybı gelişirse), derhal infüzyon durdurulmalı ve **1 g Kalsiyum Glukonat IV** yavaşça uygulanmalıdır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Transamine");
      Pair[] var37 = new Pair[]{TuplesKt.to("travma_kanama", new DoseInfo("1 g IV bolus (10 dakikada), ardından 1 g IV infüzyon (8 saatte)", "Travmatik kanamalarda ilk 3 saat içinde başlanması mortaliteyi anlamlı azaltır (CRASH-2).")), TuplesKt.to("postpartum_hemoraji", new DoseInfo("1 g IV yavaş bolus", "Kanama devam ederse 30 dakika sonra 2. doz tekrarlanabilir.")), TuplesKt.to("orthopedic_surgery", new DoseInfo("10 - 15 mg/kg IV (indüksiyonda ve cerrahi bitiminde)", "Total diz/kalça protezi operasyonlarında kan kaybını azaltmak için."))};
      var10013 = MapsKt.mapOf(var37);
      var10014 = MapsKt.mapOf(TuplesKt.to("major_cerrahi", new DoseInfo("10 - 20 mg/kg IV bolus", "Pediatrik skolyoz veya kraniyosinostoz gibi majör kanamalı ameliyatlarda.")));
      var37 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrekler yoluyla atılır. Serum kreatinin düzeyine göre dozlar azaltılmalıdır."), TuplesKt.to("tromboemboli", "Aktif tromboembolik hastalığı (DVT, PE, SVO) olanlarda tromboz riskini artırabilir; dikkatli kullanılmalıdır.")};
      var10015 = MapsKt.mapOf(var37);
      var10016 = new PharmacokineticsInfo("5 - 15 dakika", "Enjeksiyon sonu", "3 - 4 saat (dokularda 17 saate kadar uzar)", "2 - 3 saat", "%90'dan fazlası değişmeden idrarla atılır");
      String[] var39 = new String[]{"Aktif tromboembolik süreç veya geçirilmiş venöz/arteriyel tromboz öyküsü", "Subaraknoid kanama (serebral ödem ve enfarktüs riskini artırabilir)"};
      var10017 = CollectionsKt.listOf(var39);
      var39 = new String[]{"Çok hızlı IV enjekte edilirse geçici hipotansiyona yol açabilir; 1 g doz en az 10 dakikada yavaşça verilmelidir.", "Çok yüksek dozlarda (örn. kardiyak cerrahide >50-100 mg/kg) nöbet (konvülsiyon) riskini tetikleyebilir."};
      var10018 = CollectionsKt.listOf(var39);
      var39 = new String[]{"Hipotansiyon (hızlı enjeksiyonda)", "Bulantı/Kusma/Diyare", "Renk görmede geçici bozukluk"};
      var10019 = CollectionsKt.listOf(var39);
      var39 = new String[]{"Derin Ven Trombozu / Pulmoner Emboli", "Nöbet tetiklenmesi"};
      var0[6] = new Drug("tranexamic_acid", "Traneksamik Asit", "Tranexamic Acid", "Tranexamic Acid", var10008, "crisis", "B02AA02", "Antifibrinolitik (Lizin Analoğu)", "Plazminojen üzerindeki lizin bağlama bölgelerini tersinir olarak bloke ederek plazminojene ve fibrine bağlanmasını engeller, fibrin yıkımını (fibrinolizis) durdurur.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var39), CollectionsKt.listOf("Travma ve postpartum kanamalarda traneksamik asitin **ilk 3 saat içinde** uygulanması hayat kurtarıcıdır. 3 saatten sonra başlanan tedavinin fibrinolizis patolojisi değiştiği için klinik yararı olmadığı gibi mortaliteyi artırabileceği gösterilmiştir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var39 = new String[]{"Kalsiyum Sandoz", "Calcium Gluconate %10"};
      var10008 = CollectionsKt.listOf(var39);
      Pair[] var44 = new Pair[]{TuplesKt.to("hiperkalemi_last", new DoseInfo("10% Kalsiyum Glukonat solüsyonundan 10 mL IV (5-10 dakikada)", "EKG'de sivri T, QRS genişlemesi gibi kardiyotoksik bulgular varsa derhal membran stabilizasyonu için.")), TuplesKt.to("masif_transfuzyon", new DoseInfo("Her 4 ünite eritrosit süspansiyonu için 1 g Kalsiyum Glukonat IV", "Sitrat toksisitesine bağlı hipokalsemiyi önlemek için.")), TuplesKt.to("kalsiyum_klorur", new DoseInfo("10% Kalsiyum Klorür solüsyonundan 5 - 10 mL (santral venöz hattan)", "Glukonata göre 3 kat daha fazla elementer kalsiyum içerir; kardiak arrest veya ciddi şokta tercih edilir."))};
      var10013 = MapsKt.mapOf(var44);
      var10014 = MapsKt.mapOf(TuplesKt.to("akut_hipokalsemi", new DoseInfo("0.1 - 0.2 mL/kg (10% Kalsiyum Glukonat) IV yavaş bolus", "Çocuklarda kalsiyum replasmanında moniter eşliğinde yavaşça verilmelidir.")));
      var44 = new Pair[]{TuplesKt.to("karaciger_yetmezligi", "Kalsiyum glukonatın aktif hale gelmesi için karaciğerde metabolize olması gerekir; ciddi yetmezlikte kalsiyum klorür tercih edilmelidir."), TuplesKt.to("dijital_alanlar", "Dijital alan hastalarda kalsiyum enjeksiyonu dijital toksisitesini tetikleyerek öldürücü aritmilere yol açabilir.")};
      var10015 = MapsKt.mapOf(var44);
      var10016 = new PharmacokineticsInfo("Hemen (IV)", "Enjeksiyon sonu", "30 dakika - 2 saat", "Geçerli değil", "Böbrekler (%20) ve dışkı (%80) yoluyla atılım");
      String[] var46 = new String[]{"Hiperkalsemi varlığı", "Dijital (Digoksin) toksisitesi"};
      var10017 = CollectionsKt.listOf(var46);
      var46 = new String[]{"Kalsiyum Klorür damar dışına kaçarsa (ekstravazasyon) çok şiddetli doku nekrozu ve gangren yapar; bu nedenle sadece santral venöz kateterden veya çok güvenli geniş bir periferik yoldan uygulanmalıdır. Glukonat formu bu açıdan daha az irritandır.", "Bikarbonat içeren solüsyonlarla aynı damar yolundan verilmemelidir, kalsiyum karbonat çökeltisi (presipitasyon) oluşturur."};
      var10018 = CollectionsKt.listOf(var46);
      var46 = new String[]{"Sıcaklık hissi", "Ağızda tebeşir tadı", "Lokal venöz irritasyon", "Hipotansiyon (hızlı enjeksiyonda)"};
      var10019 = CollectionsKt.listOf(var46);
      var46 = new String[]{"Şiddetli doku nekrozu (ekstravazasyon)", "Kardiyak Aritmi / Asistoli (hızlı enjeksiyonda)"};
      var0[7] = new Drug("calcium_gluconate", "Kalsiyum Glukonat / Kalsiyum Klorür", "Calcium Gluconate / Calcium Chloride", "Calcium Gluconate / Calcium Chloride", var10008, "crisis", "B05XA07", "Elektrolit / Kalsiyum Replasmanı", "Hücre dışı kalsiyum konsantrasyonunu artırarak miyokard uyarılabilirliğini, iletimini ve kontraktilitesini düzenler. Magnezyum ve potasyumun kardiyak toksik etkilerini antagonize eder.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var46), CollectionsKt.listOf("Kalsiyum glukonat %10'luk çözeltisi 9 mg/mL elementer kalsiyum içerirken; Kalsiyum klorür %10'luk çözeltisi 27 mg/mL elementer kalsiyum içerir. Kardiyak arrest durumunda kalsiyum klorür daha hızlı ve etkilidir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Sodyum Bikarbonat %8.4");
      Pair[] var50 = new Pair[]{TuplesKt.to("asidoz_kriz", new DoseInfo("1 mEq/kg IV yavaş bolus (veya kan gazı açığına göre hesaplanan dozun yarısı)", "pH < 7.15 olan şiddetli metabolik asidoz tablosunda.")), TuplesKt.to("hiperkalemi", new DoseInfo("50 - 100 mEq IV (yavaş infüzyon)", "Asidoz eşlik eden hiperkalemi vakalarında potasyumu hücre içine kaydırmak için.")), TuplesKt.to("toksik_doz_tca", new DoseInfo("1 - 2 mEq/kg IV bolus", "Trisiklik antidepresan (TCA) zehirlenmesinde sodyum kanallarını korumak ve idrarı alkalileştirmek için."))};
      var10013 = MapsKt.mapOf(var50);
      var10016 = new PharmacokineticsInfo("Hemen (IV)", "Enjeksiyon sonu", "1 - 2 saat", "Geçerli değil", "Karbondioksit formunda akciğerlerden ve bikarbonat formunda böbreklerden atılım");
      String[] var51 = new String[]{"Metabolik veya respiratuar alkaloz", "Hipokalsemi (alkalizasyon iyonize kalsiyumu daha da düşürür)", "Şiddetli hiponatremi"};
      var10017 = CollectionsKt.listOf(var51);
      var51 = new String[]{"Alkalizasyon sırasında iyonize kalsiyum seviyeleri hızla düşer; tetani ve aritmileri önlemek için kalsiyum seviyeleri izlenmelidir.", "Metabolize olduğunda CO2 üretir. Eğer hasta yeterince ventile edilmiyorsa (yetersiz solunum frekansı), respiratuar asidoz derinleşebilir."};
      var10018 = CollectionsKt.listOf(var51);
      var51 = new String[]{"Hipernatremı (yüksek sodyum yükü)", "Volüm yüklenmesi / Ödem", "Hipokalemi"};
      var10019 = CollectionsKt.listOf(var51);
      var51 = new String[]{"İntraserebral Kanama (hızlı enjeksiyonda)", "Şiddetli Hipokalsemik Tetani", "Alkaloz"};
      var0[8] = new Drug("sodium_bicarbonate", "Sodyum Bikarbonat", "Sodium Bicarbonate", "Sodium Bicarbonate", var10008, "crisis", "B05XA02", "Sistemik Alkalizan ve Elektrolit Solüsyonu", "Hücre dışı sıvıdaki bikarbonat iyonu konsantrasyonunu artırarak hidrojen iyonlarını nötralize eder ve kan pH'ını yükseltir.", var10013, (Map)null, (Map)null, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var51), CollectionsKt.listOf("Sodyum bikarbonat %8.4'lük hipertonik çözelti 1 mL'de 1 mEq Sodyum ve 1 mEq Bikarbonat içerir. Çok yüksek osmolaliteye sahip olduğu için santral yoldan verilmesi veya periferden son derece yavaş titre edilmesi önerilir."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201067520, (DefaultConstructorMarker)null);
      var51 = new String[]{"Nalokson", "Narcan"};
      var10008 = CollectionsKt.listOf(var51);
      Pair[] var56 = new Pair[]{TuplesKt.to("solunum_depresyonu", new DoseInfo("0.04 - 0.08 mg IV (2-3 dakikada bir titre edilerek)", "Opioid ilişkili solunum depresyonunu geri çevirirken hastayı şiddetli ağrı krizine sokmamak için çok düşük dozlarda titre edilmelidir.")), TuplesKt.to("opioid_toksisite", new DoseInfo("0.4 - 2.0 mg IV/IM/SC", "Yoğun bakım veya acilde ağır aşırı doz opioid zehirlenmesinde."))};
      var10013 = MapsKt.mapOf(var56);
      var10014 = MapsKt.mapOf(TuplesKt.to("opioid_reversal", new DoseInfo("0.01 mg/kg IV/IM", "Çocuklarda opioid solunum depresyonunun geri çevrilmesinde standart başlangıç dozu.")));
      var10015 = MapsKt.mapOf(TuplesKt.to("opioid_bagimlisi", "Fiziksel bağımlılığı olan hastalarda aniden yüksek doz verilmesi şiddetli akut yoksunluk sendromunu (ajitasyon, hipertansiyon, taşikardi, kusma) tetikler."));
      var10016 = new PharmacokineticsInfo("1 - 2 dakika (IV), 2-5 dk (IM)", "5 - 15 dakika", "30 - 90 dakika (Yarı ömrü kısa olduğu için opioid etkisi tekrar ortaya çıkabilir: 'Renarkotizasyon')", "30 - 60 dakika", "Karaciğerde glukuronid konjugasyonu ile inaktif metabolitlerine ayrışır, idrarla atılır");
      var10017 = CollectionsKt.listOf("Naloksona karşı bilinen aşırı duyarlılık");
      String[] var57 = new String[]{"\ud83d\udea8 RENARKOTİZASYON UYARISI: Naloksonun yarı ömrü (30-60 dk), fentanil, morfin veya methadon gibi birçok opioidin yarı ömründen çok daha kısadır. Naloksonun etkisi geçtikten sonra hasta tekrar solunum depresyonuna girebilir. Yakın takip şarttır.", "Kronik ağrılı hastalarda bloğun aniden kalkması sempatik fırtınaya, hipertansiyon krizine ve akut pulmoner ödeme yol açabilir."};
      var10018 = CollectionsKt.listOf(var57);
      var57 = new String[]{"Bulantı/Kusma", "Tremor", "Terleme", "Taşikardi"};
      var10019 = CollectionsKt.listOf(var57);
      var57 = new String[]{"Akut Pulmoner Ödem", "Şiddetli Sempatik Fırtına / Ventriküler Aritmiler", "Şiddetli Yoksunluk Sendromu"};
      var0[9] = new Drug("naloxone", "Nalokson", "Naloxone", "Naloxone Hydrochloride", var10008, "crisis", "V03AB15", "Saf Opioid Reseptör Antagonisti", "Mu, kappa ve delta opioid reseptörlerine yüksek afinite ile bağlanarak agonist etki göstermeden opioidlerin tüm etkilerini yarışmalı olarak bloke eder.", var10013, var10014, var10015, var10016, var10017, var10018, var10019, CollectionsKt.listOf(var57), CollectionsKt.listOf("0.4 mg/1 mL nalokson ampulü 9 mL SF ile karıştırılarak 10 mL'ye tamamlanır (böylece 40 mcg/mL elde edilir). Bu solüsyondan 1-2 mL (40-80 mcg) yavaşça verilerek hastanın solunumu düzelene kadar titre edilir, böylece analjezik etki korunmuş olur."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201064448, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Mivacron");
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.15 - 0.2 mg/kg IV yavaş bolus", "Günübirlik cerrahiler için idealdir. Etki süresi yaklaşık 15-20 dakikadır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.2 mg/kg IV", "Çocuklarda eliminasyon hızı daha yüksektir.")));
      Pair[] var60 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde klirens hafif azalabilir, etki süresi uzayabilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde plazma kolinesteraz üretimi azalacağı için etki süresi belirgin uzar!"), TuplesKt.to("obezite", "İdeal vücut ağırlığına (IBW) göre dozlanmalıdır."), TuplesKt.to("geriatri", "Yaşlılarda plazma kolinesteraz aktivitesi azaldığı için doz %25 düşürülmelidir.")};
      var10015 = MapsKt.mapOf(var60);
      var10016 = new PharmacokineticsInfo("2 - 3 dakika", "3 - 5 dakika", "15 - 20 dakika", "2 - 5 dakika", "Plazma kolinesterazı (Psödokolinesteraz) ile hidroliz");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var61 = new String[]{"Hızlı enjeksiyonda histamin salınımına bağlı hipotansiyon ve bronkospazm yapabilir.", "Psödokolinesteraz eksikliği (atipik enzim) olanlarda uzamış apneye yol açar!"};
      var10018 = CollectionsKt.listOf(var61);
      var61 = new String[]{"Kısa etki süresi nedeniyle günübirlik anestezi uygulamalarında entübasyon ve kısa süreli işlemler için mükemmeldir.", "Etkisi neostigmin ile geri döndürülebilir ancak psödokolinesteraz eksikliğinde ventilatör desteği şarttır."};
      var0[10] = new Drug("mivacurium", "Mivakuryum", "Mivacurium", "Mivacurium", var10008, "nmb", (String)null, "Kısa etkili depolarizan olmayan NMB", "Nikotinik asetilkolin reseptörlerini kompetitif olarak bloke eder, plazma kolinesterazı ile hidroliz edilir.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var61), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Pavulon");
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.08 - 0.1 mg/kg IV bolus", "Uzun süreli cerrahi ve yoğun bakım ventilasyonlarında tercih edilir. Etkisi 60-100 dakika sürer.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.1 mg/kg IV", "Yenidoğanlarda hassasiyet artmıştır.")));
      Pair[] var63 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Ciddi böbrek yetmezliğinde birikir, eliminasyon yarı ömrü belirgin uzar, kontrendikedir!"), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde eliminasyon yavaşlar."), TuplesKt.to("obezite", "İdeal vücut ağırlığına (IBW) göre dozlanmalıdır."), TuplesKt.to("geriatri", "Yaşlılarda eliminasyon yavaşladığı için doz azaltılmalı ve TOF ile izlenmelidir.")};
      var10015 = MapsKt.mapOf(var63);
      var10016 = new PharmacokineticsInfo("3 - 5 dakika", "5 - 8 dakika", "60 - 100 dakika", "2 - 3 saat", "Böbreklerden değişmeden glomerular filtrasyonla atılır, kısmen karaciğer metabolizması");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var64 = new String[]{"Vagolitik etki: Kalp hızında ve kan basıncında belirgin artışa (taşikardi) yol açar.", "Böbrek yetmezliği olanlarda uzamış nöromüsküler blok riski çok yüksektir."};
      var10018 = CollectionsKt.listOf(var64);
      var64 = new String[]{"Uzun etkili bir ajan olduğu için ameliyat sonu uyanmada residual (kalıntı) blokaj riski yüksektir, mutlaka neostigmin/atropin geri çevrilmesi ve TOF takibi yapılmalıdır.", "Kardiyovasküler vagolitik stimülasyon taşikardik hastalarda iskemiyi tetikleyebilir."};
      var0[11] = new Drug("pancuronium", "Pankuronyum", "Pancuronium", "Pancuronium", var10008, "nmb", (String)null, "Uzun etkili depolarizan olmayan NMB", "Nikotinik asetilkolin reseptörlerini kompetitif bloke eder, hafif vagolitik etkisi bulunur.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var64), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var64 = new String[]{"Ebrantil", "Urapidil Ampul"};
      var10008 = CollectionsKt.listOf(var64);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("10 - 50 mg IV yavaş bolus", "Kan basıncı durumuna göre titre edilir, ardından gerekirse 2-9 mg/saat infüzyon başlanır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.5 - 1.0 mg/kg IV", "Pediatrik hipertansif krizlerde çok nadir ve dikkatli kullanılır.")));
      Pair[] var67 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Renal yetmezlikte klirens hafif azalır, ancak belirgin doz modifikasyonu gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde yarı ömrü uzayabilir, dozaj titre edilerek azaltılmalıdır."), TuplesKt.to("obezite", "Normal doz sınırları içinde kilo takibiyle verilir."), TuplesKt.to("geriatri", "Yaşlılarda hipotansiyon riski artmıştır, başlangıç dozları düşük tutulmalıdır.")};
      var10015 = MapsKt.mapOf(var67);
      var10016 = new PharmacokineticsInfo("3 - 5 dakika", "5 - 10 dakika", "4 - 6 saat", "4 - 5 saat", "Karaciğerde metabolize edilir, inaktif metabolitleri idrarla atılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var68 = new String[]{"Hızlı ve yüksek dozlarda kontrolsüz ortostatik veya sistemik hipotansiyon riski.", "Gereksiz kombine vazodilatör kullanımı asistoliye kadar varan ciddi bradikardi yapabilir."};
      var10018 = CollectionsKt.listOf(var68);
      var68 = new String[]{"Sempatolitik etkisi olmasına rağmen refleks taşikardi yapmaması en büyük avantajıdır. İntraoperatif cerrahi uyarılara bağlı akut hipertansif ataklarda (örn. entübasyon, ekstübasyon, diseksiyon) mükemmel etkilidir.", "Koroner arter hastalığı olanlarda güvenli vazodilatasyon sağlar."};
      var0[12] = new Drug("urapidil", "Urapidil", "Urapidil", "Urapidil", var10008, "antiarrhythmic", (String)null, "Alfa-1 Blokör ve 5-HT1A Agonisti (Antihistaminik dışı vazodilatör)", "Periferik postsinaptik alfa-1 reseptörlerini bloke ederek sistemik direnci düşürür, merkezi 5-HT1A reseptörlerini uyararak refleks taşikardiyi önler.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var68), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var68 = new String[]{"Dekstroz %5", "Dekstroz %10", "Dekstroz %50"};
      var10008 = CollectionsKt.listOf(var68);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("10 - 25 g IV (%50 solüsyondan 20-50 mL veya %10 solüsyondan 100-250 mL yavaş IV)", "Hipoglisemi acil tedavisinde verilir, ardından kan şekeri takibiyle idame sıvıya geçilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.25 - 0.5 g/kg IV (%10'luk solüsyondan 2-5 mL/kg)", "Çocuklarda kesinlikle hipertonik %50'lik dekstroz direkt verilmemelidir, damar iritasyonu ve rebound hipoglisemi riski yüksektir; %10'luk tercih edilir.")));
      Pair[] var71 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Normal metabolizma, doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Normal metabolizma."), TuplesKt.to("obezite", "Dozaj standart hipoglisemi protokollerine göredir."), TuplesKt.to("geriatri", "Yaşlılarda sıvı yüklenmesi ve hiperglisemi riski izlenmelidir.")};
      var10015 = MapsKt.mapOf(var71);
      var10016 = new PharmacokineticsInfo("Hemen", "Enjeksiyon sonu", "Metabolik hıza bağlı", "N/A", "Hücresel glikoliz ve glukoz metabolizması");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var72 = new String[]{"%10'dan daha konsantre solüsyonlar periferik damardan hızlı verilirse flebit ve lokal doku nekrozu yapabilir, yavaş veya santral hat tercih edilmelidir.", "Hızlı infüzyon ozmotik diüreze ve hiperglisemik komaya yol açabilir."};
      var10018 = CollectionsKt.listOf(var72);
      var72 = new String[]{"Hiperkalemi krizlerinde (Potasyum > 6.0 mEq/L) sodyum bikarbonat ve kalsiyumun yanında, 10 IU regüler insülin + 50 mL %50 Dekstroz IV 20-30 dakikada verilerek potasyum hücre içine çekilir.", "Kan şekeri takibi şarttır."};
      var0[13] = new Drug("dextrose", "Dekstroz (Glukoz)", "Dextrose (Glucose)", "Dextrose (Glucose)", var10008, "crisis", (String)null, "Karbonhidrat / Hipertonik Solüsyon", "Hücrelere doğrudan glukoz sağlayarak hipoglisemiyi düzeltir, insülinle birlikte potasyumun hücre içine girişini kolaylaştırır.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var72), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var72 = new String[]{"Duocid", "Ampisina", "Unasyn"};
      var10008 = CollectionsKt.listOf(var72);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("1.5 - 3.0 g IV yavaş infüzyon (cerrahi kesiden 30-60 dk önce)", "Cerrahi süre 4 saati aşarsa veya >1500 mL masif kanama olursa intraoperatif doz tekrarlanmalıdır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("50 mg/kg IV (maksimum 3.0 g)", "Yavaş IV infüzyon halinde uygulanmalıdır.")));
      Pair[] var75 = new Pair[]{TuplesKt.to("renal_yetmezlik", "eGFR <30 mL/dk olanlarda yarı ömrü uzar, profilaktik doz sonrası postoperatif idame doz aralığı uzatılmalıdır (12-24 saat)."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Obezite hastalarında üst doz sınırından (3.0 g) verilmesi önerilir."), TuplesKt.to("geriatri", "Yaşlılarda renal fonksiyon takibine göre doz aralığı ayarlanır.")};
      var10015 = MapsKt.mapOf(var75);
      var10016 = new PharmacokineticsInfo("Hemen (IV)", "Infüzyon sonu", "4 - 6 saat", "1 - 2 saat", "Böbreklerden glomerular filtrasyon ve tübüler sekresyonla atılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var76 = new String[]{"Penisilin grubu veya sefalosporin alerjisi (çapraz reaksiyon %5-10) varlığında anafilaksi riski yüksektir!", "Hızlı IV puşe uygulamalarından kaçınılmalıdır, nörotoksik etkiler ve nöbeti tetikleyebilir."};
      var10018 = CollectionsKt.listOf(var76);
      var76 = new String[]{"Karın içi cerrahiler, jinekolojik ve baş-boyun cerrahilerinde mükemmel geniş spektrumlu koruma sağlar.", "Penisilin alerjisi olanlarda klindamisin veya vankomisin tercih edilmelidir."};
      var0[14] = new Drug("ampicillin_sulbactam", "Ampisilin-Sulbaktam", "Ampicillin-Sulbactam", "Ampicillin-Sulbactam", var10008, "antibiotic", (String)null, "Aminopenisilin + Beta-Laktamaz İnhibitörü", "Ampisilin bakteri hücre duvarı sentezini engeller, sulbaktam ise bakteriyel beta-laktamaz enzimlerini inhibe ederek ampisilini korur.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var76), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var76 = new String[]{"Vancocin", "Vancomycin Ampul"};
      var10008 = CollectionsKt.listOf(var76);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("15 mg/kg IV yavaş infüzyon (cerrahi kesiden 60-120 dk önce başlanmalıdır)", "Cerrahi profilakside yavaş verilmesi hayatidir. Cerrahi uzarsa 12 saatte bir tekrarlanır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("15 mg/kg IV yavaş infüzyon", "Pediatrik hastalarda infüzyon süresi en az 60-90 dakika olmalıdır.")));
      Pair[] var79 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Ciddi nefrotoksiktir! Böbrek yetmezliğinde birikir, eGFR takibi ve plazma düzey takibi (TDM) yapılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Gerçek vücut ağırlığına göre dozlanır, maksimum tekil doz 2.0 g'ı aşmamalıdır."), TuplesKt.to("geriatri", "Böbrek fonksiyonları zayıflamış yaşlılarda dozaj aralığı uzatılmalıdır.")};
      var10015 = MapsKt.mapOf(var79);
      var10016 = new PharmacokineticsInfo("Infüzyon sonu", "1 - 2 saat", "12 saat", "6 - 8 saat", "Değişmeden böbreklerden glomerular filtrasyonla idrarla atılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var80 = new String[]{"Red Man (Kırmızı Adam) Sendromu: Hızlı IV infüzyon histamin salınımına yol açarak yüzde, boyunda masif kızarıklık, hipotansiyon ve bronkospazma neden olur. İnfüzyon hızı <10-15 mg/dk (en az 60 dk) olmalıdır.", "Ototoksik ve nefrotoksik etkileri diğer ilaçlarla (örn. gentamisin) kombine edildiğinde katlanır."};
      var10018 = CollectionsKt.listOf(var80);
      var80 = new String[]{"MRSA (Metisiline Dirençli Staph. Aureus) taşıyıcılığı veya penisilin alerjisi olan protez/kardiyak cerrahilerinde profilakside ilk tercihtir.", "Kırmızı Adam Sendromu gelişirse infüzyon derhal durdurulmalı, antihistaminik verilmeli ve daha yavaş hızda tekrar başlanmalıdır."};
      var0[15] = new Drug("vancomycin", "Vankomisin", "Vancomycin", "Vancomycin", var10008, "antibiotic", (String)null, "Glikopeptid grubu antibiyotik", "Bakteriyel hücre duvarı peptidoglikan sentezini D-alanyl-D-alanine bölgesine bağlanarak inhibe eder, hücre ölümünü sağlar.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var80), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var80 = new String[]{"Cleocin", "Clin Ampul", "Klindan"};
      var10008 = CollectionsKt.listOf(var80);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("600 - 900 mg IV yavaş infüzyon (cerrahi kesiden 30-60 dk önce)", "Cerrahi 6 saati aşarsa intraoperatif doz tekrarlanmalıdır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("10 mg/kg IV yavaş infüzyon", "10-20 dakikada yavaş verilmelidir.")));
      Pair[] var83 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Ciddi böbrek yetmezliğinde doz ayarlaması gerekmez, karaciğer eliminasyonu baskındır."), TuplesKt.to("karaciger_yetmezligi", "Ağır karaciğer yetmezliğinde klirens azalabilir, idame dozları azaltılmalıdır."), TuplesKt.to("obezite", "Standart dozlar uygulanır."), TuplesKt.to("geriatri", "Yaşlılarda psödomembranöz enterokolit riski yakından izlenmelidir.")};
      var10015 = MapsKt.mapOf(var83);
      var10016 = new PharmacokineticsInfo("Hemen (IV)", "Infüzyon sonu", "6 saat", "2 - 3 saat", "Karaciğerde aktif metabolitlerine metabolize edilir, safra ve idrarla atılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var84 = new String[]{"Hızlı IV bolus (puşe) enjeksiyonlarda kardiyak toksisite: Şiddetli hipotansiyon, aritmi ve EKG değişiklikleri riski nedeniyle en az 10-20 dakikada infüze edilmelidir.", "Pseudomembranöz Enterokolit: C. difficile üremesine bağlı şiddetli kolit yapma riski diğer antibiyotiklere göre yüksektir."};
      var10018 = CollectionsKt.listOf(var84);
      var84 = new String[]{"Penisilin ve sefalosporin alerjisi olan hastalarda batın içi ve baş-boyun cerrahilerinde mükemmel bir anaerobik profilaksi seçeneğidir.", "Nöromüsküler blokörlerin (kas gevşeticiler) etkisini potansiyalize edebilir."};
      var0[16] = new Drug("clindamycin", "Klindamisin", "Clindamycin", "Clindamycin", var10008, "antibiotic", (String)null, "Lincosamide grubu antibiyotik", "Bakteriyel 50S ribozomal alt birimine geri dönüşümlü bağlanarak protein sentezini (peptid zincir uzamasını) inhibe eder.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var84), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var84 = new String[]{"Genta Ampul", "Gentamicin", "Gentasol"};
      var10008 = CollectionsKt.listOf(var84);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("5 mg/kg IV yavaş infüzyon (cerrahi kesiden 30-60 dk önce)", "Tek doz profilaksi olarak verilir, postoperatif dönemde gerekirse böbrek fonksiyonuna göre idame planlanır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("2.5 - 5.0 mg/kg IV yavaş infüzyon", "Pediatrik hastalarda da yavaş verilmelidir.")));
      Pair[] var87 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Nefrotoksiktir! Böbrek yetmezliğinde birikir, glomerular filtrasyon zayıfsa yarı ömrü masif uzar. eGFR takibi ve plazma düzey takibi yapılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Obez hastalarında dozu hesaplarken Ayarlanmış Vücut Ağırlığı (AdjBW) kullanılmalıdır."), TuplesKt.to("geriatri", "Yaşlılarda böbrek rezervi azaldığı için doz titre edilmeli, böbrek fonksiyonu izlenmelidir.")};
      var10015 = MapsKt.mapOf(var87);
      var10016 = new PharmacokineticsInfo("Infüzyon sonu", "30 - 60 dakika", "8 - 12 saat", "2 - 3 saat (renal yetmezlikte 24-48 saate uzayabilir)", "Değişmeden böbreklerden glomerular filtrasyonla idrarla atılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var88 = new String[]{"Ototoksisite (kalıcı koklear ve vestibüler hasar) ve Nefrotoksisite (akut tübüler nekroz) riski yüksektir.", "Nöromüsküler Blokajın Potansiyalizasyonu: Kas gevşeticilerin etkisini belirgin şekilde uzatır ve pre-sinaptik asetilkolin salınımını azaltarak geri çevrilmesini zorlaştırır."};
      var10018 = CollectionsKt.listOf(var88);
      var88 = new String[]{"Kas gevşetici alan hastalarda gentamisin yapıldığında, ameliyat sonunda hastanın tam uyanması gecikebilir, TOF derinliği kontrol edilmeden hasta ekstübe edilmemelidir.", "Kalsiyum verilmesi gentamisine bağlı nöromüsküler bloğu hafifletebilir."};
      var0[17] = new Drug("gentamicin", "Gentamisin", "Gentamicin", "Gentamicin", var10008, "antibiotic", (String)null, "Aminoglikozid grubu antibiyotik", "Bakteriyel 30S ribozomal alt birimine bağlanarak mRNA kod okunmasını bozar, bakteri protein sentezini irreversibl inhibe eder.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var88), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var88 = new String[]{"Flagyl IV", "Nidazol IV", "Metrazol"};
      var10008 = CollectionsKt.listOf(var88);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("500 mg IV yavaş infüzyon (cerrahi kesiden 30-60 dk önce)", "Genellikle sefazolin veya sefuroksim ile kombine edilerek kolorektal profilakside anaerob koruma amacıyla kullanılır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("15 mg/kg IV yavaş infüzyon", "Pediatrik batın cerrahilerinde güvenle kullanılır.")));
      Pair[] var91 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Ciddi böbrek yetmezliğinde (eGFR <10 mL/dk) metabolitleri birikebilir, dozaj %50 azaltılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Ağır karaciğer yetmezliğinde klirensi %50 oranında düşer, doz azaltılması gerekir."), TuplesKt.to("obezite", "Standart dozlar yeterlidir."), TuplesKt.to("geriatri", "Yaşlılarda karaciğer klirensi azalacağı için yakın takip önerilir.")};
      var10015 = MapsKt.mapOf(var91);
      var10016 = new PharmacokineticsInfo("Infüzyon sonu", "1 saat", "8 saat", "8 saat", "Karaciğerde yoğun şekilde metabolize edilir, idrarla atılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var92 = new String[]{"Alkol ile kullanıldığında Disülfiram Benzeri Reaksiyona (şiddetli hipotansiyon, kusma, taşikardi) yol açar. Postoperatif dönemde alkol kısıtlanmalıdır.", "Hızlı IV infüzyonda tromboflebit ve lokal damar iritasyonu riski vardır."};
      var10018 = CollectionsKt.listOf(var92);
      var92 = new String[]{"Kolorektal ve jinekolojik cerrahilerde anaerobik patojenlere karşı profilaksinin vazgeçilmez parçasıdır.", "Periferik nöropati yapıcı etkisi uzun süreli tedavilerde görülebilir."};
      var0[18] = new Drug("metronidazole", "Metronidazol", "Metronidazole", "Metronidazole", var10008, "antibiotic", (String)null, "Nitroimidazol antibiyotik / Antiprotozoal", "Bakteri hücresine girdikten sonra aktif ara metabolitlerine indirgenir, bu metabolitler bakteri DNA yapısını bozarak sentezini engeller.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var92), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var92 = new String[]{"Lasix Ampul", "Desal Ampul"};
      var10008 = CollectionsKt.listOf(var92);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("20 - 40 mg IV yavaş bolus (1-2 dakikada)", "Sıvı yüklenmesi, akut akciğer ödemi veya kafa içi basınç artışında diürez sağlamak için verilir. Gerekirse infüzyon halinde titre edilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("1 mg/kg IV yavaş bolus (maksimum 40 mg)", "Pediatrik hastalarda sıvı ve elektrolit kaybı çok hızlı gelişir, yakından izlenmelidir.")));
      Pair[] var95 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde tübüler sekresyon azalacağı için etkiye yanıt düşer; istenen diürezi sağlamak için daha yüksek dozlar (örn. 80-200 mg) gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Ağır karaciğer yetmezliği ve sirozu olanlarda elektrolit dengesizliği hepatik komayı tetikleyebilir."), TuplesKt.to("obezite", "Standart diüretik protokolleri izlenir."), TuplesKt.to("geriatri", "Yaşlılarda dehidratasyon, akut böbrek hasarı ve ortostatik hipotansiyon riski son derece yüksektir.")};
      var10015 = MapsKt.mapOf(var95);
      var10016 = new PharmacokineticsInfo("5 - 15 dakika (IV)", "30 dakika", "2 - 3 saat", "1.5 - 2 saat", "Böbreklerden glomerular filtrasyon ve tübüler sekresyonla değişmeden atılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var96 = new String[]{"Ototoksisite: Çok hızlı yüksek doz (>4 mg/dk hızda) enjekte edilirse geçici veya kalıcı işitme kaybı ve çınlamaya yol açabilir.", "Elektrolit Bozuklukları: Şiddetli hipokalemi (kalp aritmilerini tetikler), hiponatremi, hipomagnezemi ve dehidratasyon riski."};
      var10018 = CollectionsKt.listOf(var96);
      var96 = new String[]{"Akut akciğer ödeminde IV enjeksiyon sonrası, diüretik etkisi henüz başlamadan önce dahi güçlü venodilatör etkisi sayesinde venöz dönüşü (preload) azaltarak hastayı saniyeler içinde rahatlatır.", "Hipokalemik hastalarda aritmi riski nedeniyle potasyum düzeyi yakın izlenmeli, gerekirse replasman yapılmalıdır."};
      var0[19] = new Drug("furosemide", "Furosemid", "Furosemide", "Furosemide", var10008, "icu_metabolic", (String)null, "Kıvrım (Loop) Diüretiği", "Henle kulbunun çıkan kalın kolunda Na-K-2Cl kotransporterını inhibe ederek sodyum, potasyum, klor ve su atılımını masif olarak artırır.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var96), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Mannitol %20 Solüsyon");
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.25 - 1.0 g/kg IV yavaş infüzyon (15-30 dakikada)", "Kafa içi basınç (ICP) veya göz içi basınç artışında ödemi çözmek amacıyla titre edilerek verilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.25 - 0.5 g/kg IV yavaş infüzyon", "Pediatrik hastalarda da yavaş verilmelidir.")));
      Pair[] var98 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Akut böbrek yetmezliğinde (anüri durumunda) filtre edilemeyeceği için birikir ve akciğer ödemini tetikler, kesinlikle kontrendikedir!"), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "İdeal veya normal vücut ağırlığı takibine göre verilir."), TuplesKt.to("geriatri", "Yaşlılarda sıvı kaymaları sonucu akut kalp yetmezliği tetiklenebilir.")};
      var10015 = MapsKt.mapOf(var98);
      var10016 = new PharmacokineticsInfo("15 - 30 dakika (ICP düşüşü)", "30 - 60 dakika", "4 - 6 saat", "100 dakika", "Böbreklerden glomerular filtrasyonla değişmeden atılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var99 = new String[]{"Akut Akciğer Ödemi ve Sıvı Yüklenmesi: IV infüzyon başlangıcında interstisyel sıvıyı hızla damar içine çektiği için geçici hipervolemi yaratarak kalp yetmezliği olanlarda akciğer ödemini tetikler.", "Ozmotik Nefroz ve Böbrek Hasarı: Yüksek dozlarda veya susuz kalmış hastalarda böbrek tübüllerine zarar verebilir."};
      var10018 = CollectionsKt.listOf(var99);
      var99 = new String[]{"Kan-beyin bariyeri (BBB) sağlam olan dokularda beyin ödemini çözmede altın standarttır. Oda sıcaklığında kristalleşebilir; şişede kristal görülürse sıcak su banyosunda tamamen çözünmesi sağlanmalı, vücut sıcaklığına geldikten sonra mutlaka filtreli setle uygulanmalıdır.", "İnfaz sırasında idrar çıkışı ve serum ozmolaritesi (hedef <320 mOsm/L) izlenmelidir."};
      var0[20] = new Drug("mannitol", "Mannitol", "Mannitol", "Mannitol", var10008, "icu_metabolic", (String)null, "Ozmotik Diüretik", "Glomerüllerden serbestçe filtre edilir ancak tübüllerden geri emilmez. Tübüler lümende ozmotik basınç yaratarak suyun geri emilimini engeller, beyin ödeminde ise hücre dışı sıvıyı intravasküler alana çekerek kranial basıncı düşürür.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var99), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var99 = new String[]{"%3 Sodyum Klorür (NaCl)", "%7.5 Sodyum Klorür"};
      var10008 = CollectionsKt.listOf(var99);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("150 - 250 mL IV yavaş infüzyon (10-20 dakikada, %3 NaCl)", "Akut kafa içi basınç krizlerinde bolus infüzyon olarak verilir, semptomatik hiponatremi durumlarında ise sodyum açığı formülüne göre titre edilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("3 - 5 mL/kg IV yavaş infüzyon (%3 NaCl)", "Pediatrik kafa travması protokollerinde ICP kontrolü için sıklıkla tercih edilir.")));
      Pair[] var102 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Normal böbrek fonksiyonlarında sodyum ve klor glomerular filtrasyonla elenir. Ağır renal yetmezlikte sodyum yüklenmesi yapabilir."), TuplesKt.to("karaciger_yetmezligi", "Normal metabolizma."), TuplesKt.to("obezite", "Standart acil doz limitlerine göredir."), TuplesKt.to("geriatri", "Yaşlılarda sıvı kayması ve kalp yetmezliği riski yakından izlenmelidir.")};
      var10015 = MapsKt.mapOf(var102);
      var10016 = new PharmacokineticsInfo("Hemen", "İnfüzyon sonu", "Hücresel dengeye bağlı", "N/A", "Böbreklerden idrarla sodyum ve klor atılımı");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var103 = new String[]{"Santral Pontin Miyelinolizis (Ozmotik Demiyelinizasyon Sendromu): Kronik hiponatremi varlığında sodyum düzeyi çok hızlı yükseltilirse beyin sapında demiyelinizasyona bağlı kalıcı felç gelişebilir! Sodyum artış hızı günde 8-10 mEq/L'yi aşmamalıdır.", "Damar İritasyonu: Yüksek ozmolarite nedeniyle periferik damardan verilirse ciddi flebit ve nekroz yapar. Mutlaka Santral Venöz Kateterden verilmelidir."};
      var10018 = CollectionsKt.listOf(var103);
      var103 = new String[]{"Akut intrakranial basınç artışında, kalbi mannitol kadar zorlamadan ve diürez yapmadan ICP'yi çok hızlı düşürür; bu nedenle hemodinamisi sınırdaki kafa travmalı hastalarda ilk tercihlerdendir.", "İdrar çıkışı ve serum sodyumu sık aralıklarla takip edilmelidir."};
      var0[21] = new Drug("hypertonic_saline", "Hipertonik Salin", "Hypertonic Saline (3% NaCl)", "Hypertonic Saline (3% NaCl)", var10008, "icu_metabolic", (String)null, "Hipertonik Sodyum Klorür Solüsyonu", "İntravasküler ozmolariteyi hızla yükselterek beyin hücrelerindeki ödem sıvısını ozmotik gradyanla damar içine çeker, kafa içi basıncı (ICP) düşürür ve serum sodyum düzeyini artırır.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var103), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var103 = new String[]{"Human Albumin %5", "Human Albumin %20", "Zenalb"};
      var10008 = CollectionsKt.listOf(var103);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("12.5 - 25 g IV yavaş infüzyon (örn. %20'lik solüsyondan 50-100 mL veya %5'lik solüsyondan 250-500 mL)", "Sıvı replasmanı, ciddi hipoalbüminemi, karaciğer sirozu (asit drenajı sonrası her 1 litre için 8g albümin) durumlarında verilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("0.5 - 1.0 g/kg IV yavaş infüzyon", "Pediatrik şok resüsitasyonunda veya yenidoğan ödemlerinde kullanılabilir.")));
      Pair[] var106 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Glomerüler hasar yoksa idrarla elenmez. Böbrek yetmezliğinde hacim yüklenmesine dikkat edilmelidir."), TuplesKt.to("karaciger_yetmezligi", "Normal sentez yeri karaciğerdir, yetmezliğinde eksikliği sık görülür."), TuplesKt.to("obezite", "Standart klinik protokoller izlenir."), TuplesKt.to("geriatri", "Yaşlılarda hızlı infüzyon akut akciğer ödemini ve kalp yetmezliğini tetikleyebilir.")};
      var10015 = MapsKt.mapOf(var106);
      var10016 = new PharmacokineticsInfo("Infüzyon sonu", "15 - 30 dakika", "Onkotik etkisi 12 - 24 saat sürer", "15 - 20 gün", "Hücre içinde lizozomal enzimlerle aminoasitlere yıkılır");
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      String[] var107 = new String[]{"Akut Akciğer Ödemi: Onkotik etkisi nedeniyle intravasküler hacmi çok hızlı genişletebileceği için kalp yetmezliği veya ciddi anemisi olanlarda akciğer ödemine yol açabilir.", "Pıhtılaşma Bozukluğu: Çok yüksek hacimlerde verilirse pıhtılaşma faktörlerini dilüe edebilir."};
      var10018 = CollectionsKt.listOf(var107);
      var107 = new String[]{"%20'lik albümin hiperonkotik bir solüsyondur, verilen her 1 mL albümin damar yatağına interstisyumdan 3-4 mL sıvı çekerek plazmayı genişletir. Ciddi sepsis, yanık ve sirozlu asit hastalarında hacim restorasyonu için paha biçilemez bir doğal kolloiddir.", "Enfeksiyon bulaş riskini önlemek için pastörize edilmiştir."};
      var0[22] = new Drug("albumin", "Albumin (İnsan)", "Albumin (Human)", "Albumin (Human)", var10008, "icu_metabolic", (String)null, "Doğal Kolloid Solüsyonu (%5 veya %20)", "Vücudun ana plazma proteinidir. İntravasküler onkotik basıncın %80'ini oluşturur, interstisyel alandaki sıvıyı damar yatağına çekerek plazma hacmini genişletir.", var10013, var10014, var10015, var10016, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var107), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      drugsList = CollectionsKt.listOf(var0);
      $stable = 8;
   }
}
