package com.anesthesiaclinic.anesthesiabriefs.data.repository;

import androidx.compose.runtime.internal.StabilityInferred;
import com.anesthesiaclinic.anesthesiabriefs.data.model.DoseInfo;
import com.anesthesiaclinic.anesthesiabriefs.data.model.Drug;
import com.anesthesiaclinic.anesthesiabriefs.data.model.PharmacokineticsInfo;
import java.util.List;
import java.util.Map;
import kotlin.Metadata;
import kotlin.Pair;
import kotlin.TuplesKt;
import kotlin.collections.CollectionsKt;
import kotlin.collections.MapsKt;
import kotlin.jvm.internal.DefaultConstructorMarker;
import org.jetbrains.annotations.NotNull;

@Metadata(
   mv = {2, 2, 0},
   k = 1,
   xi = 48,
   d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003R\u0017\u0010\u0004\u001a\b\u0012\u0004\u0012\u00020\u00060\u0005¢\u0006\b\n\u0000\u001a\u0004\b\u0007\u0010\b¨\u0006\t"},
   d2 = {"Lcom/anesthesiaclinic/anesthesiabriefs/data/repository/SeedDataDrugsPart4;", "", "<init>", "()V", "drugsList", "", "Lcom/anesthesiaclinic/anesthesiabriefs/data/model/Drug;", "getDrugsList", "()Ljava/util/List;", "app_debug"}
)
@StabilityInferred(
   parameters = 0
)
public final class SeedDataDrugsPart4 {
   @NotNull
   public static final SeedDataDrugsPart4 INSTANCE = new SeedDataDrugsPart4();
   @NotNull
   private static final List drugsList;
   public static final int $stable;

   private SeedDataDrugsPart4() {
   }

   @NotNull
   public final List getDrugsList() {
      return drugsList;
   }

   static {
      Drug[] var0 = new Drug[23];
      List var10008 = CollectionsKt.emptyList();
      Map var10013 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("2.0 - 20.0 mcg/kg/dk IV", "Kardiyojenik şok ve ciddi inotropik yetmezlik tedavisinde titre edilir.")));
      Map var10014 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("2.0 - 20.0 mcg/kg/dk IV", "Kardiyak çıktıyı artırmak amacıyla titre edilerek verilir.")));
      Pair[] var1 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Dozaj ideal veya yağ dışı vücut ağırlığına göre hesaplanmalıdır."), TuplesKt.to("geriatri", "Yaşlılarda taşikardi ve aritmi sıklığı artabilir, en düşük etkili doz tercih edilmelidir.")};
      Map var10015 = MapsKt.mapOf(var1);
      String[] var2 = new String[]{"İdiyopatik hipertrofik subaortik stenoz (IHSS)", "Bileşenlerine karşı bilinen aşırı duyarlılık"};
      List var10017 = CollectionsKt.listOf(var2);
      var2 = new String[]{"Kalp hızı ve miyokard oksijen ihtiyacını artırarak iskemiyi tetikleyebilir.", "Ciddi taşiaritmilere yol açabilir."};
      List var10018 = CollectionsKt.listOf(var2);
      var2 = new String[]{"Kardiyojenik şokta ve kalp yetmezliğinde kalp debisini artırmak için ilk tercihlerdendir.", "Taşikardi ve ventriküler aritmiyi tetikleyebilir."};
      var0[0] = new Drug("dobutamine", "Dobutamin", "Dobutamine", "Dobutamine", var10008, "vasopressor", (String)null, "Selektif Beta-1 Adrenerjik Agonist (İnotropik)", "Esas olarak Beta-1 adrenerjik reseptörleri uyararak kasılma gücünü artırır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var2), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("2.0 - 20.0 mcg/kg/dk IV", "Böbrek (<3 mcg/kg/dk), inotrop (3-10 mcg/kg/dk), vazopresör (>10 mcg/kg/dk) etkiler sağlar.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("2.0 - 20.0 mcg/kg/dk IV", "Çocuklarda hemodinamik desteği ve renal perfüzyonu artırmak için.")));
      Pair[] var5 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Renal perfüzyon artışı tartışmalıdır, doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Dozaj ideal vücut ağırlığına göre yapılmalıdır."), TuplesKt.to("geriatri", "Aritmi ve periferik gangren riski yaşlılarda daha yüksektir.")};
      var10015 = MapsKt.mapOf(var5);
      String[] var6 = new String[]{"Feokromositoma", "Düzeltilmemiş taşiaritmiler"};
      var10017 = CollectionsKt.listOf(var6);
      var6 = new String[]{"Hızlı IV infüzyonlarda taşikardi ve ventriküler aritmilere neden olabilir.", "Ekstravazasyon nekroz yapabilir; santral hat tercih edilmelidir."};
      var10018 = CollectionsKt.listOf(var6);
      var6 = new String[]{"Sempatik uyarım sağlayarak hem nabzı hem tansiyonu yükseltir.", "Son kılavuzlarda septik şokta noradrenaline göre aritmojenik etkisi yüksek olduğu için ikinci plana düşmüştür."};
      var0[1] = new Drug("dopamine", "Dopamin", "Dopamine", "Dopamine", var10008, "vasopressor", (String)null, "Sempatomimetik (Doz Bağımlı Alfa, Beta ve Dopaminerjik Etki)", "Düşük dozda D1 (renal vazodilatasyon), orta dozda Beta-1 (inotrop), yüksek dozda Alfa-1 (vazokonstrüksiyon) uyarır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var6), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Vаѕоstrict");
      var10013 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("0.01 - 0.04 Unite/dk IV", "Dirençli şok tablosunda noradrenalin tedavisine ek olarak uygulanır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("0.0002 - 0.002 Unite/kg/dk IV", "Dirençli septik veya distributif çocuk şokunda.")));
      Pair[] var9 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Dozaj standart infüzyon protokolüne göre titre edilir."), TuplesKt.to("geriatri", "Yaşlılarda koroner ve mezenterik vazokonstrüksiyon riski yüksektir.")};
      var10015 = MapsKt.mapOf(var9);
      String[] var10 = new String[]{"Bileşenlerine karşı bilinen aşırı duyarlılık", "Koroner arter hastalığı (rölatif)"};
      var10017 = CollectionsKt.listOf(var10);
      var10 = new String[]{"Masif vazokonstrüksiyona bağlı miyokard iskemisi veya bağırsak gangreni yapabilir.", "Su intoksikasyonu ve hiponatremi izlenmelidir."};
      var10018 = CollectionsKt.listOf(var10);
      var10 = new String[]{"Asidoz durumlarında dahi vazokonstrüktör etkisini korur, catecholamine dirençli septik şokta tercih edilir.", "Kardiyak arrest resüsitasyonunda standart kılavuzlarda yer alır."};
      var0[2] = new Drug("vasopressin", "Vazopressin (Antidiüretik Hormon)", "Vasopressin", "Vasopressin", var10008, "vasopressor", (String)null, "Antidiüretik Hormon (Vazopressör)", "V1 reseptörlerini uyararak güçlü periferik vazokonstrüksiyon yapar.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var10), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10 = new String[]{"GοNitrо [DSC];", "Νitrο-Βid;", "Νitrο-Dսr;", "Νitrо-Τime;", "Νitroliոguаl;"};
      var10008 = CollectionsKt.listOf(var10);
      var10013 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("5.0 - 100.0 mcg/dk IV", "Başlangıç dozu 5 mcg/dk'dır, hemodinamik yanıta göre 5-10 dk arayla artırılır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("0.25 - 5.0 mcg/kg/dk IV", "Çocuklarda pulmoner hipertansiyon veya sol ventrikül yetmezliğinde.")));
      Pair[] var14 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Dozaj ideal ağırlığa göre yapılmalıdır."), TuplesKt.to("geriatri", "Ortostatik hipotansiyon ve baş ağrısı riski yaşlılarda çok yüksektir.")};
      var10015 = MapsKt.mapOf(var14);
      String[] var15 = new String[]{"Şiddetli hipotansiyon veya hipovolemi", "Son 24-48 saat içinde PDE5 İnhibitörleri (Sildenafil vb.) kullanımı", "Kafa içi basınç artışı"};
      var10017 = CollectionsKt.listOf(var15);
      var15 = new String[]{"Hızla tolerans gelişebilir (24-48 saatlik sürekli infüzyonlarda etki azalır).", "Şiddetli baş ağrısı, refleks taşikardi ve hipotansiyon yapabilir."};
      var0[3] = new Drug("nitroglycerin_glyceryl_trinitrate", "Nitroglycerin", "Nitroglycerin", "Nitroglycerin (glyceryl trinitrate)", var10008, "icu_metabolic", (String)null, "Vazodilatör (Nitrik Oksit Donörü - Venöz Vazodilatör)", "Klinik monograf bilgileri için kaynak dokümana başvurunuz.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, CollectionsKt.listOf(var15), (List)null, (List)null, CollectionsKt.listOf("UpToDate klinik monografından alınmıştır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Nipride RTU");
      var10013 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("0.3 - 5.0 mcg/kg/dk IV", "Hipertansif krizlerde yakın arteriyel tansiyon takibi ile uygulanır (Maks 10 mcg/kg/dk).")));
      var10014 = MapsKt.mapOf(TuplesKt.to("infuzyon", new DoseInfo("0.3 - 5.0 mcg/kg/dk IV", "Pulmoner hipertansiyon veya dirençli sistemik hipertansiyonda.")));
      Pair[] var17 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde tiyosiyanat metaboliti birikerek toksisite yapar, eGFR < 30 ise uzun süreli kullanımdan kaçınılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde siyanür birikim riski belirgin artar, infüzyon hızı sınırlandırılmalıdır."), TuplesKt.to("obezite", "Dozaj ideal ağırlığa göre yapılmalıdır."), TuplesKt.to("geriatri", "Serebral perfüzyon düşüşüne yol açabilir, yaşlılarda çok yavaş titre edilmelidir.")};
      var10015 = MapsKt.mapOf(var17);
      String[] var18 = new String[]{"Kompansatuar hipertansiyon durumları (örneğin aort koarktasyonu)", "Ağır karaciğer ve böbrek yetmezliği"};
      var10017 = CollectionsKt.listOf(var18);
      var18 = new String[]{"Siyanür ve Tiyosiyanat Toksisitesi: 72 saatten uzun infüzyonlarda veya >2 mcg/kg/dk dozlarda toksisite riski izlenmelidir.", "Işığa duyarlıdır, infüzyon seti siyah torba ile korunmalıdır."};
      var10018 = CollectionsKt.listOf(var18);
      var18 = new String[]{"Aort diseksiyonu ve kontrollü hipotansiyon uygulamalarında çok etkilidir.", "Uzun süreli veya yüksek doz kullanımda siyanür toksisitesi riski vardır! Işıkta bozulur, infüzyon seti korunmalıdır."};
      var0[4] = new Drug("nitroprusside", "Sodyum Nitroprussid", "Sodium Nitroprusside", "Nitroprusside", var10008, "vasopressor", (String)null, "Güçlü Doğrudan Alfa/Beta Bağımsız Vazodilatör (Arteriyel ve Venöz)", "Doğrudan nitrik oksit (NO) salarak arter ve venlerde vazodilatasyon sağlar.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var18), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var18 = new String[]{"Νехtеrοոe;", "Ρаϲеrоnе"};
      var10008 = CollectionsKt.listOf(var18);
      Pair[] var22 = new Pair[]{TuplesKt.to("arrest", new DoseInfo("300 mg IV bolus", "VF veya nabızsız VT resüsitasyonunda (ACLS). Gerekirse ikinci doz 150 mg IV uygulanır.")), TuplesKt.to("aritmi", new DoseInfo("150 mg IV infüzyon", "10 dakikada enjekte edilir, ardından 1.0 mg/dk hızla 6 saat idame verilir."))};
      var10013 = MapsKt.mapOf(var22);
      var22 = new Pair[]{TuplesKt.to("arrest", new DoseInfo("5.0 mg/kg IV/IO bolus", "Maksimum 300 mg.")), TuplesKt.to("aritmi", new DoseInfo("5.0 mg/kg IV", "20-60 dakikada yavaş infüzyon şeklinde uygulanır."))};
      var10014 = MapsKt.mapOf(var22);
      var22 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde yarı ömrü uzayabilir, karaciğer enzimleri takip edilmelidir."), TuplesKt.to("obezite", "Dozaj standart ideal ağırlığa göre hesaplanır."), TuplesKt.to("geriatri", "Yaşlılarda bradikardi ve tiroid disfonksiyonu riski yüksektir.")};
      var10015 = MapsKt.mapOf(var22);
      String[] var25 = new String[]{"Sinüs bradikardisi, ikinci veya üçüncü derece AV blok", "Kardiyojenik şok", "İyot aşırı duyarlılığı"};
      var10017 = CollectionsKt.listOf(var25);
      var25 = new String[]{"Ciddi bradikardi ve QT uzaması yapabilir.", "Akciğer fibrozisi, karaciğer hasarı ve tiroid disfonksiyonu (uzun süreli kullanımda) riskleri vardır."};
      var10018 = CollectionsKt.listOf(var25);
      var25 = new String[]{"Akut dirençli VF/Nabızsız VT resüsitasyonunda ilk tercih antiaritmiktir.", "QT mesafesini uzatır, uzun süreli kullanımda tiroid disfonksiyonu ve pulmoner fibrozis yapabilir."};
      var0[5] = new Drug("amiodarone", "Amiodarone", "Amiodarone", "Amiodarone", var10008, "antiarrhythmic", (String)null, "Sınıf III Antiaritmik (Kanal Blokörü)", "Esas olarak potasyum kanallarını bloke eder, ayrıca sodyum, kalsiyum ve alfa/beta reseptörleri inhibe eder.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var25), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var28 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var28);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var29 = new String[]{"Paroksismal supraventriküler taşikardi (PSVT) sonlandırılmasında ilk tercihtir.", "Çok hızlı IV bolus verilmeli, arkasından SF gönderilmelidir. Geçici asistoli hissi yapabilir."};
      var0[6] = new Drug("adenosine", "Adenozin", "Adenosine", "Adenosine", var10008, "antiarrhythmic", (String)null, "Sınıf IV Sınıflanamayan Antiarritmik", "AV düğümünde iletimi yavaşlatır, geçici olarak AV bloğu oluşturur (yarım ömrü <10 saniye).", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var29), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var29 = new String[]{"Βrеviblоc;", "Βrеviblоc in NaCl;", "Βrеvibloс Premixed;", "Βrevibloϲ Premixed DS"};
      var10008 = CollectionsKt.listOf(var29);
      Pair[] var31 = new Pair[]{TuplesKt.to("yukleme", new DoseInfo("500 mcg/kg IV yavaş bolus", "1 dakikada yavaşça enjekte edilir.")), TuplesKt.to("idame", new DoseInfo("50 - 300 mcg/kg/dk IV", "İnfüzyon şeklinde hemodinamik parametrelere göre titre edilir."))};
      var10013 = MapsKt.mapOf(var31);
      var10014 = MapsKt.mapOf(TuplesKt.to("idame", new DoseInfo("50 - 300 mcg/kg/dk IV", "Supraventriküler taşikardilerde yakın EKG takibi ile titre edilir.")));
      var31 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Plazma esterazları ile yıkıldığı için karaciğer yetmezliğinde doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Dozaj ideal vücut ağırlığına göre hesaplanmalıdır."), TuplesKt.to("geriatri", "Hipotansif ve bradikardik yanıt yaşlılarda daha güçlü olabilir.")};
      var10015 = MapsKt.mapOf(var31);
      String[] var33 = new String[]{"Ciddi bradikardi veya kardiyojenik şok", "İkinci veya üçüncü derece AV blok", "Dekompanse kalp yetmezliği"};
      var10017 = CollectionsKt.listOf(var33);
      var33 = new String[]{"Hızlı bolus uygulamalarında ani ve şiddetli hipotansiyon riski vardır.", "Solunum yollarında spazm yapabilir (astımda dikkat)."};
      var10018 = CollectionsKt.listOf(var33);
      var33 = new String[]{"Yarım ömrü çok kısa (9 dk) olduğu için taşikardi ve hipertansiyon krizlerinde son derece güvenlidir.", "Hızlı boluslarda şiddetli hipotansiyona dikkat edilmelidir."};
      var0[7] = new Drug("esmolol", "Esmolol", "Esmolol", "Esmolol", var10008, "antiarrhythmic", (String)null, "Çok Kısa Etkili Beta-1 Selektif Blokör", "Kardiyoselektif kompetitif beta-1 reseptör antagonistidir. Plazma esterazları ile yıkılır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var33), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      Pair[] var36 = new Pair[]{TuplesKt.to("bolus", new DoseInfo("5.0 - 20.0 mg IV yavaş", "2 dakikada enjekte edilir. Gerekirse her 10 dakikada bir tekrarlanabilir (Maks 300 mg).")), TuplesKt.to("infuzyon", new DoseInfo("0.5 - 2.0 mg/dk IV", "Hemodinamik yanıta göre infüzyon hızı ayarlanır."))};
      var10013 = MapsKt.mapOf(var36);
      var10014 = MapsKt.mapOf(TuplesKt.to("bolus", new DoseInfo("0.2 - 1.0 mg/kg IV", "Maksimum tek doz 20 mg bolus.")));
      var36 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Metabolizması yavaşlayabilir, doz yavaş titre edilmelidir."), TuplesKt.to("obezite", "Doz ideal ağırlığa göre yapılmalıdır."), TuplesKt.to("geriatri", "Yaşlılarda ortostatik hipotansiyon ve aşırı bradikardi riski yüksektir.")};
      var10015 = MapsKt.mapOf(var36);
      String[] var38 = new String[]{"Astım veya bronkospazm öyküsü", "Bradikardi, AV blok", "Kardiyojenik şok"};
      var10017 = CollectionsKt.listOf(var38);
      var38 = new String[]{"Periferik vazodilatasyon yaparak tansiyonu düşürürken kalp hızını da azaltır.", "Astım veya ağır KOAH hastalarında bronkospazm yapabilir."};
      var10018 = CollectionsKt.listOf(var38);
      var38 = new String[]{"Gebelik hipertansiyonu (preeklampsi) tedavisinde en güvenli seçeneklerden biridir.", "Nabzı düşürür, astımlı hastalarda bronkospazm riski nedeniyle kaçınılmalıdır."};
      var0[8] = new Drug("labetalol", "Labetalol", "Labetalol", "Labetalol", var10008, "antiarrhythmic", (String)null, "Alfa ve Beta Adrenerjik Reseptör Blokörü (Vazodilatör)", "Hem alfa-1 hem beta reseptörlerini bloke ederek kan basıncını düşürür (Alfa/Beta oranı 1:7 IV).", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var38), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var38 = new String[]{"Kapspargo Sprinkle;", "Լοрrеѕѕοr;", "Toprol XL"};
      var10008 = CollectionsKt.listOf(var38);
      var10013 = MapsKt.mapOf(TuplesKt.to("bolus", new DoseInfo("1.25 - 5.0 mg IV yavaş", "2 dakikada enjekte edilir. Gerekirse her 5 dakikada bir tekrarlanarak toplam 15 mg'a tamamlanabilir.")));
      var10014 = MapsKt.emptyMap();
      Pair[] var42 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde metabolizması yavaşlayabilir, doz azaltılmalıdır."), TuplesKt.to("obezite", "Doz ideal vücut ağırlığına göre hesaplanmalıdır."), TuplesKt.to("geriatri", "Hipotansif yanıt yaşlılarda daha güçlü olabilir.")};
      var10015 = MapsKt.mapOf(var42);
      String[] var43 = new String[]{"Şiddetli bradikardi", "AV blok", "Kardiyojenik şok", "Dekompanse kalp yetmezliği"};
      var10017 = CollectionsKt.listOf(var43);
      var43 = new String[]{"Hipotansiyon ve bradikardi riski yüksektir.", "Uygulama sırasında yakın EKG ve tansiyon takibi gereklidir."};
      var10018 = CollectionsKt.listOf(var43);
      var43 = new String[]{"Kardiyoselektif beta-1 blokördür, intraoperatif taşiaritmilerde nabız kontrolü için kullanılır.", "Bradikardi ve AV blok riski yakından izlenmelidir."};
      var0[9] = new Drug("metoprolol", "Metoprolol", "Metoprolol", "Metoprolol", var10008, "antiarrhythmic", (String)null, "Beta-1 Selektif Blokör", "Kardiyoselektif beta-1 reseptör antagonistidir.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var43), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("bolus", new DoseInfo("5.0 - 20.0 mg IV yavaş", "Operasyon içi hipertansiyon krizlerinde yavaş bolus olarak uygulanır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("bolus", new DoseInfo("0.1 - 0.2 mg/kg IV", "Her 4-6 saatte bir.")));
      Pair[] var46 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Ağır böbrek yetmezliğinde doz aralığı uzatılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Metabolizması yavaşlayabilir, doz titre edilmelidir."), TuplesKt.to("obezite", "Dozaj ideal ağırlığa göre yapılmalıdır."), TuplesKt.to("geriatri", "Miyokardın oksijen tüketimini ve refleks taşikardiyi artırabileceği için yaşlılarda iskemiyi tetikleyebilir.")};
      var10015 = MapsKt.mapOf(var46);
      String[] var47 = new String[]{"Koroner arter hastalığı, iskemik kalp hastalığı", "Mitral valvüler darlık"};
      var10017 = CollectionsKt.listOf(var47);
      var47 = new String[]{"Refleks Taşikardi: Güçlü vazodilatasyon sempatik stimülasyon ve belirgin taşikardi yapar.", "Etki başlangıcı 15-20 dakikadır, hızlı ek dozlardan kaçınılmalıdır."};
      var10018 = CollectionsKt.listOf(var47);
      var47 = new String[]{"Gebelik hipertansiyonunda sıklıkla güvenle kullanılır.", "Refleks taşikardi yapabileceği için koroner arter hastalarında dikkat edilmelidir."};
      var0[10] = new Drug("hydralazine", "Hidralazin", "Hydralazine", "Hydralazine", var10008, "antiarrhythmic", (String)null, "Doğrudan Düz Kas Gevşetici (Vazodilatör)", "Arteriyol düz kaslarında kalsiyum hareketini bozarak vazodilatasyon yapar.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var47), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var47 = new String[]{"Lidomark 1/5 [DSC];", "Lidomark 2/5 [DSC];", "ReadySharp Լiԁοсаine [DSC];", "Χуlοсаine;", "Χуlοcаiոe MPF +RFID;"};
      var10008 = CollectionsKt.listOf(var47);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var51 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var0[11] = new Drug("lidocaine_local_and_regional_anesthetic_and_systemic", "Lidocaine", "Lidocaine", "Lidocaine (systemic)", var10008, "icu_metabolic", (String)null, "Antiarrhythmic Agent, Class Ib; Local Anesthetic", "Klinik monograf bilgileri için kaynak dokümana başvurunuz.", var10013, var10014, MapsKt.mapOf(var51), (PharmacokineticsInfo)null, CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık"), CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir."), (List)null, (List)null, CollectionsKt.listOf("UpToDate klinik monografından alınmıştır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      var51 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var51);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var53 = new String[]{"Bupivakaine kıyasla motor blokaj gücü benzerdir ancak kardiyak güvenlik marjı daha geniştir.", "Rejyonel anestezi ve epidural analjezide sık kullanılır."};
      var0[12] = new Drug("levobupivacaine", "Levobupivakain", "Levobupivacaine", "Levobupivacaine", var10008, "local_anesthetic", (String)null, "Uzun etkili Lokal Anestezik (S-enantiyomer)", "Sodyum kanallarını bloke eder, bupivakaine göre kardiyotoksisitesi daha düşüktür.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var53), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("4% Citanest Plain Dental");
      var10013 = MapsKt.mapOf(TuplesKt.to("lokal_anestezi", new DoseInfo("%1.0 - 2.0 solüsyon", "Maksimum güvenli doz 5.0 mg/kg (epinefrinsiz) veya 7.0 mg/kg (epinefrinli) ile sınırlandırılmalıdır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("lokal_anestezi", new DoseInfo("%1.0 solüsyon", "Çocuklarda maksimum güvenli doz 5.0 mg/kg'dır.")));
      Pair[] var54 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde metabolit birikimi izlenmelidir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde amid tipi lokal anesteziklerin klirensi azalır, doz düşürülmelidir."), TuplesKt.to("obezite", "Doz ideal vücut ağırlığına göre hesaplanmalıdır."), TuplesKt.to("geriatri", "Toksisite ve kardiyovasküler depresyon riski yaşlılarda artar.")};
      var10015 = MapsKt.mapOf(var54);
      String[] var55 = new String[]{"Bileşenlerine karşı bilinen aşırı duyarlılık", "Konjenital methemoglobinemi"};
      var10017 = CollectionsKt.listOf(var55);
      var55 = new String[]{"Methemoglobinemi: Yüksek dozlarda (>600 mg) aktif metaboliti orto-toluidin methemoglobinemiye yol açabilir.", "Lokal Anestezik Sistemik Toksisitesi (LAST) belirtileri yakından izlenmelidir."};
      var10018 = CollectionsKt.listOf(var55);
      var55 = new String[]{"Metaboliti o-toluidin methemoglobinemiye yol açabilir. Tedavisinde metilen mavisi kullanılır.", "Hızlı metabolize olduğu için sistemik toksisite riski düşüktür."};
      var0[13] = new Drug("prilocaine", "Prilokain", "Prilocaine", "Prilocaine", var10008, "local_anesthetic", (String)null, "Amid Grubu Lokal Anestezik", "Sodyum kanallarını bloke eder, yüksek dozda methemoglobinemi riski vardır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var55), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var55 = new String[]{"Ροlοсaiոe;", "Ροlοсаine Dental;", "Ροlοϲаiոe-МРF;", "Scandonest 3% Plain"};
      var10008 = CollectionsKt.listOf(var55);
      var10013 = MapsKt.mapOf(TuplesKt.to("lokal_anestezi", new DoseInfo("%1.0 - 2.0 solüsyon", "Maksimum güvenli doz 5.0 mg/kg (epinefrinsiz) veya 7.0 mg/kg (epinefrinli) ile sınırlandırılmalıdır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("lokal_anestezi", new DoseInfo("%1.0 solüsyon", "Maksimum güvenli doz 5.0 mg/kg'dır.")));
      Pair[] var59 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde klirensi azalır, doz düşürülmelidir."), TuplesKt.to("obezite", "Dozaj ideal ağırlığa göre yapılmalıdır."), TuplesKt.to("geriatri", "Hemodinamik instabilite riski yaşlılarda daha yüksektir.")};
      var10015 = MapsKt.mapOf(var59);
      var10017 = CollectionsKt.listOf("Amid grubu lokal anesteziklere karşı aşırı duyarlılık");
      String[] var60 = new String[]{"Lokal Anestezik Sistemik Toksisitesi (LAST) belirtilerine karşı tedbirli olunmalı, lipid kurtarma paketi hazır tutulmalıdır.", "Yanlışlıkla damar içi enjeksiyondan kaçınılmalıdır."};
      var10018 = CollectionsKt.listOf(var60);
      var60 = new String[]{"Diş hekimliğinde ve periferik sinir bloklarında vazokonstrüktörsüz kullanımı yaygındır.", "Plasentayı kolay geçer, fetal asidozda iyon tuzağı yapabilir."};
      var0[14] = new Drug("mepivacaine", "Mepivakain", "Mepivacaine", "Mepivacaine", var10008, "local_anesthetic", (String)null, "Amid Grubu Lokal Anestezik", "Sodyum kanallarını bloke eder, vazodilatör etkisi düşüktür.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var60), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var60 = new String[]{"Сlοrοtеkаl [DSC];", "Νеѕасaine;", "Νеѕаϲаiոe-MРF"};
      var10008 = CollectionsKt.listOf(var60);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var63 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var63);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var64 = new String[]{"Çok kısa etki süresi nedeniyle günübirlik epidural anestezi için idealdir.", "Kardiyotoksisite riski yok denecek kadar azdır."};
      var0[15] = new Drug("chloroprocaine", "Kloroprokain", "Chloroprocaine", "Chloroprocaine (systemic)", var10008, "local_anesthetic", (String)null, "Kısa etkili Ester grubu Lokal Anestezik", "Sodyum kanallarını bloke eder, plazma kolinesterazı ile çok hızlı yıkılır (yarım ömrü <1 dakika).", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var64), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var64 = new String[]{"Αrtiсаԁeոt;", "Оrаblос;", "Ѕерtοϲainе with Epinephrine 1:100,000;", "Ѕерtοсaiոe with Epinephrine 1:200,000;", "Ζοrсаiոe"};
      var10008 = CollectionsKt.listOf(var64);
      var10013 = MapsKt.mapOf(TuplesKt.to("dosing", new DoseInfo("Dozaj bilgisi belirtilmemiştir.", "")));
      var10014 = MapsKt.emptyMap();
      Pair[] var66 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde doz ayarlaması gerekebilir."), TuplesKt.to("obezite", "Obezite hastalarında dozaj ayarlaması için yeterli veri bulunmamaktadır."), TuplesKt.to("geriatri", "Özel bir doz ayarlaması belirtilmemiştir.")};
      var10015 = MapsKt.mapOf(var66);
      var10017 = CollectionsKt.listOf("Bileşenlerine karşı bilinen aşırı duyarlılık");
      var10018 = CollectionsKt.listOf("Klinik takip ve hastanın yakın izlemi önerilir.");
      String[] var67 = new String[]{"Yapısındaki ek ester bağı sayesinde plazmada da yıkılır, yarı ömrü çok kısadır (20 dk).", "Kemik dokuya penetrasyonu mükemmeldir."};
      var0[16] = new Drug("articaine", "Artikain", "Articaine", "Articaine and epinephrine", var10008, "local_anesthetic", (String)null, "Hızlı etkili Amid-Ester hibrit Lokal Anestezik", "Sodyum kanallarını bloke eder, diş hekimliği ve rejyonel anestezide sık kullanılır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var67), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, true, false, 201162816, (DefaultConstructorMarker)null);
      var67 = new String[]{"РrοAir Digihalеr [DSC];", "PrоAir HFA [DSC];", "ΡrοΑir RespiClick;", "Ρrоventil HFA [DSC];", "Vеntоlin HFA"};
      var10008 = CollectionsKt.listOf(var67);
      var10013 = MapsKt.mapOf(TuplesKt.to("inhalasyon", new DoseInfo("2.5 - 5.0 mg nebül", "Bronkospazm durumunda inhalasyon yoluyla uygulanır.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("inhalasyon", new DoseInfo("2.5 mg nebül", "Ağırlık <20 kg ise 2.5 mg, >20 kg ise 5.0 mg nebül.")));
      Pair[] var69 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Taşikardi ve iskemik kalp hastalığı riskini artırabilir, yaşlılarda dikkat edilmelidir.")};
      var10015 = MapsKt.mapOf(var69);
      String[] var70 = new String[]{"Bileşenlerine karşı bilinen aşırı duyarlılık", "Ciddi koroner yetmezlik"};
      var10017 = CollectionsKt.listOf(var70);
      var70 = new String[]{"Aşırı dozda taşikardi, aritmi ve hipokalemi yapabilir.", "İnhaler kullanımı sonrası solunum sesleri ve klinik yanıt değerlendirilmelidir."};
      var0[17] = new Drug("albuterol_salbutamol", "Albuterol", "Albuterol", "Albuterol (salbutamol)", var10008, "icu_metabolic", (String)null, "Beta-2 Adrenerjik Reseptör Agonisti (Bronkodilatör)", "Klinik monograf bilgileri için kaynak dokümana başvurunuz.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, CollectionsKt.listOf(var70), (List)null, (List)null, CollectionsKt.listOf("UpToDate klinik monografından alınmıştır."), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.listOf("Αtrovent HFA");
      var10013 = MapsKt.mapOf(TuplesKt.to("inhalasyon", new DoseInfo("500 mcg nebül", "Akut astım veya bronkospazm krizlerinde nebülizör ile her 6-8 saatte bir verilir.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("inhalasyon", new DoseInfo("250 mcg nebül", "Bebeklerde ve küçük çocuklarda 250 mcg, büyük çocuklarda 500 mcg nebül.")));
      Pair[] var72 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Doz ayarlaması gerekmez."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Glokom ve idrar retansiyonu olan yaşlılarda dikkat edilmelidir.")};
      var10015 = MapsKt.mapOf(var72);
      var10017 = CollectionsKt.listOf("Bileşenlerine veya atropine karşı aşırı duyarlılık");
      String[] var73 = new String[]{"Ağız kuruluğu ve idrar retansiyonu (özellikle yaşlılarda) yapabilir.", "Gözle temasından kaçınılmalıdır, glokomu tetikleyebilir."};
      var10018 = CollectionsKt.listOf(var73);
      var73 = new String[]{"Akut astım krizlerinde salbutamol ile kombine edildiğinde (Duolin/Combivent) sinerjistik etki gösterir.", "Göz içi basıncını artırabilir, dar açılı glokomda dikkatli olunmalıdır."};
      var0[18] = new Drug("ipratropium", "İpratropiyum Bromür", "Ipratropium Bromide", "Ipratropium (oral inhalation)", var10008, "crisis", (String)null, "Kısa Etkili Antikolinerjik (Bronkodilatör)", "Solunum yollarındaki M3 reseptörlerini bloke ederek bronkodilasyon sağlar.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var73), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var10008 = CollectionsKt.emptyList();
      var10013 = MapsKt.mapOf(TuplesKt.to("kalsiyum_destegi", new DoseInfo("500 - 1000 mg IV", "5-10 dakikada yavaş enjeksiyon. Periferik damardan verilirse flebit ve nekroz yapar (santral hat önerilir).")));
      var10014 = MapsKt.mapOf(TuplesKt.to("kalsiyum_destegi", new DoseInfo("10 - 20 mg/kg IV yavaş", "Çocuklarda yakın EKG ve damar yolu takibi ile.")));
      Pair[] var75 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Ağır böbrek yetmezliğinde hiperkalsemi riski nedeniyle serum kalsiyum takibi yapılmalıdır."), TuplesKt.to("karaciger_yetmezligi", "Kalsiyum klorür iyonize olmak için karaciğer metabolizmasına ihtiyaç duymaz (glukonata göre yetmezlikte avantajlıdır)."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Yaşlılarda kardiyak aritmi riski daha yüksektir, çok yavaş verilmelidir.")};
      var10015 = MapsKt.mapOf(var75);
      String[] var76 = new String[]{"Hiperkalsemi", "Dijital zehirlenmesi (kardiyak arrest riski)"};
      var10017 = CollectionsKt.listOf(var76);
      var76 = new String[]{"Hızlı IV bolus enjeksiyonlarda vazodilatasyon, hipotansiyon ve aritmilere yol açabilir.", "Damar dışına sızması durumunda şiddetli doku nekrozu ve gangren yapar!"};
      var10018 = CollectionsKt.listOf(var76);
      var76 = new String[]{"Kalsiyum glukonata kıyasla 3 kat daha fazla elementer kalsiyum içerir, acil durumlarda tercih edilir.", "Periferik damardan verilirse şiddetli flebit ve nekroz yapabilir, santral yoldan verilmesi önerilir."};
      var0[19] = new Drug("calcium_chloride", "Kalsiyum Klorür", "Calcium Chloride", "Calcium chloride", var10008, "crisis", (String)null, "Kalsiyum Tuzu (Kalsiyum Desteği)", "Miyokard kontraktilitesini artırır, hiperkalemi ve kalsiyum kanal blokörü toksisitesinde kardiyoprotektiftir.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var76), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var76 = new String[]{"HumuLIN R U-500 (CONCENTRATED) [DSC];", "HumuLIN R U-500 KwikPen;", "HumuLIN R [OTC];", "Мyхrеdlin;", "NovoLIN R FlexPen ReliOn [OTC];"};
      var10008 = CollectionsKt.listOf(var76);
      Pair[] var80 = new Pair[]{TuplesKt.to("hiperkalemi", new DoseInfo("10 Unite IV bolus", "%50 Dekstroz (50 mL) ile birlikte uygulanır. Potasyumu hücre içine sokar.")), TuplesKt.to("hiperglisemi", new DoseInfo("1.0 - 5.0 Unite/saat IV", "Kan şekeri seviyelerine göre infüzyon şeklinde titre edilir."))};
      var10013 = MapsKt.mapOf(var80);
      var10014 = MapsKt.mapOf(TuplesKt.to("hiperkalemi", new DoseInfo("0.1 Unite/kg IV bolus", "Dekstroz ile birlikte yavaş bolus enjeksiyon.")));
      var80 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Böbrek yetmezliğinde insülin klirensi azalır, hipoglisemi riski nedeniyle doz azaltılması gerekebilir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde hipoglisemi riski artabilir."), TuplesKt.to("obezite", "Diyabetik obez hastalarda insülin direnci nedeniyle yüksek dozlar gerekebilir."), TuplesKt.to("geriatri", "Hipoglisemiye karşı yaşlıların toleransı düşüktür, kan şekeri yakından izlenmelidir.")};
      var10015 = MapsKt.mapOf(var80);
      String[] var82 = new String[]{"Hipoglisemi", "Bileşenlerine karşı bilinen aşırı duyarlılık"};
      var10017 = CollectionsKt.listOf(var82);
      var82 = new String[]{"Hipoglisemi ve hipokalemi riskine karşı kan şekeri ve potasyum seviyeleri yakın takip edilmelidir.", "İnfüzyon kapatıldıktan sonra da hipoglisemi riski devam edebilir."};
      var10018 = CollectionsKt.listOf(var82);
      var82 = new String[]{"Hiperkalemi acil tedavisinde 10 IU regüler insülin + 50 mL %50 dekstroz IV olarak uygulanır.", "Kan şekeri takibi 30-60 dk arayla yapılmalıdır."};
      var0[20] = new Drug("insulin_regular", "Regüler İnsülin (Kristalize)", "Regular Insulin", "Insulin regular", var10008, "crisis", (String)null, "Kısa Etkili İnsülin", "Glikozun hücre içine girişini sağlar, hiperkalemide glukozla verilerek potasyumu hücre içine sokar.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var82), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var82 = new String[]{"Βаԛѕimi One Pack;", "Baԛsimi Two Pack;", "GlսсаGеո Diagnostic [DSC];", "GlսϲаGen HypoKit [DSC];", "Gvоkе HypoPen 1-Pack;"};
      var10008 = CollectionsKt.listOf(var82);
      Pair[] var86 = new Pair[]{TuplesKt.to("hipoglisemi", new DoseInfo("1.0 mg IM/SC/IV", "Ağır hipoglisemi durumunda damar yolu yoksa IM/SC olarak tercih edilir.")), TuplesKt.to("beta_bloker_toksisitesi", new DoseInfo("5.0 - 10.0 mg IV yavaş", "Pozitif inotropik etki sağlamak amacıyla verilir, ardından 2-10 mg/saat infüzyon başlanır."))};
      var10013 = MapsKt.mapOf(var86);
      var10014 = MapsKt.mapOf(TuplesKt.to("hipoglisemi", new DoseInfo("0.5 mg IM/SC/IV", "Ağırlık <20 kg ise 0.5 mg, >20 kg ise 1.0 mg.")));
      var86 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer glikojen depoları yetersiz olan sirozlu veya aç hastalarda hipoglisemi tedavisinde etkisiz kalabilir."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Kardiyojenik yan etkiler (taşikardi, hipertansiyon) yaşlılarda daha belirgindir.")};
      var10015 = MapsKt.mapOf(var86);
      String[] var88 = new String[]{"Feokromositoma", "İnsülinoma"};
      var10017 = CollectionsKt.listOf(var88);
      var88 = new String[]{"Şiddetli bulantı ve kusmaya yol açabilir, hava yolu korunmalıdır.", "Etki gösterdikten sonra hastaya hızlıca karbonhidrat verilmelidir."};
      var10018 = CollectionsKt.listOf(var88);
      var88 = new String[]{"Beta-blokör ve kalsiyum kanal blokörü doz aşımında ilk tercih antidottur.", "Bulantı kusma yapıcı etkisi çok yüksektir, solunum yolu korunmalıdır."};
      var0[21] = new Drug("glucagon", "Glukagon", "Glucagon", "Glucagon", var10008, "crisis", (String)null, "Pankreatik Hormon (Glukagon)", "Karaciğerde glikojenolizi artırır, kalsiyum girişini artırarak Beta blokör toksisitesinde inotropik etki sağlar.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var88), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      var88 = new String[]{"Alkindi Sprinkle;", "Сοrtef;", "Κhiոdivi;", "Ѕοlս-СОRTΕF"};
      var10008 = CollectionsKt.listOf(var88);
      var10013 = MapsKt.mapOf(TuplesKt.to("inflamasyon", new DoseInfo("100 - 500 mg IV", "İnflamatuar olaylar, astım krizleri veya adrenal yetmezlik durumunda.")));
      var10014 = MapsKt.mapOf(TuplesKt.to("inflamasyon", new DoseInfo("1.0 - 2.0 mg/kg IV", "Akut astım alevlenmesi veya alerjik krizlerde.")));
      Pair[] var92 = new Pair[]{TuplesKt.to("renal_yetmezlik", "Doz ayarlaması gerekmez, sodyum ve sıvı retansiyonu izlenmelidir."), TuplesKt.to("karaciger_yetmezligi", "Karaciğer yetmezliğinde metabolizması gecikebilir."), TuplesKt.to("obezite", "Doz ayarlaması gerekmez."), TuplesKt.to("geriatri", "Hipertansiyon, hiperglisemi ve psikiyatrik yan etkiler yaşlılarda daha sıktır.")};
      var10015 = MapsKt.mapOf(var92);
      String[] var93 = new String[]{"Sistemik mantar enfeksiyonları", "Bileşenlerine karşı bilinen aşırı duyarlılık"};
      var10017 = CollectionsKt.listOf(var93);
      var93 = new String[]{"Akut olarak kan şekerini (hiperglisemi) yükseltebilir.", "Sıvı ve sodyum retansiyonuna (ödem) yol açabilir."};
      var10018 = CollectionsKt.listOf(var93);
      var93 = new String[]{"Anafilakside etkisi geç (4-6 saat sonra) başlar; bu nedenle acil resüsitasyonda ilk tedavi her zaman adrenalindir.", "Adrenal yetmezlikli hastalarda perioperatif stres dozu olarak verilmelidir."};
      var0[22] = new Drug("hydrocortisone", "Hidrokortizon", "Hydrocortisone", "Hydrocortisone (systemic)", var10008, "allergy", (String)null, "Glukokortikoid (Kortikosteroid)", "İnflamasyonu baskılar, anafilaksi ve adrenal yetmezlik/kriz yönetiminde kullanılır.", var10013, var10014, var10015, (PharmacokineticsInfo)null, var10017, var10018, (List)null, (List)null, CollectionsKt.listOf(var93), (String)null, (String)null, (Double)null, (Double)null, (Double)null, (List)null, (String)null, (String)null, false, false, 201162816, (DefaultConstructorMarker)null);
      drugsList = CollectionsKt.listOf(var0);
      $stable = 8;
   }
}
