import json
import re

# Standard English dictionary for filtering
known = {
    "mg", "kg", "mcg", "g", "ml", "iv", "im", "po", "sc", "pr", "micrograms", "milligrams", "kilograms", "bolus", "infusion",
    "adult", "pediatric", "typical", "range", "class", "dose", "premedication", "induction", "maintenance", "or", "and", "with",
    "fruit", "juice", "not", "available", "in", "this", "local", "card", "verify", "from", "institutional", "protocol", "drug",
    "monograph", "of", "to", "for", "a", "an", "the", "selective", "receptor", "agonist", "antagonist", "blocker", "calcium",
    "salt", "support", "product", "derivative", "blood", "factor", "coagulation", "concentrate", "cofactor", "uterotonic",
    "analog", "hormone", "carbohydrate", "solution", "osmotic", "diuretic", "loop", "synthetic", "strong", "positive",
    "allosteric", "modulator", "reversal", "antidote", "nutritional", "lipid", "reversible", "acetylcholinesterase",
    "inhibitor", "cyclodextrin", "sympathomimetic", "catabolic", "vasopressor", "inotropic", "dihydropyridine",
    "cephalosporin", "antibiotic", "antiprotozoal", "antipyretic", "antispasmodic", "aminopenicillin", "beta-lactamase",
    "glycopeptide", "lincosamide", "nitroimidazole", "ester", "amide", "amide-ester", "depolarizing", "non-depolarizing",
    "benzylisoquinoline", "antihistamine", "antiarrhythmic", "adrenergic", "vasodilator", "alkalinizing", "inorganic",
    "inhalational", "anesthetic", "gas", "benzodiazepine", "acting", "group", "sedation", "clinical", "decision", "mode",
    "information", "serves", "as", "general", "guideline", "must", "be", "titrated", "carefully", "patient-specific",
    "response", "propofol", "midazolam", "ketamine", "dantrolene", "tramadol", "nitrous", "oxide", "highly", "potent",
    "ultra", "short-acting", "intermediate-acting", "long-acting", "alpha", "beta", "gamma", "mu", "opioid", "non-opioid",
    "cox", "nsaid", "nonsteroidal", "anti-inflammatory", "unclassified", "oxytocin", "pure", "enantiomer", "nitric",
    "donor", "venous", "arterial", "weak", "reuptake", "halothane", "isoflurane", "sevoflurane", "desflurane", "etomidate",
    "thiopental", "fentanyl", "sufentanil", "alfentanil", "remifentanil", "morphine", "meperidine", "pethidine",
    "hydromorphone", "buprenorphine", "naloxone", "flumazenil", "neostigmine", "sugammadex", "succinylcholine",
    "rocuronium", "vecuronium", "atracurium", "cisatracurium", "pancuronium", "mivacurium", "lidocaine", "bupivacaine",
    "levobupivacaine", "ropivacaine", "prilocaine", "mepivacaine", "procaine", "chloroprocaine", "articaine",
    "epinephrine", "norepinephrine", "phenylephrine", "ephedrine", "dopamine", "dobutamine", "milrinone", "vasopressin",
    "esmolol", "metoprolol", "labetalol", "propranolol", "atenolol", "carvedilol", "nicardipine", "clevidipine",
    "diltiazem", "verapamil", "nitroprusside", "nitroglycerin", "hydralazine", "clonidine", "dexmedetomidine",
    "atropine", "glycopyrrolate", "scopolamine", "ipratropium", "albuterol", "salbutamol", "terbutaline",
    "aminophylline", "theophylline", "magnesium", "sulfate", "calcium-chloride", "calcium-gluconate", "sodium-bicarbonate",
    "mannitol", "furosemide", "acetazolamide", "spironolactone", "hydrochlorothiazide", "insulin", "dextrose", "glucagon",
    "dexamethasone", "methylprednisolone", "hydrocortisone", "prednisolone", "triamcinolone", "ranitidine", "famotidine",
    "metoclopramide", "ondansetron", "granisetron", "dolasetron", "palonosetron", "aprepitant", "fosaprepitant",
    "droperidol", "haloperidol", "promethazine", "diphenhydramine", "dimenhydrinate", "meclizine", "hydroxyzine",
    "acetaminophen", "paracetamol", "ketorolac", "ibuprofen", "naproxen", "diclofenac", "indomethacin", "celecoxib",
    "aspirin", "clopidogrel", "heparin", "enoxaparin", "dalteparin", "warfarin", "dabigatran", "rivaroxaban", "apixaban",
    "protamine", "tranexamic", "acid", "epsilon-aminocaproic", "vitamin-k", "phytonadione", "desmopressin", "ddavp",
    "fibrinogen", "factor-viii", "factor-ix", "pcc", "albumin", "hetastarch", "pentastarch", "dextran", "gelatin",
    "crystalloid", "colloid", "saline", "lactated", "ringers", "plasmalyte", "penicillin", "ampicillin", "sulbactam",
    "amoxicillin", "clavulanate", "cefazolin", "cefuroxime", "ceftriaxone", "ceftazidime", "cefepime", "imipenem",
    "meropenem", "ertapenem", "vancomycin", "gentamicin", "tobramycin", "amikacin", "clindamycin", "linezolid",
    "metronidazole", "ciprofloxacin", "levofloxacin", "moxifloxacin", "azithromycin", "erythromycin", "clarithromycin",
    "fluconazole", "amphotericin", "caspofungin", "voriconazole", "acyclovir", "ganciclovir", "oseltamivir",
    "octreotide", "terlipressin", "somatostatin", "glucagon-like", "peptide", "liraglutide", "semaglutide", "dulaglutide",
    "exenatide", "empagliflozin", "dapagliflozin", "canagliflozin", "sitagliptin", "saxagliptin", "linagliptin",
    "pioglitazone", "rosiglitazone", "glimepiride", "glipizide", "glyburide", "metformin", "acarbose", "miglitol",
    "pramlintide", "bromocriptine", "cabergoline", "levothyroxine", "liothyronine", "methimazole",
    "propylthiouracil", "lugols", "potassium", "iodide", "hydrocortisone-sodium-succinate", "solu-cortef",
    "methylprednisolone-sodium-succinate", "solu-medrol", "dexamethasone-sodium-phosphate", "decadron",
    "triamcinolone-acetonide", "kenalog", "betamethasone", "celestone", "fludrocortisone", "florinef", "aldosterone",
    "spironolactone-aldactone", "eplerenone", "inspra", "amiloride", "triamterene", "furosemide-lasix",
    "bumetanide-bumex", "torsemide-demadex", "ethacrynic-acid", "edecrin", "chlorothiazide", "diuril",
    "hydrochlorothiazide-microzide", "chlorthalidone", "indapamide", "metolazone", "zaroxolyn", "mannitol-osmitrol",
    "isosorbide", "glycerin", "urea", "acetazolamide-diamox", "methazolamide", "dorzolamide", "brinzolamide",
    "conivaptan", "vaprisol", "tolvaptan", "samsca", "demeclocycline", "fludrocortisone-florinef", "desmopressin-ddavp",
    "vasopressin-pitressin", "terlipressin-glypressin", "ornipressin", "selepressin", "argipressin", "phenylephrine-neo-synephrine",
    "norepinephrine-levophed", "epinephrine-adrenalin", "dopamine-intropin", "dobutamine-dobutrex", "isoproterenol-isuprel",
    "ephedrine-sulfate", "mephentermine", "metaraminol", "methoxamine", "midodrine", "albuterol-proventil",
    "ventolin", "levalbuterol-xopenex", "pirbuterol", "terbutaline-brethine", "metaproterenol", "salmeterol-serevent",
    "formoterol-foradil", "arformoterol", "indacaterol", "olodaterol", "vilanterol", "ipratropium-atrovent",
    "tiotropium-spiriva", "aclidinium", "umeclidinium", "glycopyrrolate-robinul", "atropine-sulfate",
    "scopolamine-transderm-scop", "hyoscyamine", "dicyclomine", "propantheline", "methantheline", "benztropine",
    "trihexyphenidyl", "biperiden", "procyclidine", "oxyphencyclimine", "glycopyrronium", "revefenacin",
    "tiotropium", "ipratropium", "aclinidium", "umeclidinium", "formoterol", "salmeterol", "indacaterol",
    "olodaterol", "vilanterol", "albuterol", "levalbuterol", "metaproterenol", "terbutaline", "pirbuterol",
    "bitolterol", "fenoterol", "procaterol", "ritodrine", "isoxsuprine", "nylidrin", "isoproterenol",
    "epinephrine", "norepinephrine", "dopamine", "dobutamine", "phenylephrine", "methoxamine", "mephentermine",
    "metaraminol", "ephedrine", "midodrine", "clonidine", "guanfacine", "guanabenz", "methyldopa", "moxonidine",
    "rilmenidine", "dexmedetomidine-precedex", "tizanidine", "lofexidine", "fadomidine", "medetomidine",
    "xylazine", "detomidine", "romifidine", "apraclonidine", "brimonidine", "dipivefrin", "epinephryl",
    "pilocarpine", "carbachol", "bethanechol", "methacholine", "acetylcholine", "cevimeline", "neostigmine-prostigmin",
    "pyridostigmine", "mestinon", "ambenonium", "demecarium", "physostigmine", "antilirium", "tacrine",
    "donepezil", "aricept", "rivastigmine", "exelon", "galantamine", "razadyne", "edrophonium", "tensilon",
    "sugammadex-bridion", "neostigmine", "pyridostigmine", "edrophonium", "physostigmine", "donepezil",
    "rivastigmine", "galantamine", "tacrine", "echothiophate", "isoflurophate", "sarin", "soman", "tabun",
    "vx", "malathion", "parathion", "diazinon", "chlorpyrifos", "dichlorvos", "trichlorfon", "metrifonate",
    "pralidoxime", "protopam", "obidoxime", "trimedoxime", "diacetylmonoxime", "atropine", "scopolamine",
    "glycopyrrolate", "ipratropium", "tiotropium", "aclidinium", "umeclidinium", "revefenacin", "glycopyrronium",
    "pirenzepine", "telenzepine", "dicyclomine-bentyl", "hyoscyamine-levsin", "propantheline-pro-banthine",
    "glycopyrrolate-robinul", "scopolamine-transderm-scop", "benztropine-cogentin", "trihexyphenidyl-artane",
    "biperiden-akineton", "procyclidine-kemadrin", "oxyphencyclimine-daricon", "hexocyclium", "mepenzolate",
    "methscopolamine", "valethamate", "pipenzolate", "tridihexethyl", "isopropamide", "clidinium",
    "otilonium", "cimetropium", "prifinium", "timepidium", "fenpiverinium", "glycopyrronium-bromide",
    "tiotropium-bromide", "ipratropium-bromide", "aclidinium-bromide", "umeclidinium-bromide",
    "revefenacin-yupelri", "atropine-methonitrate", "atropine-oxide", "scopolamine-butylbromide",
    "scopolamine-methonitrate", "scopolamine-hydrobromide", "homatropine", "homatropine-methylbromide",
    "tropicamide", "cyclopentolate", "eucatropine", "pirenzepine", "telenzepine", "tripitamine",
    "darifenacin", "solifenacin", "oxybutynin", "tolterodine", "fesoterodine", "trospium", "flavoxate",
    "propiverine", "imidafenacin", "vamicamide", "solifenacin-vesicare", "darifenacin-enablex",
    "oxybutynin-ditropan", "tolterodine-detrol", "fesoterodine-toviaz", "trospium-sanctura",
    "flavoxate-urispas", "propiverine-detrunorm", "imidafenacin-uritos", "vesicare", "enablex",
    "ditropan", "detrol", "toviaz", "sanctura", "urispas", "detrunorm", "uritos", "succinylcholine-anectine",
    "quelicin", "suxamethonium", "rocuronium-zemuron", "vecuronium-norcuron", "atracurium-tracrium",
    "cisatracurium-nimbex", "pancuronium-pavulon", "mivacurium-mivacron", "pipecuronium", "arduan",
    "doxacurium", "neuromax", "tubocurarine", "metocurine", "gallamine", "alcuronium", "fazadinium",
    "decamethonium", "hexamethonium", "pentolinium", "mecamylamine", "trimethaphan", "tetraethylammonium",
    "sugammadex-bridion", "sugammadex", "bridion", "neostigmine", "pyridostigmine", "edrophonium",
    "physostigmine", "atropine", "glycopyrrolate", "scopolamine", "lidocaine-xylocaine", "bupivacaine-marcaine",
    "sensorcaine", "levobupivacaine-chirocaine", "ropivacaine-naropin", "prilocaine-citanest",
    "mepivacaine-carbocaine", "polocaine", "procaine-novocain", "chloroprocaine-nesacaine",
    "articaine-septocaine", "cocaine", "tetracaine", "pontocaine", "benzocaine", "hurricaine",
    "proparacaine", "alcaine", "benoxinate", "dyclonine", "pramoxine", "prilocaine-lidocaine-emla",
    "emla", "lidocaine", "bupivacaine", "levobupivacaine", "ropivacaine", "prilocaine", "mepivacaine",
    "procaine", "chloroprocaine", "articaine", "cocaine", "tetracaine", "benzocaine", "proparacaine",
    "dyclonine", "pramoxine", "dibucaine", "cinchocaine", "oxethazaine", "quanisocaine", "butacaine",
    "piperocaine", "amylocaine", "hexylcaine", "propoxycaine", "pyrrocaine", "etanidocaine",
    "butt-paste", "anesthetic", "analgesic", "antiarrhythmic", "vasoconstrictor", "epinephrine",
    "phenylephrine", "fentanyl-sublimaze", "sufentanil-sufenta", "alfentanil-alfenta",
    "remifentanil-ultiva", "morphine-duramorph", "astramorph", "infumorph", "meperidine-demerol",
    "pethidine", "hydromorphone-dilaudid", "buprenorphine-subutex", "naloxone-narcan",
    "flumazenil-romazicon", "butorphanol", "stadol", "nalbuphine", "nubain", "pentazocine",
    "talwin", "deocine", "dezocine", "dalgan", "profadol", "ketocyclazocine", "cyclazocine",
    "alazocine", "bremazocine", "pentazocine", "phenazocine", "levorphanol", "levo-dromoran",
    "methadone", "dolophine", "propoxyphene", "darvon", "dextropropoxyphene", "tramadol-ultram",
    "tapentadol", "nucynta", "codeine", "hydrocodone", "vicodin", "lortab", "oxycodone",
    "oxycontin", "percocet", "oxymorphone", "opana", "heroin", "diacetylmorphine", "acetylmorphine",
    "monoacetylmorphine", "nicomorphine", "dipropanoylmorphine", "desomorphine", "krokodil",
    "methyldesorphine", "heterocodeine", "active", "selective", "antagonist", "agonist",
    "blocker", "gaba-a", "positive", "allosteric", "modulator", "short-acting", "highly",
    "potent", "clinical", "dosing", "monograph", "adult", "pediatric", "typical", "range",
    "dose", "premedication", "induction", "maintenance", "intravenous", "intramuscular",
    "oral", "subcutaneous", "rectal", "transdermal", "epidural", "intrathecal", "spinal",
    "percutaneous", "topical", "inhalation", "inhalational", "gas", "agent", "anesthetic",
    "analgesic", "sedative", "hypnotic", "muscle", "relaxant", "neuromuscular", "blocker",
    "class", "mechanism", "action", "indicated", "indication", "contraindication", "warning",
    "precautions", "safety", "level", "urgent", "emergency", "standard", "non-absolute",
    "titrate", "titrated", "titration", "patient-specific", "response", "hemodynamic",
    "effects", "cardiovascular", "respiratory", "depression", "apnea", "hypotension",
    "hypertension", "bradycardia", "tachycardia", "arrhythmia", "dysrhythmia", "qt",
    "prolongation", "torsades", "pointes", "ventricular", "fibrillation", "tachycardia",
    "asystole", "cardiac", "arrest", "resuscitation", "cpr", "acls", "pals", "bls",
    "airway", "obstruction", "laryngospasm", "bronchospasm", "desaturation", "hypoxia",
    "hypercapnia", "hypocapnia", "acidosis", "alkalosis", "metabolic", "respiratory",
    "lactate", "base", "excess", "deficit", "abg", "interpretation", "ventilation",
    "oxygenation", "perfusion", "shock", "index", "sepsis", "septic", "anaphylaxis",
    "anaphylactic", "reaction", "histamine", "release", "mast", "cell", "degranulation",
    "epinephrine", "norepinephrine", "phenylephrine", "ephedrine", "vasopressin",
    "atropine", "glycopyrrolate", "scopolamine", "diphenhydramine", "famotidine",
    "methylprednisolone", "hydrocortisone", "dexamethasone", "albuterol", "salbutamol",
    "ipratropium", "magnesium", "sulfate", "calcium", "chloride", "gluconate",
    "sodium", "bicarbonate", "mannitol", "furosemide", "dextrose", "insulin",
    "glucagon", "dantrolene", "ryanodine", "receptor", "antagonist", "malignant",
    "hyperthermia", "crisis", "last", "local", "anesthetic", "systemic", "toxicity",
    "lipid", "emulsion", "intralipid", "resuscitation", "amiodarone", "lidocaine",
    "avoid", "anticoagulant", "regional", "anesthesia", "block", "neuraxial",
    "hematoma", "asra", "guidelines", "heparin", "enoxaparin", "dalteparin",
    "warfarin", "dabigatran", "rivaroxaban", "apixaban", "clopidogrel", "aspirin",
    "nsaid", "ketorolac", "ibuprofen", "naproxen", "diclofenac", "celecoxib",
    "acetaminophen", "paracetamol", "tramadol", "opioid", "receptor", "agonist",
    "reuptake", "inhibitor", "serotonin", "syndrome", "seizure", "convulsion",
    "naloxone", "flumazenil", "neostigmine", "sugammadex", "reversal", "antidote",
    "nitrous", "oxide", "oxygen", "air", "nitrogen", "carbon", "dioxide",
    "helium", "xenon", "halothane", "isoflurane", "sevoflurane", "desflurane",
    "mac", "minimum", "alveolar", "concentration", "solubility", "partition",
    "coefficient", "blood-gas", "oil-gas", "induction", "emergence", "recovery",
    "agitation", "delirium", "shivering", "nausea", "vomiting", "ponv", "rescue",
    "ondansetron", "granisetron", "dolasetron", "palonosetron", "aprepitant",
    "droperidol", "haloperidol", "metoclopramide", "promethazine", "dexamethasone",
    "scopolamine", "propofol", "midazolam", "ketamine", "etomidate", "thiopental",
    "fentanyl", "sufentanil", "remifentanil", "morphine", "meperidine", "pethidine",
    "succinylcholine", "rocuronium", "vecuronium", "atracurium", "cisatracurium",
    "pancuronium", "mivacurium", "lidocaine", "bupivacaine", "ropivacaine",
    "epinephrine", "norepinephrine", "phenylephrine", "ephedrine", "vasopressin",
    "esmolol", "labetalol", "metoprolol", "nicardipine", "clevidipine", "nitroprusside",
    "nitroglycerin", "hydralazine", "clonidine", "dexmedetomidine", "atropine",
    "glycopyrrolate", "albuterol", "magnesium", "calcium", "sodium", "mannitol",
    "furosemide", "insulin", "dextrose", "glucagon", "hydrocortisone", "methylprednisolone",
    "dexamethasone", "ondansetron", "metoclopramide", "diphenhydramine", "acetaminophen",
    "ketorolac", "heparin", "enoxaparin", "protamine", "tranexamic", "vitamin-k",
    "desmopressin", "fibrinogen", "factor-viii", "pcc", "albumin", "crystalloid",
    "cefazolin", "clindamycin", "vancomycin", "gentamicin", "metronidazole",
    "neostigmine", "sugammadex", "naloxone", "flumazenil", "dantrolene", "tramadol",
    "nitrous-oxide", "propofol-dosing", "midazolam-dosing", "ketamine-dosing",
    "dantrolene-dosing", "tramadol-dosing", "nitrous-oxide-dosing", "adults",
    "children", "infants", "neonates", "pregnancy", "lactation", "elderly",
    "renal", "impairment", "hepatic", "obesity", "cardiac", "disease",
    "pulmonary", "neurological", "musculoskeletal", "endocrinological",
    "gastrointestinal", "hematological", "immunological", "psychiatric",
    "surgical", "procedure", "preoperative", "intraoperative", "postoperative",
    "anesthesia-briefs", "anesthesia", "clinic", "education", "only", "professional",
    "clinical", "evaluation", "direct", "patient", "assessment", "disclaimer",
    "mode", "decision", "support", "typical", "range", "guideline", "carefully",
    "specific", "rate", "mg/kg/hr", "mcg/kg/min", "mcg/kg/hr", "mg/kg/min",
    "mg/kg", "mcg/kg", "g/kg", "ml/kg", "mg/min", "mcg/min", "ml/min", "g/min",
    "ml/hr", "drops/min", "units/min", "units/hr", "units/kg", "percent",
    "vol%", "mac-fraction", "concentration", "flow", "l/min", "ml/min",
    "partial", "pressure", "oxygen", "tension", "pao2", "paco2", "etco2",
    "spo2", "sao2", "svo2", "scvo2", "fio2", "pip", "plat", "peep", "cpap",
    "bipap", "hfnc", "eclsa", "ecmo", "iabp", "lvad", "rvad", "bivad",
    "pacemaker", "icd", "crt", "emi", "mri", "radiation", "safety",
    "surgical", "diathermy", "cautery", "monopolar", "bipolar", "harmonic",
    "scalpel", "laser", "airway", "fire", "explosion", "hazard", "risk",
    "prevention", "management", "emergency", "crisis", "checklist",
    "cognitive", "aid", "help", "support", "decision-support-mode",
    "not-specified", "not-defined", "unknown", "none-specified",
    "verify-monograph", "institutional-protocol", "drug-monograph",
    "professional-guideline", "educational-use", "no-liability",
    "consult-senior", "ask-help", "rescue-protocol", "escalation-plan",
    "backup-plan", "alternative-strategy", "contraindicated", "allergy",
    "hypersensitivity", "cross-reactivity", "anaphylaxis-risk", "severe",
    "adverse", "events", "complications", "side-effects", "toxicity",
    "overdose", "reversal-agent", "antidote-therapy", "monitoring",
    "ecg", "nibp", "art-line", "cvp", "pap", "pawp", "co", "ci", "sv",
    "svr", "pvr", "lvsw", "rvsw", "eeg", "bis", "entropy", "tof",
    "train-of-four", "double-burst", "tetanic", "stimulation",
    "post-tetanic-count", "ptc", "emg", "mmg", "phg", "acceleromyography",
    "amg", "kinemyography", "kmg", "piezoelectric", "sensor",
    "transducer", "calibration", "baseline", "twitch", "fade",
    "recovery-ratio", "safe-extubation", "cuff-leak", "stridor",
    "laryngospasm-risk", "airway-edema", "steroid-therapy",
    "epinephrine-nebulizer", "re-intubation-prep", "difficult-airway-cart",
    "fiberoptic-scope", "videolaryngoscope", "lma-rescue", "fastrach",
    "supreme", "solus", "auraonce", "auragain", "i-gel", "laryngeal",
    "tube", "combitube", "king-lt", "retrograde", "intubation",
    "blind-nasal", "awake-intubation", "tracheostomy", "cricothyroidotomy",
    "needle-decompression", "surgical-airway", "cico-rescue",
    "escalate-immediately", "call-for-help", "team-communication",
    "crisis-resource-management", "crm", "human-factors", "situational",
    "awareness", "fixation-error", "cognitive-lockup", "bias",
    "decision-making", "clinical-judgment", "textbook-grade",
    "board-prep", "exam-review", "study-guide", "practice-questions",
    "multiple-choice", "single-best-answer", "multiple-true-false",
    "viva-voce", "structured-oral", "soe", "osce", "practical-exam",
    "european-diploma", "edaic", "american-board", "ab", "basic",
    "advanced", "applied", "certification", "maintenance-of-certification",
    "moca", "continuous-professional-development", "cpd", "cme",
    "medical-education", "residency-training", "fellowship",
    "specialist", "consultant", "attending", "anesthesiologist",
    "anesthetist", "nurse-anesthetist", "crna", "anesthesia-assistant",
    "aa", "resident", "fellow", "medical-student", "healthcare-professional",
    "teamwork", "patient-safety", "quality-improvement", "audit",
    "compliance", "standard-of-care", "evidence-based-medicine",
    "ebm", "systematic-review", "meta-analysis", "randomized-controlled-trial",
    "rct", "observational-study", "cohort", "case-control", "case-series",
    "case-report", "expert-opinion", "consensus-guidelines",
    "practice-parameters", "standards", "advisories", "statements",
    "position-papers", "policy", "protocol", "procedure-manual",
    "operating-room", "or", "anesthesia-workstation", "ventilator",
    "vaporizer", "scavenging", "breathing-system", "circle-system",
    "mapleson", "bain", "jackson-rees", "ayres-t-piece", "non-rebreathing",
    "valve", "soda-lime", "baralyme", "amgorg", "carbon-dioxide-absorbent",
    "compound-a", "carbon-monoxide", "fire-risk", "desflurane-degradation",
    "sevoflurane-degradation", "isoflurane-degradation", "halothane-degradation",
    "heat-generation", "absorbent-desiccation", "moisture-content",
    "fresh-gas-flow", "fgf", "closed-circuit-anesthesia", "low-flow",
    "minimal-flow", "metabolic-flow", "xenon-anesthesia", "closed-loop",
    "automated-delivery", "target-controlled-infusion", "tci",
    "marsh", "schnider", "minto", "gepts", "dyck", "pharmacokinetic",
    "pk", "pharmacodynamic", "pd", "compartment", "model", "one-compartment",
    "two-compartment", "three-compartment", "volume-of-distribution",
    "vd", "clearance", "cl", "half-life", "t12", "elimination",
    "context-sensitive", "half-time", "csht", "decrement-time",
    "effect-site", "equilibration", "ke0", "biophase", "potency",
    "efficacy", "affinity", "intrinsic-activity", "full-agonist",
    "partial-agonist", "inverse-agonist", "competitive-antagonist",
    "non-competitive-antagonist", "irreversible-antagonist",
    "allosteric-interaction", "synergism", "addition", "potentiation",
    "antagonism", "tolerance", "tachyphylaxis", "dependence",
    "addiction", "withdrawal", "abuse-potential", "controlled-substance",
    "scheduling", "prescribing-regulations", "records", "audit-trail",
    "adverse-drug-reactions", "adr", "pharmacovigilance", "yellow-card",
    "fda", "ema", "mhra", "tga", "health-canada", "who", "national-database",
    "local-registry", "reporting-system", "safety-alerts", "recalls",
    "shortages", "alternative-supply", "substitution-policy",
    "therapeutic-equivalence", "generic-substitution", "brand-name",
    "trade-name", "chemical-name", "inn", "usanc", "ban", "rinn",
    "naming-conventions", "tall-man-lettering", "sound-alike-look-alike",
    "sala", "lasa", "bar-coding", "smart-pumps", "dose-error-reduction",
    "ders", "drug-library", "hard-limits", "soft-limits", "clinical-override",
    "double-check", "independent-verification", "high-alert-medications",
    "apins", "pinch", "potassium", "insulin", "narcotics", "chemo",
    "heparin", "neuromuscular-blockers", "epidural-medications",
    "concentrated-electrolytes", "vials", "ampoules", "syringes",
    "labeling", "iso-standards", "color-coding", "blue-neuromuscular",
    "red-induction", "yellow-tranquilizers", "orange-opioids",
    "green-anticholinergics", "purple-vasopressors", "grey-local-anesthetics",
    "pink-other", "black-stripes-antagonists", "label-content",
    "concentration-per-ml", "total-amount", "expiry-date", "preparer-initials",
    "date-time-prepared", "sterility", "contamination-risk", "infection-control",
    "single-patient-use", "multi-dose-vials", "preservative-free",
    "preservative-containing", "benzyl-alcohol", "methylparaben",
    "sulfites", "metabisulfite", "allergy-triggers", "asthma-cautions",
    "propofol-lipid-vehicle", "egg-lecithin", "soybean-oil", "glycerol",
    "preservative-edta", "sodium-metabisulfite", "benzyl-alcohol",
    "microbial-growth", "12-hour-rule-infusion", "6-hour-rule-syringe",
    "strict-aseptic-technique", "hand-hygiene", "swabbing-vial-rubber",
    "needle-safety", "sharps-disposal", "stick-injury-protocol",
    "occupational-health", "post-exposure-prophylaxis", "pep",
    "hiv", "hbv", "hcv", "transmission-prevention", "personal-protective",
    "equipment", "ppe", "gloves", "apron", "mask", "goggles", "shield",
    "lead-apron", "thyroid-shield", "radiation-protection", "scavenging-efficiency",
    "waste-anesthetic-gases", "wag", "exposure-limits", "niosh", "osha",
    "chronic-exposure-risks", "spontaneous-abortion", "congenital-anomalies",
    "bone-marrow-depression", "vitamin-b12-inactivation", "nitrous-oxide-toxicity",
    "methionine-synthase", "homocysteine-accumulation", "neuropathy",
    "subacute-combined-degeneration", "myeloneuropathy", "megaloblastic",
    "anemia", "leukopenia", "thrombocytopenia", "immunotoxicity",
    "dna-synthesis-disruption", "teratogenicity", "reproductive-toxicology",
    "environmental-impact", "greenhouse-gas-potential", "gwp",
    "desflurane-high-gwp", "sevoflurane-lower-gwp", "nitrous-oxide-ozone-depletion",
    "carbon-footprint", "sustainable-anesthesia", "green-operating-theater",
    "minimal-flow-delivery", "intravenous-alternative", "tiva", "total-intravenous",
    "anesthesia", "target-controlled", "infusion", "propofol-remifentanil",
    "eco-friendly-practice", "waste-reduction", "recycling", "sustainability",
    "greenhouse-effect", "global-warming", "climate-change", "policy-guidelines",
    "professional-responsibility", "ethics", "patient-centered-care"
}

# Exhaustive Turkish-to-English dictionary for direct substitution
EXHAUSTIVE_REPLACEMENTS = {
    # MH Crisis / Crisis mapping
    "Mh kriz": "MH Crisis",
    "Mh Kriz": "MH Crisis",
    "mh kriz": "MH crisis",
    "MH kriz": "MH crisis",
    "MH Kriz": "MH Crisis",
    "Malignant Kriz": "Malignant Crisis",
    "malignant kriz": "malignant crisis",
    "kriz": "crisis",
    "Kriz": "Crisis",

    # Analgesia
    "Analjezi": "Analgesia",
    "analjezi": "analgesia",
    "Analjezik": "Analgesic",
    "analjezik": "analgesic",
    "Analjezikler": "Analgesics",
    "analjezikler": "analgesics",

    # Direct Acting Skeletal Muscle Relaxant
    "Direkt Acting": "Direct-Acting",
    "direkt acting": "direct-acting",
    "Direkt": "Direct",
    "direkt": "direct",
    "Iskelet Kasi Gevsetici": "Skeletal Muscle Relaxant",
    "iskelet kasi gevsetici": "skeletal muscle relaxant",
    "Iskelet Kası Gevşetici": "Skeletal Muscle Relaxant",
    "Iskelet": "Skeletal",
    "iskelet": "skeletal",
    "Kasi": "Muscle",
    "kasi": "muscle",
    "Kası": "Muscle",
    "kası": "muscle",
    "Gevsetici": "Relaxant",
    "gevsetici": "relaxant",
    "Gevşetici": "Relaxant",
    "gevşetici": "relaxant",
    "Gevseticiler": "Relaxants",
    "gevseticiler": "relaxants",

    # Tramadol / Weak Opioid Agonist
    "Zayif Mu-Opioid": "Weak Mu-Opioid",
    "zayif mu-opioid": "weak mu-opioid",
    "Zayif": "Weak",
    "zayif": "weak",
    "Monoamin Geri Alim Inhibitor": "Monoamine Reuptake Inhibitor",
    "monoamin geri alim inhibitor": "monoamine reuptake inhibitor",
    "Monoamin Geri Alım İnhibitörü": "Monoamine Reuptake Inhibitor",
    "Monoamin": "Monoamine",
    "monoamin": "monoamine",
    "Geri Alim": "Reuptake",
    "geri alim": "reuptake",
    "Geri Alım": "Reuptake",
    "geri alım": "reuptake",
    "Alim": "Reuptake",
    "alim": "reuptake",
    "Alım": "Reuptake",
    "alım": "reuptake",
    "Inhibitor": "Inhibitor",
    "inhibitor": "inhibitor",
    "Inhibitoru": "Inhibitor",
    "inhibitoru": "inhibitor",
    "İnhibitör": "Inhibitor",
    "inhıbıtor": "inhibitor",
    "İnhibitörü": "Inhibitor",

    # Inorganic inhalational
    "Inorganik": "Inorganic",
    "inorganik": "inorganic",
    "İnorganik": "Inorganic",
    "inhalasyon": "inhalational",
    "Inhalasyon": "Inhalational",
    "inhaler": "inhalational",
    "Inhaler": "Inhalational",
    "anestezik": "anesthetic",
    "Anestezik": "Anesthetic",
    "anestezikler": "anesthetics",
    "Anestezikler": "Anesthetics",

    # General leftovers
    "Akut": "Acute", "akut": "acute",
    "Alerji": "Allergy", "alerji": "allergy",
    "Alfa": "Alpha", "alfa": "alpha",
    "Alkaloid": "Alkaloid", "alkaloid": "alkaloid",
    "Antiemetik": "Antiemetic", "antiemetik": "antiemetik",
    "Antikoagulasyon": "Anticoagulation", "antikoagulasyon": "anticoagulation",
    "Bagimli": "Dependent", "bagimli": "dependent",
    "Birinci": "First", "birinci": "first",
    "Bradikardi": "Bradycardia", "bradikardi": "bradycardia",
    "Bronkodilator": "Bronchodilator", "bronkodilator": "bronchodilator",
    "Bronkospazm": "Bronchospasm", "bronkospazm": "bronchospasm",
    "Cerrahi": "Surgical", "cerrahi": "surgical",
    "Cok": "Highly", "cok": "highly",
    "Dogal": "Natural", "dogal": "natural",
    "Dopamin": "Dopamine", "dopamin": "dopamine",
    "Dopaminerjik": "Dopaminergic", "dopaminerjik": "dopaminergic",
    "Doseaj": "Dosage", "doseaj": "dosage",
    "Enantiyomer": "Enantiomer", "enantiyomer": "enantiomer",
    "Eter": "Ether", "eter": "ether",
    "Etki": "Effect", "etki": "effect",
    "Florlu": "Fluorinated", "florlu": "fluorinated",
    "Glukonat": "Gluconate", "glukonat": "gluconate",
    "Halojenli": "Halogenated", "halojenli": "halogenated",
    "Hiperkalemi": "Hyperkalemia", "hiperkalemi": "hyperkalemia",
    "Hipertansiyon": "Hypertension", "hipertansiyon": "hypertension",
    "Hipoglisemi": "Hypoglycemia", "hipoglisemi": "hypoglycemia",
    "Hizli": "Rapid", "hizli": "rapid",
    "Inflamasyon": "Inflammation", "inflamasyon": "inflammation",
    "Kanal": "Channel", "kanal": "channel",
    "Kanama": "Bleeding", "kanama": "bleeding",
    "Kolloid": "Colloid", "kolloid": "colloid",
    "Kusak": "Generation", "kusak": "generation",
    "Orta": "Intermediate", "orta": "intermediate",
    "Prokinetik": "Prokinetic", "prokinetik": "prokinetic",
    "Rektal": "Rectal", "rektal": "rectal",
    "Rutin": "Routine", "rutin": "routine",
    "Ryanodin": "Ryanodine", "ryanodin": "ryanodine",
    "Saf": "Pure", "saf": "pure",
    "Unite": "Units", "unite": "units",
    "Uzun": "Long", "uzun": "long",
    "Yenidogan": "Neonatal", "yenidogan": "neonatal",
    "adrenaline": "epinephrine",
    "adrenalinsiz": "without epinephrine",
    "antagonizmasi": "antagonism",
    "ardindan": "followed by",
    "artirilarak": "increased",
    "baslanmalidir": "should be started",
    "bilgisi": "information",
    "cevirme": "conversion",
    "direncli": "resistant",
    "disi": "except",
    "edilerek": "by titrating",
    "eslik": "accompanied",
    "hibrit": "hybrid",
    "hipokalsemi": "hypocalcemia",
    "infiltrasyon": "infiltration",
    "kesiden": "from incision",
    "lik": "fold",
    "luk": "fold",
    "maskeyle": "with mask",
    "minuteda": "per minute",
    "nebul": "nebulized",
    "once": "before",
    "orn": "e.g.",
    "profilaksi": "prophylaxis",
    "profilaksisi": "prophylaxis",
    "protamin": "protamine",
    "puf": "puff",
    "slowca": "slowly",
    "solusyon": "solution",
    "solusyondan": "from solution",
    "tek": "single",
    "titre": "titrated"
}

def clean_text_with_exhaustive_map(text):
    if not text:
        return ""
    t = text
    # Sort replacements by key length in descending order
    # so that longer compound words are replaced first!
    sorted_replacements = sorted(EXHAUSTIVE_REPLACEMENTS.items(), key=lambda x: len(x[0]), reverse=True)
    
    for k, v in sorted_replacements:
        # Match only full word boundaries!
        # \b doesn't work perfectly on boundaries with non-alphanumeric chars or dots,
        # so we can use lookarounds for a clean boundary check!
        escaped_k = re.escape(k)
        # Lookbehind and lookahead to ensure we only replace full words
        # (characters surrounding must not be alphabetic characters)
        pattern = r'(?<![a-zA-ZğüşöçıİĞÜŞÖÇ])' + escaped_k + r'(?![a-zA-ZğüşöçıİĞÜŞÖÇ])'
        t = re.sub(pattern, v, t)
        
    return t

# Run check on test elements
def run_test():
    with open("scratch/final_assistant_expanded.json", "r", encoding="utf-8") as f:
        db = json.load(f)
        
    drugs = [x for x in db if x["category"] == "drug_dosing"]
    
    unrecognized_words = set()
    tr_chars = "çğıöşüÇĞİÖŞÜ"
    
    for d in drugs:
        en_str = json.dumps(d["en"], ensure_ascii=False)
        cleaned_en_str = clean_text_with_exhaustive_map(en_str)
        # Verify if any leaked words remain
        words = re.findall(r'[a-zA-ZğüşöçıİĞÜŞÖÇ]+', cleaned_en_str)
        for w in words:
            wl = w.lower()
            if any(c in tr_chars for c in w):
                unrecognized_words.add(w)
            elif wl not in known and len(wl) > 2:
                # Also check if it's not a common english word in our replacements
                unrecognized_words.add(w)
                
    print(f"Remaining unrecognized words: {len(unrecognized_words)}")
    for w in sorted(list(unrecognized_words)):
        print(f"  - {w}")

if __name__ == "__main__":
    run_test()
