// Builds docs/app.html (the live app preview embedded three times on the homepage)
// from site-src/app.html by compiling its <script type="text/babel"> blocks ahead of time.
//
// Why: the page used to ship @babel/standalone (~3 MB) and compile the JSX in the
// browser. The homepage embeds this page in three same-origin iframes, which share the
// parent's main thread, so every compile froze scrolling. The transform here is the
// same @babel/standalone version and preset the browser used, so the output behaves
// identically.
//
// Usage (from the repo root):  node tools/build-app.mjs
// Edit site-src/app.html, never docs/app.html — the latter is overwritten.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(root, "tools", "package.json"));
const Babel = require("@babel/standalone");

const src = readFileSync(join(root, "site-src", "app.html"), "utf8");

const BABEL_TAG = /\s*<script src="https:\/\/unpkg\.com\/@babel\/standalone@[^"]+"[^>]*><\/script>/;
if (!BABEL_TAG.test(src)) throw new Error("babel standalone <script> tag not found — update tools/build-app.mjs");

let blocks = 0;
const out = src
  .replace(BABEL_TAG, "")
  .replace(/<script type="text\/babel" data-presets="react">([\s\S]*?)<\/script>/g, (_, code) => {
    blocks++;
    const { code: js } = Babel.transform(code, { presets: ["react"], comments: false });
    if (js.includes("</script")) throw new Error("compiled block contains </script");
    return "<script>\n" + js + "\n</script>";
  });

if (!blocks) throw new Error("no text/babel blocks found");
if (/text\/babel/.test(out)) throw new Error("a text/babel block was left uncompiled");

const banner = "<!-- GENERATED by tools/build-app.mjs from site-src/app.html — do not edit by hand. -->\n";
// Keep the @dsCard marker on line 1, where the design tooling looks for it.
const nl = out.indexOf("\n") + 1;
const final = out.startsWith("<!-- @dsCard") ? out.slice(0, nl) + banner + out.slice(nl) : banner + out;
writeFileSync(join(root, "docs", "app.html"), final);
console.log(`docs/app.html: compiled ${blocks} JSX blocks, ${(out.length / 1024).toFixed(0)} KB`);
